### ISSUE TITLE
Reduce edmf compilation times

### ISSUE THREAD

**Issue by trontrytel** [CliMA/ClimaAtmos.jl#1019]
@charleskawczynski , @dennisYatunin - could you at some point type out the possible things to try here?

**Comment by charleskawczynski** [comment]
- Abolish Cases.jl module (including every time requires recompilation of entire RHS) by moving all of its pieces into the appropriate places in src/. This is basically connected to bullet points in #949.
 - Add an invalidations script, similar to [CC#972](https://github.com/CliMA/ClimaCore.jl/pull/972) and [CC#968](https://github.com/CliMA/ClimaCore.jl/pull/968)

**Comment by charleskawczynski** [comment]
Fix coming soon, see https://github.com/CliMA/ClimaTimeSteppers.jl/issues/88#issuecomment-1338483380

**Comment by charleskawczynski** [comment]
Closed by https://github.com/CliMA/ClimaTimeSteppers.jl/pull/85
