### ISSUE TITLE
Edmf coriolis  vs ClimaAtmos coriolis

### ISSUE THREAD

**Issue by trontrytel** [CliMA/ClimaAtmos.jl#1028]
Is there a way to further unify the coriolis treatment between the full model and edmf single column setups?

See PR: https://github.com/CliMA/ClimaAtmos.jl/pull/1026

CC: @trontrytel , @charleskawczynski , @szy21

**Comment by szy21** [comment]
I think the Coriolis parameter is the same thing between the full model and the single column. We unified it [here](https://github.com/CliMA/ClimaAtmos.jl/blob/0dcefdd67eabb5fb18376d061daed8e0e95aecf8/examples/hybrid/staggered_nonhydrostatic_model.jl#L89). What special about edmf is that it has the f x ug term, which the full model doesn't have.
