### ISSUE TITLE
JFNK job is not reproducible

### ISSUE THREAD

**Issue by charleskawczynski** [CliMA/ClimaAtmos.jl#1098]
The JFNK job is not reproducible. It has `--regression_test true` and yet some jobs have recently passed and failed without having changed the regression tables:

 - https://buildkite.com/clima/climaatmos-ci/builds/5388 (staging, passed)
 - https://buildkite.com/clima/climaatmos-ci/builds/5391 (main, broken)

This is either due to randomness, or it's unstable. Maybe we can try reducing the timestep? cc @dennisYatunin. For now, I may change this to soft-fail to allow other PRs to merge

**Comment by dennisYatunin** [comment]
This was fixed in #1105. #1021 removes the soft-fail flag.
