### ISSUE TITLE
vertical diffusion does not work with --surface_scheme default to nothing

### ISSUE THREAD

**Issue by jiahe23** [CliMA/ClimaAtmos.jl#1142]
I tried to run a moist held suarez set up without surface flux (zero flux)
```
CA_EXAMPLE=examples/
DRIVER=$CA_EXAMPLE'hybrid/driver.jl'
julia1.8 --project=$CA_EXAMPLE --threads=8 $DRIVER --forcing held_suarez --moist equil --vert_diff true --precip_model 0M --dt 450secs --t_end 900secs
```
and got the following error
```
nested task error: type NamedTuple has no field sfc_inputs
    Stacktrace:
     [1] getproperty
       @ ./Base.jl:38 [inlined]
     [2] get_surface_fluxes!( ......
......
@ ClimaAtmos ~/Documents/CliMA/ClimaAtmos.jl/src/tendencies/vertical_diffusion_boundary_layer.jl:244
```

I think we want zero flux when `--surface_scheme` is default to nothing.

**Comment by charleskawczynski** [comment]
What's the expected behavior when `surface_scheme = nothing` w.r.t. `sfc_conditions::SurfaceFluxConditions` (the output of SurfaceFluxes.jl)? Should that just mean that

```julia
sfc_conditions[colidx].ρτxz = 0
sfc_conditions[colidx].ρτyz = 0
sfc_conditions[colidx].shf = 0
sfc_conditions[colidx].lhf = 0
sfc_conditions[colidx].Ch = 0
```
? Or is it just for `ρτxz` and `ρτyz`?

Also, was this working recently / a while ago? I may have broke this but I think it should be an easy fix

**Comment by charleskawczynski** [comment]
I think the main thing we need to know is: what is the role of `get_surface_fluxes!` (or `sfc_conditions`) when `surface_scheme = nothing`

**Comment by jiahe23** [comment]
I was thinking not touching the surface flux package but assign zeros when specifying bc's for the operators (e.g., [here](https://github.com/CliMA/ClimaAtmos.jl/blob/main/src/tendencies/vertical_diffusion_boundary_layer.jl#L381)
