### ISSUE TITLE
Add a diffusion test case for Krylov methods

### ISSUE THREAD

**Issue by trontrytel** [CliMA/ClimaAtmos.jl#1156]
- [ ] ~~1D diffusion of moisture and enthalpy. This could be done in  Clima Timesteppers? (@dennisYatunin, @charleskawczynski )~~ Moved to ClimaTimesteppers
- [ ] 3D on a sphere test case in ClimaAtmos:  Diffuse a blob of (1) moisture and  (2) moisture and enthalpy. We can start from the hydrostatically balanced test case. Run explicit and then implicit to see if the results match. (@dennisYatunin , @szy21 )

**Comment by trontrytel** [comment]
@szy21 , @charleskawczynski , @dennisYatunin - Are we still trying to add those test cases? (I'll open a separate issue for the simple plume test case for edmf)

**Comment by dennisYatunin** [comment]
Yeah a 1D diffusion problem will be added in ClimaTimeSteppers

**Comment by trontrytel** [comment]
Sounds good. I guess we come back to the 3D one once we pass the 1D. Do you have an issue in the Timesteppers I could follow?

**Comment by szy21** [comment]
I think we can close this:) We have a sphere vertical diffusion test now.
