### ISSUE TITLE
Test the implicit solve for GABLS case. 

### ISSUE THREAD

**Issue by trontrytel** [CliMA/ClimaAtmos.jl#1173]
This case is dry and has no updrafts, so it's the simplest we have right now. 
- [x] What is the behaviour and performance for long dt? 
- [x] Double check if this case is deterministic.
- [ ] ~~Optimize performance: Get to the solution with a small number of GMRES iterations.~~ Leaving it for later once we have improved compilation times and agreed on a longer test case. See discussion below

**Comment by dennisYatunin** [comment]
https://buildkite.com/clima/climaatmos-ci/builds/5955

GABLS with IMEX EDMF seems to be the most stable IMEX EDMF configuration we have seen so far. I have increased the timestep all the way to 10000 seconds, and there are still combinations of solver parameters for which the simulation runs to completion (although the solution quality noticeably deteriorates for timesteps in the 1000s of seconds). In addition, this configuration appears to produce deterministic results, and changing the solver parameters does not appear to randomly switch whether or not the simulation crashes. This is also the first configuration in which we have seen a potential speedup from using IMEX EDMF; the simulations with a timestep of 10000 seconds ran in under a second (excluding compilation time), though I will need to run more tests to properly quantify the speedup.

**Comment by trontrytel** [comment]
Following up from @dennisYatunin :
- GABLS is deterministic
- The max dt with explicit turbconv (in this case the tke tendency is fully explicit) is 500-1000, the max dt with with imex grid-mean tendencies and explicit turbconv is ~1000, and the max dt with both imex turbconv and imex grid-mean is > 10000
- It is very difficult to get an estimate of the speedup from JFNK. With the explicit EDMF version running at a 500 second timestep, it takes less than 2 seconds (excluding compilation), and the 10000 second IMEX runs also take less than 2 seconds. We would need a bigger problem and spend less time in compilation to optimize

**Comment by dennisYatunin** [comment]
For reference, here is the buildkite run that gave me this data:
https://buildkite.com/clima/climaatmos-ci/builds/5996

**Comment by trontrytel** [comment]
Closing and moving on to dry cases with updrafts
