### ISSUE TITLE
Implement and test checkpoint-restart functionality

### ISSUE THREAD

**Issue by akshaysridhar** [CliMA/ClimaAtmos.jl#118]
First iteration of callback system has been merged (writes integrator data to JLD2 files) - ClimaCore Fields are accessible from the JLD2 output files and should allow simulations to be re-started via the existing initialisation hooks. Requires implementation, unit tests and validation using existing test cases(e.g. Bickley Jet 2D).

**Comment by jakebolewski** [comment]
This works pretty well (a less portable but faster version for local runs is to just call the built in serialize (`Serialization.serialize`)) machinery, tested it with the bubble test cases.

Any callbacks part of the solver would have to be defined in the env through for round tripping.

**Comment by jakebolewski** [comment]
There is also a tabular interface which we would hook up to fields, see https://diffeq.sciml.ai/stable/features/io/.
