### ISSUE TITLE
Figure out why our tests don't work with Float32

### ISSUE THREAD

**Issue by bischtob** [CliMA/ClimaAtmos.jl#119]
**context**
Some of our integration tests don't pass with Float32.

**ideas**
no idea why, but last time I checked I thought it was a `ClimaCore.jl` issue.

**next steps**
Set up some test and track down which sub-component breaks the Float type.

**Comment by szy21** [comment]
@dennisYatunin Does #141 close this?

**Comment by dennisYatunin** [comment]
Yes, it does.
