### ISSUE TITLE
Unify parameter sets

### ISSUE THREAD

**Issue by charleskawczynski** [CliMA/ClimaAtmos.jl#1199]
We should probably try to unify our clima parameters, which are [switched depending on the configuration](https://github.com/CliMA/ClimaAtmos.jl/blob/2af30f78a78739fed08f5ee3ea7044f18f18f533/examples/hybrid/parameter_set.jl#L8-L15)

This could be fixed in two ways:
 - simply pick a set of parameter values, and see if all experiments work with those values. This may be difficult if some experiments are breaking, but it could require the least code changes since we could technically just delete all the overrides (if all the experiments just worked).
 - we could create 3 toml files with overrides based on the if-else if-else blocks in the link above. Then specify the correct toml override in all of the appropriate buildkite jobs so that there are no behavioral changes. The result is that this function could simply create the parameters with the toml override. This is simple in the sense that we can easily solve this by making no behavioral changes, but it will require carefully figuring out which set of parameters each buildkite job is using. My tip here would be to add a print in the if-elseif-else block and run CI, then collect the information from the log. That would take a lot of guess/investigatory work out

**Comment by nefrathenrici** [comment]
Option 2 requires 100+ CI runs to use toml files. I would rather try to have a unified parameter set, so I will pick one set of parameter values that minimizes MSE / pipeline crashes. If there are runs that really don't work well, we can override them with a minimal toml file.
