### ISSUE TITLE
Undefined variable?

### ISSUE THREAD

**Issue by Yujie-W** [CliMA/ClimaAtmos.jl#1203]
Variable `prof_v` is not defined in method for `GATE_III_*`
https://github.com/CliMA/ClimaAtmos.jl/blob/d0e85d63b6c5bc768881a6bdb2c194b51fab6c86/tc_driver/Cases.jl#L726

Should it be the following as in some other cases without `*_v`?
```julia
set_z!(prog_gm_uₕ, prof_u, x -> FT(0))
```

**Comment by charleskawczynski** [comment]
Yes, it looks like it's zero based on the last working version in TurbulenceConvection.jl, [here](https://github.com/CliMA/TurbulenceConvection.jl/blob/3a22e373744181e682df2614ff712bf862455eb2/driver/Cases.jl#L731-L747), the case was commented out in [this PR](https://github.com/CliMA/TurbulenceConvection.jl/pull/1064), I probably accidentally added a reference to the undefined `prof_v` in a refactoring PR, not realizing that this code was not exercised

**Comment by charleskawczynski** [comment]
This code has been refactored away.
