### ISSUE TITLE
Add `beta` factor to AtmosSimulation cache

### ISSUE THREAD

**Issue by juliasloan25** [CliMA/ClimaAtmos.jl#1214]
SurfaceFluxes and ClimaLSM both now include a beta factor to more realistically represent evaporation (see https://github.com/CliMA/SurfaceFluxes.jl/pull/75 and https://github.com/CliMA/ClimaLSM.jl/pull/124). We want to update the coupler to perform the calculation of the beta factor and store it in the atmos cache (https://github.com/CliMA/ClimaCoupler.jl/issues/199).

To do this, we need an additional field in the atmos cache to store the beta factor (i.e. `atmos_sim.integrator.p.beta`).

**Comment by szy21** [comment]
cc @akshaysridhar. I can take this on while he is on vacation.
