### ISSUE TITLE
Apply dss directly on Fields

### ISSUE THREAD

**Issue by jiahe23** [CliMA/ClimaAtmos.jl#124]
**context**
As suggested by @jakebolewski, directly applying `Spaces.weighted_dss!` on Field is more efficient than applying it separately on variables in the [shallow water](https://github.com/CliMA/ClimaAtmos.jl/blob/e6aed4b8e243939722b01957f3d35b8480384b85/src/Models/ShallowWaterModels/shallow_water_model.jl#L81-L83) and [nonhydrostatic](https://github.com/CliMA/ClimaAtmos.jl/blob/0f8d768e9ecca989740aa842e50fcb278efeadb0/src/Models/Nonhydrostatic2DModels/nonhydrostatic_2d_model.jl#L135-L138) model set-ups . 

**solution**
For hybrid plane, we should first aggregate variables on face and center when initializing the [Fields](https://github.com/CliMA/ClimaAtmos.jl/blob/0f8d768e9ecca989740aa842e50fcb278efeadb0/src/Models/Nonhydrostatic2DModels/nonhydrostatic_2d_model.jl#L33) and perform dss separately for face and center as in [climacore bubble example](https://github.com/CliMA/ClimaCore.jl/blob/1a3c9463d367aa4dede9a11ffd81249ea8fa9017/examples/hybrid/bubble.jl#L223-L224).

**Comment by szy21** [comment]
Reopen it just for discussion. No need to implement it now.

**Comment by bischtob** [comment]
How will this play with the fact that we want the use to think as little as possible about the discretization ?

**Comment by bischtob** [comment]
@jiahe23 is this still relevant?
