### ISSUE TITLE
Redefining function from RRTMGP.jl

### ISSUE THREAD

**Issue by simonbyrne** [CliMA/ClimaAtmos.jl#1246]
This function is
https://github.com/CliMA/ClimaAtmos.jl/blob/b4cd235c30db7e481c6b3b22e5f888abac969025/src/RRTMGPInterface.jl#L1231
is redefining a function in RRTMGP:
https://github.com/CliMA/RRTMGP.jl/blob/66cf373933eddd1fdd0c1c0f70db7a3a654ff397/src/optics/GrayOpticsKernels.jl#L17

Can we do this some other way (e.g. define a new function instead)?

**Comment by szy21** [comment]
@dennisYatunin Do you remember why we need this function to have the same name as the one in RRTMGP?

**Comment by dennisYatunin** [comment]
RRTMGP does not let us pass a custom function for computing the optical properties; it just calls this function. So, if we want to change how it computes the optical properties, we need to redefine this function. I think the simplest solution is to replace the call to `compute_optical_props_kernel!` with a call to a user-specified function, unless there is some GPU-related reason not to do this.

**Comment by szy21** [comment]
> RRTMGP does not let us pass a custom function for computing the optical properties; it just calls this function. So, if we want to change how it computes the optical properties, we need to redefine this function. I think the simplest solution is to replace the call to `compute_optical_props_kernel!` with a call to a user-specified function, unless there is some GPU-related reason not to do this.

@sriharshakandala Do you think this is a possible solution?

**Comment by sriharshakandala** [comment]
Can we add a fuction type/flag/name to `GrayAtmosphericState` so that the optical properties function can call the appropriate function specified by the user

**Comment by sriharshakandala** [comment]
We can try something similar to what was done here! https://github.com/CliMA/ClimaCore.jl/blob/main/examples/sphere/shallow_water.jl#L70

**Comment by dennisYatunin** [comment]
Sure, switching between two OpticalProperties types in the atmospheric state would also be fine. @szy21, what would we call the different options?

**Comment by szy21** [comment]
I hope in the end the user can specify optical properties functions themselves rather than choosing from options. But I don't want to block this so having options now is fine. I don't have great names in mind - maybe call them by the reference, `Schneider2004` and `OGorman2008`?

**Comment by sriharshakandala** [comment]
> I hope in the end the user can specify optical properties functions themselves rather than choosing from options. But I don't want to block this so having options now is fine. I don't have great names in mind - maybe call them by the reference, `Schneider2004` and `OGorman2008`?

Yes. The above option will allow users to add additional functions.
