### ISSUE TITLE
Refactoring Parameter Usage in CA

### ISSUE THREAD

**Issue by nefrathenrici** [CliMA/ClimaAtmos.jl#1259]
This SDI continues the discussion from [SDI#721](https://github.com/CliMA/ClimaAtmos.jl/issues/721).
## Purpose

Currently, ClimaParameters is in a decent initial state as a single source for parameters, but there a few issues. 
1. In ClimaAtmos, there are currently three sources of parameters: ClimaParameters, NameList, and the CLI. This will ideally be reduced to just ClimaParameters. The CLI should just handle configuration for running the model, and should eventually also support a TOML file.
2. A model running a simple simulation should not have to gather all default parameters used in all components.
3. The growing numbers of parameters should not become unwieldy.
4. Parameters and configuration should be clearly logged for reproducibility.

This SDI is meant to further discussion around these issues and propose changes.

## Summary of Proposed Steps

1. Remove [NameList](https://github.com/CliMA/ClimaAtmos.jl/blob/main/tc_driver/generate_namelist.jl) usage, add the parameters to ClimaParameters.
2. Use ArgParse to group common configurations in order to simplify the CI.
3. Add support to store a model configuration in a TOML file, separate from the parameter TOML file.
4. Use a tagging system to ‘tag’ each parameter with the component(s) that it is used in, allowing for only sufficient parameters to be grabbed from ClimaParameters.
5. Continue using parameter structures to read in parameters from the flat ClimaParameters TOML and define derived parameters.
6. Log config and override parameters to the same place.

## NameList

This is the easy part. The NameList dictionary will be phased out and replaced with TOML. [Basic functionality](https://github.com/CliMA/ClimaAtmos.jl/pull/812) to convert NameList dicts to TOML already exists. With this in place, we can add all of the default parameters from NameList into the main `parameters.toml` in ClimaParameters and add a parameter structure to replace them. Supported TOML file types may need to be expanded.

This can act as a pilot/example for any changes we want to make to the ClimaParameters interface, such as the underlying TOML structure.

## Parameter Categorization
Models should not need to load in the whole TOML dictionary for running simple simulations or test cases. Two possible solutions to this:

1. Split the big TOML file into multiple files, at the very least one for each high-level component. This is simple, but it may be difficult to split parameters neatly.

2. Add one or more component tags to each parameter, which will then be used by the component to obtain the necessary parameters. These might have to be quite specific for ClimaAtmos, where the complexity can vary greatly depending on the configuration. This seems to be the cleanest way to categorize parameters.

## Parameter Types

Universal/planet parameters should be separated into their own file or have their own tag to help distribute them consistently to all components.

Derived parameters could be defined using expressions in TOML, but this is likely to be somewhat brittle and inconsistent, since it would require a lot of work switching over and testing. Parameter structures are a good place where derived parameters are already defined in-code, this should be expanded where applicable.

Neural net parameters or other large arrays could be separated out into other files, with the TOML entry containing the relative file path. I’m not familiar with NN parameter usage, so I’m not sure what issues this might cause or what the naming conventions would be.

## CLI

This is the most controversial part, since the CLI is required for the CI, but it seems like it [should be phased out](https://github.com/CliMA/ClimaAtmos.jl/issues/721#issuecomment-1226559829) eventually. I'm not sure how to fully phase the CLI out without creating an unwieldy amount of configuration files -- it seems like some CLI functionality will be useful in any scenario. 

At the very least, here are some options that can be used together or separately to simplify the CLI:

1. Use ArgParse to group arguments that are commonly used together. This can be used to improve the CI pipeline and [existing argument parsing code](https://github.com/CliMA/ClimaAtmos.jl/blob/main/examples/hybrid/driver.jl#L394-L413). For example, all Bomex-related arguments can be grouped into something like `--Bomex` for the Bomex tests. The only real difficulty this poses is with parsing overlapping configurations, but just needs a bit of planning. 

2. Create a [simple configuration file parser](https://github.com/JuliaPackaging/Preferences.jl/) to allow all arguments/options to be passed in via a single TOML config file. This is a bit more flexible than the first option, as it can be used to group arbitrary arguments into a file.

3. If we want to limit the CLI as much as possible:  for a model run, enable the option to format and save all given CLI options to a TOML config file. This way, tests and other use cases can easily be switched to use TOML files for configuration instead of the CLI. Then, CLI arguments can be deprecated and a config file can be created for each CI case. Note that the config files should be totally distinct from any parameter override TOMLs.

**Comment by trontrytel** [comment]
This is great work and a great summary of the work plan. Looking forward to cleaning up the parameter handling on the EDMF side.

**Comment by odunbar** [comment]
### Namelists
Regarding the namelist flattening. We should be aware that automated procedures will produce unwieldy hierarchical names, e.g. `hier_name = component_subcomponent_module_param`. It is important to remember that when reading parameters that we must not depending on the string structure (i.e. reinforcing the hierarchy again). 

The *ideal* format of TOML is to have a descriptive `[name]`, while leaving `param` at the end of `hier_name` in the `alias` field of the TOML, a reminder of the [start we have made here] 
(https://docs.google.com/spreadsheets/d/1T3wXWv0tc6O4YuN-7OxMDtezV61RXcUO6DP-eOCXnUc/edit#gid=0), all parameters in the current ClimaParameters.jl defaults `parameters.toml` follow this naming convention.

e.g. 
```toml
[rain_drop_drag_coefficient]
alias = "C_drag"
value = 0.55
type = "float"
```
likely came from something like `hier_name = atmos_microphysics_C_drag`

### Parameter Categorization
To clarify the purpose here. The "whole TOML" is still small, it is likely O(KB) size and is read a couple of times per simulation, there are no computational reasons to split it. I believe instead, the purpose of the splitting is to (1) allow users a smoother and less error-prone editing experience, (2) to separate concerns

To this end, I think we should not split by component, (which does not separate concerns). Instead I suggest a soft splitting of the `override` (aka `experiment`) TOML file into something like...
1. `configure.toml` - options used during the build stage, e.g. switches describing which parameterizations are used, and other options 
2. `simulation.toml` - numbers describing the simulation to be running, e.g. grid sizes, time limits etc. experiment name etc
3. `nuisance_parameters.toml` - describing taken as fixed-value physics-based parameters, not of interest to the simulation, but not so universal that they are already fixed to this in the defaults file
4. `experiment_parameters.toml` - numbers describing values of interest to the simulation (e.g. a manageable set of parameters the user alters to create an experiment series with)

### Component tags

This is something we proposed before and unfortunately it didn't work. Instead we now have the full list, and the component instead asks for specific (unstructured) parameters. This then adds a tag to the parameter log file e.g. the log file will read
```toml
[rain_drop_drag_coefficient]
used_in = "Microphysics,ClimaAtmos"
alias = "C_drag"
value = 0.55
type = "float"
```
This is described and used in the `ClimaParameters.jl` docs and tests

### ParameterTypes
- Planet parameters are defined in `ClimaParameters.jl` default list already
- We have several examples of using derived parameters in other packages, e.g. [Thermodynamics.jl](https://github.com/CliMA/Thermodynamics.jl/blob/main/src/Parameters.jl)
- Neural net parameters, are storeable as vectors in the `value= [...]` field. We have considered the option of storing them and putting a filepath in the value field instead, these can be dealt with if and when the issue arises.


### CLI 

I have no comment on CLI as of yet, as I don't know enough about the pipeline.

**Comment by tapios** [comment]
@nefrathenrici Thank you for this clean and clear summary. 

Let's talk about CLI options if there continue to be ties. A hybrid option may be to pass in a pointer to a config file as a CL option (close to your option 2).

**Comment by nefrathenrici** [comment]
After today's discussion, I will work out some prototype that uses TOML files for build/numerical parameters with a couple of examples. This will give us something more concrete to examine and improve upon.

**Comment by trontrytel** [comment]
Hi @nefrathenrici . Based on all he discussion and feedback, could you add a list of small issues that need to be done to address the big SDI here? I'm guessing the [PR 103](https://github.com/CliMA/CLIMAParameters.jl/pull/103) works on solving first point from the summary of the proposed steps. But was wondering about the next ones. 

And could we add [this issue](https://github.com/CliMA/Calibratmos.jl/issues/2) to the list of tasks here?

**Comment by nefrathenrici** [comment]
@trontrytel 
Here is a tentative list of issues/PRs:
1. [Add NameList to ClimaParameters](https://github.com/CliMA/CLIMAParameters.jl/pull/103)
2. #1305
3.  #1304
4. [ Provide an example on how to run a single column simulation using a toml file.](https://github.com/CliMA/Calibratmos.jl/issues/2)
