### ISSUE TITLE
Tests in test/runtests.jl yield errors

### ISSUE THREAD

**Issue by sandreza** [CliMA/ClimaAtmos.jl#127]
Currently 30 / 36 tests are passing, but the remaining 6 need to be investigated and fixed. Specifically 3 unit tests and 3 regression tests are failing

**Comment by szy21** [comment]
I just ran the main branch and all 46/46 tests are passing. Have you updated all the packages?

**Comment by sandreza** [comment]
I've updated ClimaCore, but I'll need to do a clean wipe to make sure all the dependencies are in check! Thanks for checking this @szy21! I'll close the issue
