### ISSUE TITLE
clear description of discretized equations in ClimaAtmos development documenation

### ISSUE THREAD

**Issue by bischtob** [CliMA/ClimaAtmos.jl#1276]
- specifically document the choice of order of interpolation (when are we interpolating what)
- address the point of kinetic energy conservation considerations in the documentation

**Comment by trontrytel** [comment]
Can this be closed? @szy21 @bischtob

**Comment by szy21** [comment]
Not quite. I guess this will be done after we are sure topography works, and document the discretized equations we use in the end.

**Comment by szy21** [comment]
superseded by #1846
