### ISSUE TITLE
Test cases on sphere with Earth topography

### ISSUE THREAD

**Issue by bischtob** [CliMA/ClimaAtmos.jl#1282]

**Comment by szy21** [comment]
@akshaysridhar #1202 doesn't close this, right? will there be a PR for this?

**Comment by akshaysridhar** [comment]
@szy21 Yes, there will be a separate PR to introduce the Earth cases into the buildkite setup.

**Comment by akshaysridhar** [comment]
Moist Baroclinic Wave Test Case: Earth Orography with Gaussian Smoothing (Raw -> Lat Long Spline Interpolation) + Laplacian Smoothing (On nodal points, with spectral div/grad operators) 
```
h_elem = 16
n_poly = 3
z_elem = 25
z_stretch = false
kappa_4 = 8e16
alpha_rayleigh_w = 1.0
alpha_rayleigh_uh = 1e-4
use_reference_state = false
t_end = 30days
```

![mbw_basic_day30](https://user-images.githubusercontent.com/43710045/236500010-cd059141-fe6d-4d95-b0c6-147b8808336f.png)
![mbw_moisture_day30](https://user-images.githubusercontent.com/43710045/236500014-7a95e58f-b5d2-47a7-a491-3a5d4e2f66ab.png)
![mbw_velocity_day30](https://user-images.githubusercontent.com/43710045/236500018-2aa254cd-b0d9-41f2-8791-435cc6a68c58.png)

**Comment by akshaysridhar** [comment]
Moist Baroclinic Wave Case Summary: 
| dt  	| kappa_4 	| z_elem 	| z_stretch 	| h_elem 	| n_poly 	| t_end (days) 	| use_ref_state 	| P/F                      	|
|-----	|---------	|--------	|-----------	|--------	|--------	|--------------	|---------------	|--------------------------	|
| 25  	| 8e16    	| 25     	| false     	| 16     	| 3      	| 30           	| false         	| P:day30 (sim end time)   	|
| 35  	| 8e16    	| 25     	| false     	| 16     	| 3      	| 30           	| false         	| P:day30 (sim end time)   	|
| 50  	| 8e16    	| 25     	| false     	| 16     	| 3      	| 30           	| false         	| P:day15 (in progress)    	|
| 100 	| 8e16    	| 45     	| false     	| 16     	| 3      	| 30           	| false         	| F: sat_adjust -> T = NaN 	|
| 100 	| 1e16    	| 45     	| true      	| 16     	| 3      	| 30           	| false         	| F: sat_adjust -> T = NaN 	|

**Comment by akshaysridhar** [comment]
Dry Baroclinic Wave Test Case Summary: 
| dt  	| kappa_4 	| z_elem 	| z_stretch 	| h_elem 	| n_poly 	| t_end (days) 	| use_ref_state 	| P/F                    	|
|-----	|---------	|--------	|-----------	|--------	|--------	|--------------	|---------------	|------------------------	|
| 25  	| 8e16    	| 25     	| false     	| 16     	| 3      	| 30           	| false         	| P:day30 (sim end time) 	|
| 50  	| 8e16    	| 25     	| false     	| 16     	| 3      	| 30           	| false         	| P:day30 (sim end time) 	|
| 75  	| 8e16    	| 25     	| false     	| 16     	| 3      	| 30           	| false         	| P:day10+ (in progress) 	|
| 100 	| 1e16    	| 45     	| false     	| 16     	| 3      	| 30           	| false         	| F: NaN (< day 2)       	|
| 150 	| 1e16    	| 45     	| true      	| 16     	| 3      	| 30           	| false         	| F: NaN (< day 2)       	|

**Comment by akshaysridhar** [comment]
[summary_1_day30.pdf](https://github.com/CliMA/ClimaAtmos.jl/files/11465705/summary_1_day30.pdf)
[summary_10_day30.pdf](https://github.com/CliMA/ClimaAtmos.jl/files/11465707/summary_10_day30.pdf)

**Comment by akshaysridhar** [comment]
Dry HS: Day 400 (simulation end time) 
[day = 400, dt = 300s, kappa = 1e16, Gauss-smoothing = 4, Laplace-smooth = 100R_e, 100 passes]
Level 1 Summary 
[summary_dry_hs_l1_day400_dt300_1e16_smooth4.pdf](https://github.com/CliMA/ClimaAtmos.jl/files/11518453/summary_dry_hs_l1_day400_dt300_1e16_smooth4.pdf)
Level 10 Summary 
[summary_dry_hs_l10_day400_dt300_1e16_smooth4.pdf](https://github.com/CliMA/ClimaAtmos.jl/files/11518455/summary_dry_hs_l10_day400_dt300_1e16_smooth4.pdf)

Equil-Moist HS: Day 125 (simulation end time 400 days, in progress) 
[day = 125, dt = 100s, kappa = 1e16, Gauss-smoothing = 4, Laplace-smooth = 100R_e, 100 passes]
Level 1 Summary 
[summary_emhs_l1_day125_dt100_4e16_smooth5.pdf](https://github.com/CliMA/ClimaAtmos.jl/files/11518492/summary_emhs_l1_day125_dt100_4e16_smooth5.pdf)
Level 10 Summary 
[summary_emhs_l10_day125_dt100_4e16_smooth5.pdf](https://github.com/CliMA/ClimaAtmos.jl/files/11518497/summary_emhs_l10_day125_dt100_4e16_smooth5.pdf)
