### ISSUE TITLE
Improve mass and tracer conservation test with and without topography in ClimaAtmos

### ISSUE THREAD

**Issue by Zhengyu-Huang** [CliMA/ClimaAtmos.jl#1283]

**Comment by tapios** [comment]
It would be best to check conservation (a) with zero fluxes at the boundaries and (b) with non-zero fluxes (e.g., with constant fluxes and a tracer concentration that grows linearly in time). Some conservation problems (from interpolation issues) may only become manifest with non-trivial boundary fluxes.

**Comment by Zhengyu-Huang** [comment]
> It would be best to check conservation (a) with zero fluxes at the boundaries and (b) with non-zero fluxes (e.g., with constant fluxes and a tracer concentration that grows linearly in time). Some conservation problems (from interpolation issues) may only become manifest with non-trivial boundary fluxes.

We have one (a) type conservation test (mass \ energy conservation in the stretched grid) in the ci. Is the test urgent? We plan to let @valeriabarra work on the test, when she is back.

**Comment by tapios** [comment]
That's fine. (I think some of the recent interpolation changes only make a difference for conservation with nonzero boundary fluxes.)

**Comment by szy21** [comment]
Superseded by other issues on conservation.
