### ISSUE TITLE
Research on how to compute u^2 + I(w^2) when there is topography

### ISSUE THREAD

**Issue by Zhengyu-Huang** [CliMA/ClimaAtmos.jl#1285]
We plan to try computing u_ig^{ij}u_j as the following
- compute u_ig^{ij}u_j (i,j=1,2) at cell centers
- compute u_3g^{33}u_3 = I(u_3^2) g^33
- compute u_ig^{i3}u_3 = u_ig^{i3}I(u_3) and u_3g^{3i}u_i = u_3g^{3i}I(u_i)
here I is the interpolation from face to center. This will be done after 2 successes.

**Comment by szy21** [comment]
See Simon's document (on Slack).
