### ISSUE TITLE
Unit-test weighted interpolation operations in ClimaCore

### ISSUE THREAD

**Issue by akshaysridhar** [CliMA/ClimaAtmos.jl#1291]

**Comment by szy21** [comment]
I think we have this now, right?

**Comment by akshaysridhar** [comment]
> I think we have this now, right?

Yes: 
-`https://github.com/CliMA/ClimaCore.jl/blob/10a80f8405cb5064a712fb9625f04717d485e4f4/test/Operators/finitedifference/column.jl#L324`
- `https://github.com/CliMA/ClimaCore.jl/blob/10a80f8405cb5064a712fb9625f04717d485e4f4/test/Operators/finitedifference/column.jl#L273`
