### ISSUE TITLE
Unify the EDMF surface thermo state with the surface representation in ClimaAtmos.

### ISSUE THREAD

**Issue by trontrytel** [CliMA/ClimaAtmos.jl#1296]
Similar to the initialization issue. EDMF creates some surface thermo state and surface parameters based on the SCM cases specified in papers. This should be unified with the surface representation done for the spherical clima atmos configuration.

**Comment by charleskawczynski** [comment]
Just to chime in on some specifics here:
 - `surf_params = Cases.surface_params(case, thermo_params, atmos.moisture_model)` is a struct that's really only useful on a single column (no variables can spatially vary from it).
 - `surf_params` is used during initialization _only_ on a sphere (on a sphere, we have `get_surface` grab the dycore's surface struct, and use that).

So, we should still refactor this, and split apart spatially constant and non-varying data

**Comment by trontrytel** [comment]
vert_diff = true; surface__scheme, set_surface_thermo_state

**Comment by trontrytel** [comment]
`surf_params` are only used in initial conditions

**Comment by trontrytel** [comment]
Linked PR: https://github.com/CliMA/ClimaAtmos.jl/pull/1447
