### ISSUE TITLE
Prototype using a TOML file to pass in model configurations

### ISSUE THREAD

**Issue by nefrathenrici** [CliMA/ClimaAtmos.jl#1304]
## Purpose
This will give us a concrete example to improve upon as we work on refactoring parameter usage.

## People and Personnel
(@ the personnel required/requested to implement the software solution)
- Lead: @nefrathenrici 

## Basic Steps: (Subject to change as I plan more thoroughly)
1. Create TOML file(s) that group arguments commonly used together in the CLI. These won't be pushed to the main branch, but will exist to show off the new functionality in the end.
2. Parse those TOML files via ClimaParameters. (#1340)
3. (Optional) Create TOML files for the case-based hardecoded values in `examples/hybrid/parameter_set.jl`
4. Merge the ClimaParameters dictionary with the parsed_args dictionary in `create_parameters`.
5. Make sure that the new data structure is distributed correctly. This will likely be a slow process, but it can be introduced slowly.

**Comment by tapios** [comment]
LGTM. Looking forward to seeing what you prototype!
