### ISSUE TITLE
Replace NameList with ClimaParameters

### ISSUE THREAD

**Issue by nefrathenrici** [CliMA/ClimaAtmos.jl#1305]
Replace generate_namelist and create a parameter struct for the EDMF parameters. Remove all calls to ``parse_namelist``
Depends on: https://github.com/CliMA/CLIMAParameters.jl/pull/103

**Comment by trontrytel** [comment]
Draft PR: https://github.com/CliMA/ClimaAtmos.jl/pull/1311

**Comment by trontrytel** [comment]
Draft PR: https://github.com/CliMA/ClimaAtmos.jl/pull/1377
