### ISSUE TITLE
Use bubble correction as default

### ISSUE THREAD

**Issue by szy21** [CliMA/ClimaAtmos.jl#1313]
It is not used as default because high resolution moist baroclinic wave breaks when using bubble correction, see this [build](https://buildkite.com/clima/climaatmos-longruns/builds/797#018618d5-0a7d-4950-ac8f-01daabaec737) for example. Here is a plot of vertical velocity at some upper level at day 40, and it seems there is some oscillation.

![image](https://user-images.githubusercontent.com/11598433/216842699-9c7fc4f9-98e0-4490-ae84-46ce787ad888.png)

**Comment by szy21** [comment]
Reopening this for the record. We can investigate it when we have the time.

**Comment by szy21** [comment]
Note: @tapios suggested that we look at shallow water experiments to see if there are similar patterns.

**Comment by bischtob** [comment]
@simonbyrne, any issues with extruded spaces here?

**Comment by charleskawczynski** [comment]
We should probably have an `enable_bubble` test in ClimaCore that uses the same space that ClimaAtmos uses by default, on a sphere.

**Comment by valeriabarra** [comment]
ClimaCore shallow-water simulation with the same target horizontal resolution (`ne = 16`), run for 15 days, **no** bubble:
- animation:
https://user-images.githubusercontent.com/39932030/218188488-37408420-b984-488b-99b0-2f7ccc5671e6.mp4
- final screenshot:
![final_height_ne_16_day_15_no_bubble](https://user-images.githubusercontent.com/39932030/218188723-ea3ed19f-687a-4432-9728-60eb6ed821c4.png)
- Numerical results:
```julia
[ Info: ("Solution L₂ norm at time t = 1296000: ", 10007.370840423204)
[ Info: ("Fluid volume at time t = 1296000: ", 5.101084466643369e18)
```

Same simulation, **with** bubble:
- animation:
https://user-images.githubusercontent.com/39932030/218188815-106dd81a-9592-47ee-a4b5-5d481d1cd076.mp4

- final screenshot:

![final_height_ne_16_day_15_with_bubble](https://user-images.githubusercontent.com/39932030/218188845-e865eddb-a2b3-458d-a4f5-c412e573431a.png)

- Numerical results:
```julia
[ Info: ("Solution L₂ norm at time t = 1296000: ", 10007.37084042841)
[ Info: ("Fluid volume at time t = 1296000: ", 5.101084473414422e18)
```


Volume Errors:
```julia 
julia> day_15_volume_with_bubble = 5.101084473414422e18
5.101084473414422e18

julia> day_15_volume_no_bubble = 5.101084466643369e18
5.101084466643369e18

ulia> rel_error = abs(day_15_volume_with_bubble - day_15_volume_no_bubble)/day_15_volume_no_bubble
1.3273751078377083e-9
```

**Comment by valeriabarra** [comment]
> @simonbyrne, any issues with extruded spaces here?

I think Simon was referring to this [bit](https://github.com/CliMA/ClimaCore.jl/blob/10a80f8405cb5064a712fb9625f04717d485e4f4/src/Spaces/extruded.jl#L314-L327) of code, but we simply multiply the horizontal `J` and `WJ` with the vertical ones. We don't override or recompute them. So there should be no issue there.

**Comment by tapios** [comment]
Can we see a flow that is more dynamically unstable (e.g., Bickley jet) and thus generates smaller flow scales?
