### ISSUE TITLE
High resolution moist baroclinic wave breaks when using bubble correction

### ISSUE THREAD

**Issue by szy21** [CliMA/ClimaAtmos.jl#1315]
See this [build](https://buildkite.com/clima/climaatmos-longruns/builds/797#018618d5-0a7d-4950-ac8f-01daabaec737) for example. @valeriabarra Could you investigate it, or set the default bubble correction back to false before we figure out whether there is a problem?

**Comment by valeriabarra** [comment]
For now we can revert #1314. I can't investigate at the moment

**Comment by szy21** [comment]
That's fine with me, thanks!

**Comment by szy21** [comment]
FYI I made a quick plot of vertical velocity at some upper level at day 40. It seems there is some oscillation, especially near the cubed sphere edge. I don't know if it's relevant to the stability.

![image](https://user-images.githubusercontent.com/11598433/216793825-7cac6599-be99-4c68-9d52-7fa2a7d58657.png)

**Comment by szy21** [comment]
We can follow up in #1313
