### ISSUE TITLE
Move remapping to separate command

### ISSUE THREAD

**Issue by simonbyrne** [CliMA/ClimaAtmos.jl#1317]
The current remapping step in the longrun job is [called as part of the driver](https://github.com/CliMA/ClimaAtmos.jl/blob/ce47d12c88f4455c41f5852317a4094a3dbb8c92/examples/hybrid/driver.jl#L441). Unfortunately this triggers an error:
https://buildkite.com/clima/climaatmos-longruns/builds/759#0185aee3-e22c-4c23-9840-82a749974ca7/140-471
```

HDF5-DIAG: Error detected in HDF5 (1.12.1) thread 0:
  #000: H5F.c line 711 in H5Fclose(): decrementing file ID failed
    major: File accessibility
    minor: Unable to close file
  #001: H5Iint.c line 1018 in H5I_dec_app_ref(): can't decrement ID ref count
    major: Object atom
    minor: Unable to decrement reference count
  #002: H5Iint.c line 949 in H5I_dec_ref(): can't locate ID
    major: Object atom
    minor: Unable to find atom information (already closed?)
```

I'm not quite sure why this is failing: my main hypothesis is that written file isn't completely closed on some MPI processes, so when it is read for remapping it triggers an error.

The easiest solution is to make the remapping a completely separate script, which should be run after the driver (either as part of the current buildkite step, or as a separate step which depends on the model run step (the latter is probably preferable in cases where you are using large CPU resources).

**Comment by simonbyrne** [comment]
Note we already do this in the CI pipeline: https://buildkite.com/clima/climaatmos-ci/builds/6906#01862d35-45e0-43f3-bf55-c328754e8b9e

**Comment by charleskawczynski** [comment]
I'll open a draft PR to get this moving
