### ISSUE TITLE
Revamp inefficient testing pipeline for Atmos tests

### ISSUE THREAD

**Issue by bischtob** [CliMA/ClimaAtmos.jl#1328]
### Purpose
Overhaul of the current CI and Longrun CI to improve physical test coverage and streamline the review process for developers and reviewers.

### Cost/Benefits/Risks
**Costs**: Several developer/scientist days

**Benefits**: Hopefully our ability to catch bugs earlier and with less effort for developers and reviewers. Potentially huge efficiency gains for the team as reviews become smoother. Reduction in review overhead and repeat-reviews.

**Risks**: If this is not done carefully and with good planning, we may lose some of our current test coverage. Since a CI is run with every PR, there is inertia to change, hence we need to make sure we deliver an actual improvement over current CI (-> some planning goes a long way). The plan reflects risk mitigation approaches by first onboarding the proposed changes to ClimaAtmos.jl without disrupting the current review process.

Another risk is disruption of some work streams for the EDMF team. As a result, we should target the dycore and atmos tests only for now.

### People and Personnel
- Lead: @szy21
- Collaborators: @jiahe23, @akshaysridhar 
- Reviewers: @simonbyrne, @bischtob

### Components
**Part 1 (lowish-hanging fruit)**
Removal of unneeded ClimaAtmos.jl tests and porting of relevant atmosphere tests from ClimaCore.jl. This serves to simply have a current and useful list of CI and Longrun CI tests.

**Part 2 (hardest part)**
Unify CI and Longrun CI output formats to HDF5 and solve remapping issue (may require @simonbyrne's input)
After that, we can update metrics for integration tests (conservation checks, distributional checks) that are calculate from HDF5 output. This makes adding utilities for improved static before-and-after graphics (PDF), ideally in a single scrollable report (minimizes number of clicks for reviewers), easy.

**Part 3 (easy)**
Update Buildkite pipelines to provide for the easiest possible (!) review experience (make it easy to copy-paste link to PR).
Update PR review policies to reflect new capabilities

### Inputs
- Current ClimaCore.jl and ClimaAtmos.jl CI and Longrun CI tests.

### Results and deliverables
**Tangible**
- Updated ClimaAtmos.jl driver configurations
- ClimaAtmos.jl metrics for before-after-testing
- New utility scripts that generate plots, PDFs, and MP4s
- Buildkite pipelines
- Updated PR review policy document and PR template

**Intangible**
- A sense of reduced effort in PR reviews and a sense of increased reliability of our CIs.

### Task Breakdown And Tentative Due Date*
- [x] #1354
Budget: 1 day
- [x] #1358
Budget: 1 day - 1 week***
- [x] #1360
Budget: 1 day
- [x] #1382
Budget: 1 day - 1 week**
- [x] #1491
Budget: 1 week
- [x] #1401
Budget: 1 day - 1 week***
- [x] #1402
Budget: 1 day - 1 week***

\* not all items need to be done serially.
** uncertainty stems from unknown unknowns and known unknows about remapping and HDF5 issues in current CI.
*** uncertainty  stems from time to pass code reviews and switch in CI.

### References
[Keeping Science on Keel When Software Moves](https://dl.acm.org/doi/pdf/10.1145/3382037)
[State Check](https://clima.github.io/ClimateMachine.jl/latest/APIs/Diagnostics/StateCheck/)

***
### Metadata
- Proposed by: @bischtob, @szy21 
- Proposal date: Feb 8, 2023
- Approved by: @cmbengue 
- Approval date: Feb 8, 2023

### CC
@tapios, @cmbengue, @simonbyrne

**Comment by bischtob** [comment]
@szy21, @simonbyrne, @akshaysridhar  please add comments

**Comment by bischtob** [comment]
Ideas from earlier conversations:
- Conservation tests
- Spectra
- Distributions
- Simple visualizations for quick inspection and sanity checks
- Ported tests

**Comment by bischtob** [comment]
Candidate ClimaCore tests for porting:
https://github.com/CliMA/ClimaCore.jl/blob/e063e694afd962babe526de98dd8794016242853/.buildkite/pipeline.yml#L368
https://github.com/CliMA/ClimaCore.jl/blob/e063e694afd962babe526de98dd8794016242853/.buildkite/pipeline.yml#L608
https://github.com/CliMA/ClimaCore.jl/blob/e063e694afd962babe526de98dd8794016242853/.buildkite/pipeline.yml#L617

**Comment by szy21** [comment]
Thanks Toby! Here are a few minor comments.

I might change the title to something like "Inefficient post-processing and physical testing".
I would add "remove unnecessary ci tests"  before "Ported ClimaCore.jl integration tests to ClimaAtmos.jl". I think we should be able to get rid of some more current tests, especially if we want to keep the total number of tests manageable. 
I don't think we need MP4 visualization, at least as a first pass. The MP4 are probably hard to be embedded in a pdf, and most of the time they are not as useful as plots.

**Comment by szy21** [comment]
We don't have to do this as a first pass either, but we should add a time-average option for diagnostics.

**Comment by bischtob** [comment]
@szy21 can you double check the task breakdown again?

**Comment by szy21** [comment]
Looks good! I made a minor change (adding remapping before plotting in the task breakdown).

**Comment by bischtob** [comment]
@szy21 , i added budget estimates. please check.

**Comment by cmbengue** [comment]
This is very good, and ready to go when you guys are.

**Comment by akshaysridhar** [comment]
For the item 
```Add remapping, plotting and reporting utility functions to ClimaAtmos.jl utils for postprocessing of HDF5``` 
What is the proposed new component following this plan? Our current post-processing functions have provisions for remapping / plotting (including time averaging), provided the integrator object is accessible. Is the idea to refactor the existing code in the `post_processing` directory to be available as more generic utilities for offline use? (The "reporting" function utilities would certainly be useful w.r.t our online buildkite setup.) 

Is there any scope for repurposing some of the `DiagnosticsMachine` tools that we had ?(I see `StateCheck` mentioned above, so I'm curious if this is part of the plan)

**Comment by szy21** [comment]
The timeline looks good overall, I have some minor suggestions:

`Add HDF5 as output to CI and Longrun CI tests if not already standard` is one command line argument change, so can be done in 1 day
`Add remapping, plotting and reporting utility functions to ClimaAtmos.jl utils for postprocessing of HDF5` will take longer than 1 week I think. How about separating it into `Add remapping that creates netcdf files` which is about 1 day - 1 week (uncertainty from currently it's not working but can potentially be fixed, see #1317) and `Add plotting and reporting utility...` which is another 1 week.

**Comment by szy21** [comment]
> For the item `Add remapping, plotting and reporting utility functions to ClimaAtmos.jl utils for postprocessing of HDF5` What is the proposed new component following this plan? Our current post-processing functions have provisions for remapping / plotting (including time averaging), provided the integrator object is accessible. Is the idea to refactor the existing code in the `post_processing` directory to be available as more generic utilities for offline use? (The "reporting" function utilities would certainly be useful w.r.t our online buildkite setup.)
> 
> Is there any scope for repurposing some of the `DiagnosticsMachine` tools that we had ?(I see `StateCheck` mentioned above, so I'm curious if this is part of the plan)

The idea is to not rely on the integrator object, because it's not realistic for the longrun. We want to move the post-processing pipeline to hdf5 -> netcdf -> plotting.

I'm not familiar with the `DiagnosticsMachine`, but if we already have something working, we should try to adopt it.

**Comment by bischtob** [comment]
Thanks for everyone's input! :)

**Comment by bischtob** [comment]
@trontrytel suggests nightly reports :)_

**Comment by trontrytel** [comment]
This looks great! A couple of (late) comments:
- For EDMF it has worked really well to include the current main branch and the PR branch in the same plot that is shown as artifact in a given builkite job. This is especially useful when combined with some simple regression tests. Then the workflow is: 
(i) regression tests flag the CI cases where PR results are at all different than the stored reference data,  
(ii) the reviewer/developer knows which cases to check, 
(iii) plots with main vs PR branch make it easy to decide if the resulting changes are insignificant, significant and good, or significant and bad. 
The key thing is to make it easy to update the reference data, so that we are not afraid to make changes to the simulation results.
- I really liked when the nightly runs in the old ClimateMachine repo were posting the resulting plots on Slack. This was the easiest way for me to remember to keep paying attention to the long run builds and quickly catch when my simulations break.
- :+1: for some standard plotting pipeline for all our cases.

**Comment by szy21** [comment]
Thanks @trontrytel. I like the plots with main vs PR in particular. I wonder if we could ask you or Charlie for help when we work on it (probably in 1-2 weeks)?

**Comment by trontrytel** [comment]
> Thanks @trontrytel. I like the plots with main vs PR in particular. I wonder if we could ask you or Charlie for help when we work on it (probably in 1-2 weeks)?

I was thinking of switching our plotting setup from Plots.jl to CairoMakie.jl (Plots with Plots.jl are a little finicky). If we were to do a cleanup in our plotting pipeline is should be easy to extend to other CI runs. Not sure about the timing of it though - before or after some dry implicit edmf runs?

**Comment by bischtob** [comment]
We can do CairoMakie.jl, I think :).

**Comment by akshaysridhar** [comment]
Can we use `YAML.jl` to produce an automated buildkite summary of sorts ? Something we could perhaps store and verify in `docs` at a glance? MWE with the basic functionality from YAML.jl looks something like this for a specific case identified:  
```
julia> data = YAML.load_file(".buildkite/pipeline.yml"; dicttype = OrderedDict{String,Any})
julia> for ii = 1:length(data["steps"][5]["steps"][:])
           @info data["steps"][5]["steps"][:][ii]["label"];
       end
[ Info: :computer: single column hydrostatic balance float64
[ Info: :computer: single column radiative equilibrium gray
[ Info: :computer: single column radiative equilibrium clearsky
[ Info: :computer: single column radiative equilibrium allsky idealized clouds varying insolation
[ Info: :computer: single column non-orographic gravity wave parameterization
```  i.e. here perhaps we just filter "groups" or "labels" ; given `data` is tied to the existing version of buildkite, this should auto-update each time we add/remove a `label`

**Comment by bischtob** [comment]
YAML.jl

**Comment by bischtob** [comment]
Moving the last outstanding issue to SDI #1383. Closing this SDI.
