### ISSUE TITLE
IMEX splitting of vertical divergence

### ISSUE THREAD

**Issue by simonbyrne** [CliMA/ClimaAtmos.jl#1338]
In #1286 we moved all the vertical divergence terms into the implicit part. After discussion with @paullric, we should probably handle the horizontal velocity contribution in the explicit part. This gets a bit complicated with upwinding, as the upwinding direction should be determined by the combined velocity (i.e. the sign of the contravariant3 component of the reconstructed velocity), but only multiplied by the velocity contribution horizontal or vertical components. We will need https://github.com/CliMA/ClimaCore.jl/issues/1125

This only will make a difference with topography (since otherwise the horizontal contribution to the vertical divergence is 0)

**Comment by bischtob** [comment]
This MAY cause suboptimal time step size or other instabilities, BUT we do not quite know what the impact of this modification would be.

**Comment by szy21** [comment]
@simonbyrne what's the status of this?

**Comment by simonbyrne** [comment]
I think with the changes proposed in #2510 this would no longer be needed.
