### ISSUE TITLE
Add support for `SSP333` time stepper

### ISSUE THREAD

**Issue by valeriabarra** [CliMA/ClimaAtmos.jl#1341]
Benefits:
The new SSP time stepper, including its integration with limiters, will be tested in ClimaAtmos.

Risks:
Lack of simpler, incremental examples in the upstream repo. There is not currently a working spherical 3D simple example that uses the new SSP algorithm yet in ClimaTimeSteppers (only a 2D one), and there are no examples with multiple tracers (that we'd need to account for in ClimaAtmos). 
Documentation of the new interfaces is lacking and scattered.

**Comment by valeriabarra** [comment]
Working branch: [`valeria/test-SSP333`](https://github.com/CliMA/ClimaAtmos.jl/tree/valeria/test-SSP333)

**Comment by bischtob** [comment]
Note: still fixing bug on simulation crashes with q_tot = 1.

**Comment by bischtob** [comment]
@valeriabarra, Is SSP-IMEX without limiters working for dry Held-Suarez? Double check with Gardner paper (might still work with 1 Newton iteration) who mentions multiple Newton iterations are required.

**Comment by bischtob** [comment]
aka check first without limiters then with limiters

**Comment by valeriabarra** [comment]
- Regular top (30k m) dry HS simulation without limiters and using default ARS 343 time-stepper (see this [build](https://buildkite.com/clima/climaatmos-ci/builds/7320#_)): 
     - T plot: 
![hs--no-lim-ARS-T](https://user-images.githubusercontent.com/39932030/219823272-a5c31fd1-1447-4722-ad20-9995fac2ace3.png)

     - T^2 plot:
![hs--no-lim-ARS-T2](https://user-images.githubusercontent.com/39932030/219823302-4ee8ff90-5868-415a-b194-c507faf5e4cf.png)

- High top (45k m) dry HS simulation without limiters and using default ARS 343 time-stepper (see this [build](https://buildkite.com/clima/climaatmos-ci/builds/7320#_)): 
     - T plot: 
![high-top-hs--no-lim-ARS-T](https://user-images.githubusercontent.com/39932030/219823346-776e38de-ef0a-4d29-a440-b0af148b4cb0.png)

     - T^2 plot:
![high-top-hs--no-lim-ARS-T2](https://user-images.githubusercontent.com/39932030/219823355-965b34b1-31be-41b4-a955-6ea6b77550d3.png)

- Regular top (30k m) dry HS simulation without limiters, with SSP333 time-stepper (see this [build](https://buildkite.com/clima/climaatmos-ci/builds/7326#_) -- these dry HS tests are marked as failures in the build because the regression mse tables are changed): 
     - T plot: 
![hs--no-lim-SSP-T](https://user-images.githubusercontent.com/39932030/219823417-8971ab58-1a2c-4709-be8c-8940ee6e62ba.png)

     - T^2 plot:
![hs--no-lim-SSP-T2](https://user-images.githubusercontent.com/39932030/219823452-cf6d93da-b2a4-4d50-960d-a265a06cb2a6.png)


- High top (45k m) dry HS simulation without limiters, with SSP333 time-stepper (see this [build](https://buildkite.com/clima/climaatmos-ci/builds/7320#_)): 
     - T plot: 
![high-top-hs--no-lim-ARS-T](https://user-images.githubusercontent.com/39932030/219823495-7335de06-73ed-4167-9dcf-9ad55dec57d0.png)

     - T^2 plot:
![high-top-hs--no-lim-SST-T2](https://user-images.githubusercontent.com/39932030/219823507-6421af6e-be1d-4643-8a2b-9aa35cb9da08.png)
