### ISSUE TITLE
Setup box kinetic energy conservation tests in ClimaAtmos

### ISSUE THREAD

**Issue by Zhengyu-Huang** [CliMA/ClimaAtmos.jl#1347]

**Comment by trontrytel** [comment]
Can we close this one?

As a side note, we have added a kinematic test case for EDMFX in ClimaAtmos proper: https://github.com/CliMA/ClimaAtmos.jl/pull/1614. It basically zeroes out the momentum tendency for EDMFX and drives everything with whatever we have in initial condition.
