### ISSUE TITLE
Correctly set vertical velocity at cell boundaries

### ISSUE THREAD

**Issue by szy21** [CliMA/ClimaAtmos.jl#1367]
Find a way to set $u_v$ at cell boundaries so that $\tilde{u}^v = 0$. Can fake it for now, but should add a boundary condition to ClimaCore that handles this.

**Comment by simonbyrne** [comment]
It's a little bit convoluted, but we want to set $u_v$ at the boundaries so that $\tilde{u}^v = 0$.
