### ISSUE TITLE
Build radiation module

### ISSUE THREAD

**Issue by bischtob** [CliMA/ClimaAtmos.jl#137]
**context**
We need to add a radiation module to ClimaAtmos that allow us to build column models with radiation forcing. We also need the corresponding basic validation tests.

**next steps**
Define here the simplest case of what we need. Currently we are missing minimal specs for how this functions within the ClimaCore/ClimaAtmos API. I'd like to see a minimal example here that we can iterate on as APIs change, etc.

**Comment by szy21** [comment]
Just chatted with @dennisYatunin. Radiation doesn't use ClimaCore. We will talk about what would be the best way to integrate it into ClimaAtmos.
