### ISSUE TITLE
Exceeding allocation limits in threaded performance checks

### ISSUE THREAD

**Issue by akshaysridhar** [CliMA/ClimaAtmos.jl#1414]
`bors` staging builds have been failing with varying threaded performance allocation counts:

1. Manual trigger (branch commit): https://buildkite.com/clima/climaatmos-ci/builds/7695#0186a486-ed56-4d63-b4d4-9bb2d8d299fd (Success)

```
[ Info: Allocation change (allocs/allocs_limit): 0.9998989133181704
```

2. Successful (main merge): https://buildkite.com/clima/climaatmos-ci/builds/7700#0186a500-be4a-4b5b-b13b-1f721ad281be (Success)

```
[ Info: Allocation change (allocs/allocs_limit): 0.999631755659049
```
3. Staging-1: https://buildkite.com/clima/climaatmos-ci/builds/7696#0186a487-e161-4b8b-9f83-7951b1db2322 (Failure)
```
[ Info: Allocation change (allocs/allocs_limit): 1.0000649842954619
```
4. Staging-2: https://buildkite.com/clima/climaatmos-ci/builds/7698#0186a4e9-d163-4be1-8e59-405d94062592 (Failure) 
```
[ Info: Allocation change (allocs/allocs_limit): 1.0000072204772736
```

Curious if this is a known issue - what should we expect or check beyond, for instance the link listed in (1) i.e. a manual verification of the "default" buildkite outcomes following a new commit?

**Comment by charleskawczynski** [comment]
Is the issue here that the allocations are larger than expected, or that they're non-deterministic?

**Comment by akshaysridhar** [comment]
> 

The non-determinism seems to be the issue here (mostly the differences between original commits and staging builds, which causes CI failures); re-trying this eventually leads to a successful outcome e.g. 
`[ Info: Allocation change (allocs/allocs_limit): 0.999631755659049`. 
The differences between the staging / manual commit tags above are of O(1e-5)- O(1e-6). Maybe we could apply a safety-margin with respect to the `allocs_limit` if this variation is expected.
