### ISSUE TITLE
Implement physics closures in EDMFX

### ISSUE THREAD

**Issue by trontrytel** [CliMA/ClimaAtmos.jl#1421]
A rough list of what we need:
 - [x] entrainment/detrainment
 - [x] non-hydrostatic pressure
 - [x] buoyancy
 - [x] subdomain buoyancy exchange term
 - [x] shear
 - [x] saturated/unsaturated gradients
 - [x] buoyancy gradients
 - [x] mixing length
 - [ ] microphysics

**Comment by charleskawczynski** [comment]
K-loops have been removed

**Comment by szy21** [comment]
Closing this as the only missing term is microphysics, which is tracked by other issues.
