### ISSUE TITLE
Test changes to pressure gradients.

### ISSUE THREAD

**Issue by trontrytel** [CliMA/ClimaAtmos.jl#1423]

**Comment by trontrytel** [comment]
Here is what is currently happening in the EDMF code in ClimaAtmos:

We compute the `nh_pressure` as described in He et al paper draft eq. (34) in the current overleaf document. Note that `P = p/rho_h` in the paper draft. So the `nh_pressure = d/dz(p/rho_h)`. `rho_h` stands for the reference density that is in balance with the hydrostatic pressure.

```
If = InterpolateC2F
Ic = InterpolateF2C
∇ = DivergenceC2F

nh_pressure = 
     -α_b * If(b_up) +                                                  
      α_a * wcomponent(CCG.WVector(w_up)) * ∇(Ic(CCG.WVector(w_up))) -   
      α_d * (wcomponent(CCG.WVector(w_up - w_en))) * abs(wcomponent(CCG.WVector(w_up - w_en))) / H_up  
```

The coupling to the momentum and TKE equations in He et al is written in equations (23), (25) and (26) in the flux form.

In the code we are solving the momentum equation in the advective form and the TKE equation in the flux form. Be mindful that changing the momentum equation from flux to advective is what "broke" our deep convective TRMM case (see [this PR](https://github.com/CliMA/ClimaAtmos.jl/pull/918/files)). 

The `nh_pressure` is then applied to momentum tendency:

```
tends_w +=                                                           
    w_up * If(entr) * (wcomponent(CCG.WVector(w_en - w_up))) +       
    CCG.Covariant3Vector(CCG.WVector(If(buoy) + nh_pressure))
```

and to TKE tendency:

```
tke_press +=                                                         
    (Ic(wcomponent(CCG.WVector(w_en - w_up)))) * prog_up[i].ρarea * Ic(nh_press)     
```

The questions:
- I never understood the `w_up * If(entr) * (wcomponent(CCG.WVector(w_en - w_up)))` term. See the discussion [here](https://github.com/CliMA/ClimaAtmos.jl/pull/918#discussion_r990856799). Could we double check that this is correct in the advective form?
- What part of the He et al derivations depend on `P` being defined as `p/rho_h`? Can we try using the same formulae as proposed there and just try re-tuning the `α_b`, `α_a` and `α_d`?

**Comment by jiahe23** [comment]
I don't see a reason why the form is changed from flux form equations to advective form equations.

It is the Boussinesq approximation that assigns P being defined as p/rho_h and solves the Poisson equation.

**Comment by tapios** [comment]
Just to be clear: this not the pressure gradient term I was talking about. The term parameterized in Jia's paper is 'd' in my notation. Nothing needs to be changed here. (Going from flux to advective form only changes by division by 'a rho'.)

**Comment by trontrytel** [comment]
Closing this issue. We currently use the anelastic approximation:

![image](https://user-images.githubusercontent.com/1196696/225673932-f3e815e0-0bb0-420a-b34a-45ededd69f6e.png)

Those terms will not be removed in the EDMFex implementation. See momentum equation in EDMF equations here: https://github.com/CliMA/ClimaAtmos.jl/pull/1443
