### ISSUE TITLE
Test SSP IMEX without limiter, with 1 Newton iteration and for different timestep

### ISSUE THREAD

**Issue by szy21** [CliMA/ClimaAtmos.jl#1440]
- Tests in order of complexity: dry baroclinic wave, moist baroclinic wave, moist held suarez, aquaplanet with clearsky radiation
- Specific command line arguments: `--max_newton_iters 1 --ode_algo SSP333 --apply_limiter false`
- Timestep: Start with the default ARS343 `--dt`, and decrease until it is stable.
- Test if it is stable and produces physically correct results. If so, compare time to solution with the default ARS343 timestepper

**Comment by jiahe23** [comment]
amip targeted resolution with limiter applied:

dry bw runs thru 10 days
```
mpiexec julia --project=examples examples/hybrid/driver.jl --z_elem 45 --dz_bottom 30 --h_elem 16 --kappa_4 1e16 --dt 300secs --max_newton_iters 1 --t_end 10days --dt_save_to_disk 10days --job_id longrun_ssp1_bw_rhoe_dry_highres --ode_algo SSP333
```


moist bw crashes within 10 days
```
mpiexec julia --project=examples examples/hybrid/driver.jl --moist equil --precip_model 0M --z_elem 45 --dz_bottom 30 --h_elem 16 --kappa_4 1e16 --dt 300secs --max_newton_iters 1 --t_end 10days --dt_save_to_disk 10days --job_id longrun_ssp1_bw_rhoe_equil_highres --ode_algo SSP333
```

**Comment by jiahe23** [comment]
without limiter low resolution set up

n_elem = 6, np = 3, z_max = 30e3, z_elem = 10, dt = 580 secs

dry/moist bw can run with newton iteration = 1 for 10 days

vorticity at day 10 is
![vort](https://user-images.githubusercontent.com/47290257/225709231-1398aefa-04f9-445c-bea0-b47797ea0e6f.png)

**Comment by jiahe23** [comment]
without limiter targeted resolution set up

n_elem = 16, np = 3, z_max = 45e3, z_elem = 50, dt = 300 secs

newton_iteration=1,  dry bw crashes after day 7; moist after day 6

dry/moist bw can run with newton iteration = 2 for 10 days

vorticity at day 10 is
![vort (1)](https://user-images.githubusercontent.com/47290257/225712162-953e167a-0af8-4c06-8813-c5b6287c26b5.png)

**Comment by jiahe23** [comment]
A test with reduced dt=100 showed success in dry/moist bw can run with newton iteration = 1 for 10 days (dt=150 cashes)

![vort (2)](https://user-images.githubusercontent.com/47290257/225758246-1145b865-dc39-4f92-b0c8-7dcf9a14fe7c.png)

**Comment by jiahe23** [comment]
I believe we can conclude that iter=1 doesn't work.
