### ISSUE TITLE
Moist simulation with limiter still contains negative qt

### ISSUE THREAD

**Issue by jiahe23** [CliMA/ClimaAtmos.jl#1490]
The [moist held suarez](https://buildkite.com/clima/climaatmos-longruns/builds/855#01870b71-19ec-4629-a183-ad7d42457e2c) simulation has negative qt. It was set up with the limiter on, SSP 2 iterations, dt = 75 in longrun buildkite. 

```
julia> println(qt |> parent |> extrema)
(-0.0008108849f0, 0.021829993f0)
```

Here are the plots of qt signs (orange for +1 and blue for -1) at level 13 equivalent to z = 1033 m on both the raw cg grid and the remapped lat/lon grid. 

![cg_13](https://user-images.githubusercontent.com/47290257/227387436-aaf9e22c-05fe-48a2-9572-b3368536b041.png)
![latlon_13](https://user-images.githubusercontent.com/47290257/227387442-0d6d70e0-a372-4fa3-a430-414242232725.png)

**Comment by jiahe23** [comment]
negative qt also observed in moist baroclinic wave

**Comment by jiahe23** [comment]
I did a test by increasing precipitation timescale by 10X, i.e., reducing the qt source due to precipitation by 10X.; and still observe negative qt on the order of 10e-4.

**Comment by valeriabarra** [comment]
I don't know if we're expecting machine-precision zero, but I think this might depend on the accuracy of the solver. 

I tested the longrun moist HS test case for `--max_newton_iters 3` and `dt=100secs` and the `qt` values are better (still negative, but better). These are the CLI options I used:

```
mpiexec julia --project=examples examples/hybrid/driver.jl --forcing held_suarez --moist equil --vert_diff true --surface_scheme bulk --precip_model 0M --z_elem 45 --dz_bottom 30 --h_elem 16 --kappa_4 1e16 --dt 100secs --max_newton_iters 3 --t_end 400days --dt_save_to_disk 10days --job_id longrun_ssp_hs_rhoe_equil_highres --ode_algo SSP333
```

(from this [build](https://buildkite.com/clima/climaatmos-longruns/builds/863#01872548-b673-4c7a-8d8a-298e311113fe)), 

here are the `qt` extrema:

```
println(qt |> parent |> extrema)
(-1.0461779f-6, 0.02176966f0)
```

and here are the artifacts produced (removing the 200-days spinup): 

- sigma Vs mean `u`:
![mean_u_sigma](https://user-images.githubusercontent.com/39932030/228675927-1e73763d-0215-45bc-8b29-b22b80f309fb.png)

- sigma Vs mean `qt`:


![mean_qt_sigma](https://user-images.githubusercontent.com/39932030/228676061-af5b2cbb-2d7b-475f-839c-faaa27e815e3.png)


- height Vs  mean `qt`:
![mean_qt](https://user-images.githubusercontent.com/39932030/228676142-db77f308-afb6-4c5b-9a86-d79626945248.png)

**Comment by valeriabarra** [comment]
> Do you know the differences in time-to-solution comparing (iter=2, dt=75secs) vs (iter=3, dt=100secs) and how long could this setup (iter=3, dt=100secs) survive?

What was the time-to-solution for your run with (max_newton_iter=2, dt=75secs)? For this run I used the default longrun configuration, which runs until 400 days (`--t_end 400days`) and it ran to completion. I can test another run for even longer. 

This one took 32 hours to complete, so that makes 0.82 SYPD

**Comment by szy21** [comment]
Actually, I just realized we should expect negative qt if we are using central difference for qt?

**Comment by trontrytel** [comment]
Lets close this one then. The testing for advection schemes that should play well with limiters is done here: https://github.com/CliMA/ClimaAtmos.jl/issues/1503 and https://github.com/CliMA/ClimaAtmos.jl/issues/1513

**Comment by valeriabarra** [comment]
I can confirm that these tests run all the way for 800 days (`--t_end 800days`)
