### ISSUE TITLE
Investigate grid imprinting

### ISSUE THREAD

**Issue by trontrytel** [CliMA/ClimaAtmos.jl#1514]
See results on the moist baroclinic wave shown here: https://github.com/CliMA/ClimaAtmos.jl/issues/1313

Looks like we still have grid imprinting on main. Not sure if its an issue or a feature. See if you want to track it or close it @szy21

**Comment by szy21** [comment]
Thanks. The oscillation looks small, but I’m not sure whether it is an issue. I’ll ask Tapio about it. Let’s keep this open for now.

**Comment by szy21** [comment]
Tapio agreed that the oscillation is small, but suggested that we try increasing hyperdiffusion or decreasing dt. I don't think this is high priority so we don't have to do this now, but we can leave this open.
