### ISSUE TITLE
`zalesak` upwinding on tracers & energy fails

### ISSUE THREAD

**Issue by valeriabarra** [CliMA/ClimaAtmos.jl#1562]
This is part of the investigation in #1310

**Comment by valeriabarra** [comment]
After the recent fixes: 
- fix in the implicit tendency BC specification, #1612 (and its simplified interface, #1617) 
- fix in the vertical Jacobian for zalesak, #1577 
- and the logic fix in the ClimaCore Zalesak operator, [#1219](https://github.com/CliMA/ClimaCore.jl/pull/1219), 

we can have the coarse/regular CI resolution moist BW example, with Zalesak FCT applied to both tracers and energy, with the following CLI options:

 ```
 julia --project=examples examples/hybrid/driver.jl --initial_condition MoistBaroclinicWave --moist equil --precip_model 0M --job_id sphere_zalesak_upwind_tracer_energy_ssp_baroclinic_wave_rhoe_equilmoist --dt 100secs --max_newton_iters 3 --dt_save_to_disk 5days --t_end 10days --ode_algo SSP333 --tracer_upwinding zalesak --energy_upwinding zalesak
 ```
 
 producing the following plots:
 
 At day 10: 
 
 - `u`, level 1:
![u_day10_level1](https://user-images.githubusercontent.com/39932030/236957351-a3c66d27-adda-4ed4-9ea2-e3cb960a0b0e.png)


- `v`, level 1:
![v_day10_level1](https://user-images.githubusercontent.com/39932030/236957373-128fe3ed-738b-4a2b-9af2-a9e175514c56.png)

- `ρq_tot`, level 1:
![rho_q_tot_day10_level1](https://user-images.githubusercontent.com/39932030/236957560-868fde2a-1824-4596-8903-a112e6c74294.png)

The bad news is that with such a small `dt`, this is unfeasible to add to our CI pipeline because it takes way too long (about 1h and 30m to run for only 5 days, with `--t_end 5days`)

**Comment by valeriabarra** [comment]
@szy21 , how do these results look to you?

**Comment by szy21** [comment]
The results look fine to me. Do you have vertical velocity as well? The extreme of negative qt seems a bit large, but I don't know what to expect.

I'm just a bit worried about the fact that we need to reduce dt significantly for zalesak.

**Comment by valeriabarra** [comment]
These are the mean plots:

- `qt` Vs sigma:
![mean_qt_sigma](https://github.com/CliMA/ClimaAtmos.jl/assets/39932030/e059ad86-d17c-4a14-8a84-785964a7c118)


- `qt` Vs height:
![mean_qt](https://github.com/CliMA/ClimaAtmos.jl/assets/39932030/6c95e2ea-495f-4b86-b8c4-e393f19091f6)

**Comment by szy21** [comment]
Thanks, they look fine to me.

**Comment by valeriabarra** [comment]
Thanks! 
Do you think we can close the issue (since the issue was about the failure)?

**Comment by szy21** [comment]
I think we can close the issue if we know the targeted resolution in the longrun works, even with a much smaller dt. You can test only the moist baroclinic wave case, maybe shorten t_end (e.g. to 30 days?) to get a more reasonable turnaround time.

**Comment by valeriabarra** [comment]
> I think we can close the issue if we know the targeted resolution in the longrun works, even with a much smaller dt. You can test only the moist baroclinic wave case, maybe shorten t_end (e.g. to 30 days?) to get a more reasonable turnaround time.

Oh ok, sure. I thought this Issue was only about the coarse resolution investigation and that there would be separate ones for the high-res longruns (as I had done previously for the first-order upwining). That's ok!

**Comment by Zhengyu-Huang** [comment]
I think the dt is too small.  Do you have extrema for upwind3 or central schemes?  I only found the extrema for upwind1 (-1.3867047f-7, 0.019974397f0). If the extrema are not improved, we should not use Zalesak scheme.

**Comment by valeriabarra** [comment]
> I think the dt is too small. Do you have extrema for upwind3 or central schemes? I only found the extrema for upwind1 (-1.3867047f-7, 0.019974397f0). If the extrema are not improved, we should not use Zalesak scheme (I cannot find bugs in the Zalesak).

The ones you reported are from this [comment](https://github.com/CliMA/ClimaAtmos.jl/issues/1536#issuecomment-1500510155) on the longrun moist aquaplanet simulation. Whereas, for first-order upwinding longrun moist baroclinic wave simulation, you can find it in this other [comment](https://github.com/CliMA/ClimaAtmos.jl/pull/1588#issuecomment-1516920879). For third-order longrun moist baroclinic wave, you can please find it in this [comment](https://github.com/CliMA/ClimaAtmos.jl/pull/1588#issuecomment-1542639558) in the PR where we merged the longrun CI jobs.

**Comment by valeriabarra** [comment]
@Zhengyu-Huang , for central diff, longrun high-resolution moist baroclinic wave it is:

```
println(qt |> parent |> extrema)
(-2.1559521f-5, 0.015704077f0)
```

**Comment by Zhengyu-Huang** [comment]
Thanks for the great work! Based on these extrema results, we have
first order upwind                    (-1.3867047f-7, 0.019974397f0)                                
central diff                                (-2.1559521f-5, 0.015704077f0)          
third order upwind                   (-4.8600927f-5, 0.0163151f0)        
Zalesak                                     (-2.2098837f-5, 0.017645685f0)

Zalesak is only slightly better than third order upwind, and the extrema result is similar with central diff.  
I think in future we should use central diff (largest dt), if the negative qt causes issues, we can use first order upwind.

**Comment by valeriabarra** [comment]
I found a configuration that works and allows us to use a larger dt (`dt=350secs`)! 
I had to increase newton iterations to `--max_newton_iters 4`, but it still runs in a reasonable amount of time that we can add it to our CI (about 55mins). 

```
julia --project=examples examples/hybrid/driver.jl --initial_condition MoistBaroclinicWave --moist equil --precip_model 0M --job_id sphere_zalesak_upwind_tracer_energy_ssp_baroclinic_wave_rhoe_equilmoist --dt 350secs --max_newton_iters 4 --dt_save_to_disk 5days --t_end 10days --ode_algo SSP333 --tracer_upwinding zalesak --energy_upwinding zalesak
```

These are the produced plots, at day 10:

- `u`, level 1:
![u_day10_level1](https://github.com/CliMA/ClimaAtmos.jl/assets/39932030/101ad9aa-0a5f-49c2-9c93-04a67ef4a1f9)

- `v`, level 1:
![v_day10_level1](https://github.com/CliMA/ClimaAtmos.jl/assets/39932030/6bff6bd0-9ac2-42c8-b108-49af1b1c3992)

- `w`, level 1+half:
![w_day10_level1](https://github.com/CliMA/ClimaAtmos.jl/assets/39932030/60e9dfd9-aa10-492d-b136-f0a11c8aae54)

- `ρq_tot`, level 1:
![rho_q_tot_day10_level1](https://github.com/CliMA/ClimaAtmos.jl/assets/39932030/9e3e89af-bc75-40de-b56a-3ae08e84c013)

- passive tracer, level 1: 
![pass_tracer_day10_level1](https://github.com/CliMA/ClimaAtmos.jl/assets/39932030/bd61cb5f-0968-4198-ac0a-878d72fc543b)

- passive tracer, level 10: 
![pass_tracer_day10_level10](https://github.com/CliMA/ClimaAtmos.jl/assets/39932030/627d8de5-1e79-4e2b-8229-449fdfa2d581)

For this simulation, the mean value extrema for `qt` are:
```
println(qt |> parent |> extrema)
(-6.2526547f-6, 0.017534055f0)
```

**Comment by valeriabarra** [comment]
@szy21 , @Zhengyu-Huang , I think we can close this issue now :) 
I'll add the jobs to CI as per #1579

**Comment by valeriabarra** [comment]
Here is moist Held-Suarez results for our regular CI pipeline. 

CLI options used:
```
julia --project=examples examples/hybdrid/driver.jl --z_max 45e3 --z_elem 25 --dz_bottom 300 --vert_diff true --surface_scheme bulk --moist equil --forcing held_suarez --precip_model 0M --rayleigh_sponge true --alpha_rayleigh_uh 0 --viscous_sponge true --zd_rayleigh 30e3 --zd_viscous 30e3 --job_id sphere_ssp_zalesak_tracer_energy_upwind_held_suarez_rhoe_equilmoist_hightop_sponge --dt 100secs --max_newton_iters 4 --t_end 10days --dt_save_to_disk 5days --ode_algo SSP333 --tracer_upwinding zalesak --energy_upwinding zalesak
```

These are the produced plots, at day 10:
- `u`, level 1:
![u_day10_level1](https://github.com/CliMA/ClimaAtmos.jl/assets/39932030/af99f22d-3adc-4e2d-9d9c-5c432cd677b4)

- `v`, level 1:
![v_day10_level1](https://github.com/CliMA/ClimaAtmos.jl/assets/39932030/afb75a79-7e5a-4753-85ae-8b4afc862a1a)

- `w`, level 1+half:
![w_day10_level1](https://github.com/CliMA/ClimaAtmos.jl/assets/39932030/94e0f80d-c132-4e3e-ac28-7cf2511c92c9)

- `ρq_t
![rho_q_tot_day10_level1](https://github.com/CliMA/ClimaAtmos.jl/assets/39932030/bb453e00-48e3-478d-bf3c-22251a691dcd)
ot`, level 1:

For this simulation, the mean value extrema for `qt` are:
```
println(qt |> parent |> extrema)
(-0.00019842283f0, 0.013695388f0)
```

---------------------------------------------------------------
The longruns are working and running in the longrun pipeline (see this [build](https://buildkite.com/clima/climaatmos-longruns/builds/960)), and the individual jobs: 
- target resolution [MBW](https://buildkite.com/clima/climaatmos-longruns/builds/960#0188263a-561b-4c63-89cd-55b0779f0df3)
- target resolution [MHS](https://buildkite.com/clima/climaatmos-longruns/builds/960#0188263a-561e-4c4c-ab00-5dd4b1211d5a)
- target resolution [aquaplanet](https://buildkite.com/clima/climaatmos-longruns/builds/960#01882a8b-1db0-490e-b3de-66fa867d4dda)

**Comment by valeriabarra** [comment]
I think we can close this issue now after the recent fixes
