### ISSUE TITLE
ARS Vs SSP: Compare time to solution for dry BW using Gardner resolution

### ISSUE THREAD

**Issue by valeriabarra** [CliMA/ClimaAtmos.jl#1573]
We want to compare the time to solution of the ARS and SSP time-steppers for the dry BW test case, using the resolution from Gardner's paper: `--z_elem 30 --h_elem 20`

This was just requested. I'll track it as part of #1310

**Comment by valeriabarra** [comment]
In this [build](https://buildkite.com/clima/climaatmos-longruns/builds/926) we see that for the resolution in Gardner, i.e.,  `--z_elem 30 --h_elem 20`:

- [ARS343 with `dt=350secs`](https://buildkite.com/clima/climaatmos-longruns/builds/926#0187960e-828c-4691-8e16-96d7efa7b35a) took 3h and 30m to complete 100 days of simulation, which is equivalent to **1.87SYPD**, and produced the following plots
![ARS343_dbw_day100](https://user-images.githubusercontent.com/39932030/232937280-aeb055b2-9e4c-41f4-85d4-654fc37b9bbd.png)

- [SSP333 with `dt=350secs` and `max_newton_iters=3`](https://buildkite.com/clima/climaatmos-longruns/builds/926#0187960e-8296-4772-9bdc-02c84b40db6a) took 3h and 47m to complete 100 days of simulation, which is equivalent to **1.73SYPD**, and produced the following plots
![SSP333_dbw_day100](https://user-images.githubusercontent.com/39932030/232937510-4313aa10-259b-404d-8ec6-d40c725865ab.png)

--------------------------------
We can conclude that for the dry BW test case with the Garnder resolution, SSP333 is only **7% slower** than ARS343

**Comment by tapios** [comment]
Great! That's reassuring. ARS here is with 1 Newton iteration?

**Comment by valeriabarra** [comment]
> Great! That's reassuring. ARS here is with 1 Newton iteration?

Yes.
