### ISSUE TITLE
Add `zalesak` upwinding on tracers and energy in CI pipeline

### ISSUE THREAD

**Issue by valeriabarra** [CliMA/ClimaAtmos.jl#1579]
Now that the fix in the vertical transport Jacobian (PR #1577) has been merged, we can add the `zalesak` tests on tracers in the CI pipeline.

**Comment by bischtob** [comment]
Ideas: 
Discontinuous weighting parameter may cause an issue
Check if vertical resolution matters
Jacobian has a bug (unlikely)
Use simpler upwinding and move on

**Comment by valeriabarra** [comment]
Closed by #1672
