### ISSUE TITLE
Plot spectrum of topography

### ISSUE THREAD

**Issue by szy21** [CliMA/ClimaAtmos.jl#1589]
@akshaysridhar Please add details here, thanks!

**Comment by akshaysridhar** [comment]
<img width="600" alt="ETOPO1_Raw_surface_elevation" src="https://user-images.githubusercontent.com/43710045/234936890-65ac584a-fa85-4493-8e6c-c5660a0f5e27.png">

**Comment by akshaysridhar** [comment]
<img width="500" alt="HR_Earth_Spectra_Comparison" src="https://user-images.githubusercontent.com/43710045/235184737-ee0d27ee-0084-4c6b-9cc5-82a1736de515.png">
