### ISSUE TITLE
Make ClimaAtmos GPU-compatible

### ISSUE THREAD

**Issue by charleskawczynski** [CliMA/ClimaAtmos.jl#1597]
There are several GPU-incompatible pieces in ClimaAtmos. For example,
 - [gravity wave parameterization](https://github.com/CliMA/ClimaAtmos.jl/blob/6d95d2ce38a3b580db497442be0606e47d5fffd1/src/parameterizations/gravity_wave_drag/orographic_gravity_wave.jl#L119-L122)
 - [gravity wave parameterization](https://github.com/CliMA/ClimaAtmos.jl/blob/6d95d2ce38a3b580db497442be0606e47d5fffd1/src/parameterizations/gravity_wave_drag/orographic_gravity_wave.jl#L158-L159)
 - [gravity wave parameterization](https://github.com/CliMA/ClimaAtmos.jl/blob/6d95d2ce38a3b580db497442be0606e47d5fffd1/src/parameterizations/gravity_wave_drag/orographic_gravity_wave.jl#L224)
 - [gravity wave parameterization](https://github.com/CliMA/ClimaAtmos.jl/blob/6d95d2ce38a3b580db497442be0606e47d5fffd1/src/parameterizations/gravity_wave_drag/orographic_gravity_wave.jl#L240-L244)
 - [gravity wave parameterization](https://github.com/CliMA/ClimaAtmos.jl/blob/6d95d2ce38a3b580db497442be0606e47d5fffd1/src/parameterizations/gravity_wave_drag/orographic_gravity_wave.jl#L270-L273)
 - [gravity wave parameterization](https://github.com/CliMA/ClimaAtmos.jl/blob/6d95d2ce38a3b580db497442be0606e47d5fffd1/src/parameterizations/gravity_wave_drag/orographic_gravity_wave.jl#L337)
 - [gravity wave parameterization](https://github.com/CliMA/ClimaAtmos.jl/blob/6d95d2ce38a3b580db497442be0606e47d5fffd1/src/parameterizations/gravity_wave_drag/orographic_gravity_wave.jl#L440-L445)
 - [gravity wave parameterization](https://github.com/CliMA/ClimaAtmos.jl/blob/6d95d2ce38a3b580db497442be0606e47d5fffd1/src/parameterizations/gravity_wave_drag/non_orographic_gravity_wave.jl#L157-L184)
 - [gravity wave parameterization](https://github.com/CliMA/ClimaAtmos.jl/blob/6d95d2ce38a3b580db497442be0606e47d5fffd1/src/parameterizations/gravity_wave_drag/non_orographic_gravity_wave.jl#L195-L232)
 - [gravity wave parameterization](https://github.com/CliMA/ClimaAtmos.jl/blob/6d95d2ce38a3b580db497442be0606e47d5fffd1/src/parameterizations/gravity_wave_drag/non_orographic_gravity_wave.jl#L260-L379)

Many of these issues revolve around the use of `parent`, which exposes ClimaCore internals and bypasses all of the ClimaCore-specific implementation around
 - GPU support
 - proper handling of axis tensor / metric transformations
 - proper handling of cell face and cell center indexing for ExtrudedFiniteDifference spaces

**Comment by szy21** [comment]
Superseded by #1980
