### ISSUE TITLE
Test EDMFX in kinematic advection case

### ISSUE THREAD

**Issue by trontrytel** [CliMA/ClimaAtmos.jl#1600]
The kinematic test case: 
- use box setup
- set momentum tendency to be zero for the grid-mean and EDMFX (We want to keep this test case for a while in ClimaAtmos, so lets add it properly)
- use constant velocity to test our advection especially at the updraft edge (top and bottom)

Different things to test:
- [ ] different updraft area fraction profiles going from very smooth to more steep
- [x] upwinding 1st and 3rd, center, others?
- [x] positive and negative velocities
- [x] without/with moisture
- [ ] stretched vs non-stretched
- [ ] box vs sphere

Notes from meeting on May 3rd:
 - [x] Test for smoother initial conditions. We want to check if oscillations in updraft area fraction are reduced with smoother initial condition.
 - [ ] Try upwinding everywhere in SGS (also summoning @Zhengyu-Huang to weigh in on this)
 - [ ] Change the weighs in regularization of precomputed quantities such that we tend to grid-mean properties when area goes to zero faster.
 - [ ] Test also for not constant initial potential temperature profile
 - [ ] Test on the sphere with horizontal advection

Tests to be done later:
 - [ ] explicit vs implicit time stepping (good test case for the volume term and implicit handling of updraft edges) -> Once we have implicit solver for EDMFX
 - [ ] with/without limiters -> If we ever decide we need limiters in the vertical for SGS scheme

**Comment by jiahe23** [comment]
Let's reopen this issue and keep track of all the test results here.

**Comment by jiahe23** [comment]
![3](https://user-images.githubusercontent.com/47290257/235786586-1a0b9903-77ca-4ef3-a4f5-bd2473c1b8f9.png)


Choice of upwinding does not make any differences.

**Comment by szy21** [comment]
With moisture:
![image](https://user-images.githubusercontent.com/11598433/235813117-baeccaeb-ff86-48cf-8dba-85de9cdf1c16.png)

**Comment by szy21** [comment]
Smooth initial condition, a_half = 1e-3
![final_profiles](https://user-images.githubusercontent.com/11598433/236344546-50bfce97-6175-4fb7-b3c4-4dbce74deb06.png)

**Comment by szy21** [comment]
dry, upwind rhoa
![final_profiles](https://user-images.githubusercontent.com/11598433/236344697-d66bcfcd-5a49-46a0-ab67-ac4c0261402a.png)

**Comment by szy21** [comment]
(just for fun, without the pressure work term)
![final_profiles](https://user-images.githubusercontent.com/11598433/236351127-1c5acf12-d332-499b-92b3-69e96df00e3d.png)

**Comment by szy21** [comment]
negative w
![image](https://user-images.githubusercontent.com/11598433/236355891-985e051d-15a9-41e8-82ff-2be3d80b1efd.png)

**Comment by szy21** [comment]
2D advection in x-z plane. The plot is area fracion.
![image](https://user-images.githubusercontent.com/11598433/236902172-c78708d5-b977-49ce-975b-e62da0606fac.png)

**Comment by szy21** [comment]
This is a bit outdated so I'm closing it. The most important thing left is horizontal advection and limiter I think. We can reevaluate it after the dycore is done.
