### ISSUE TITLE
Verify cached values and operations in precomputed quantity block

### ISSUE THREAD

**Issue by akshaysridhar** [CliMA/ClimaAtmos.jl#1631]
Tracks behaviour changes introduced from modified order of operations in `implicit_tendency.jl` file.  
 - [x] Verify behaviour with operator configurations before and after #1617. 
 - [x] Verify cached value of surface contravariant3 velocity.

**Comment by akshaysridhar** [comment]
Running 
```
julia -i --color=yes --project=examples examples/hybrid/driver.jl --config plane --x_max 240000.0 --z_max 25000.0 --x_elem 80 --z_elem 90 --dt 1.5secs --t_end 14400.0secs --z_stretch false --vert_diff false --kappa_4 1e6 --dt_save_to_disk 3600secs --initial_condition AgnesiHProfile --topography Agnesi --rayleigh_sponge true --alpha_rayleigh_uh 0.0 --alpha_rayleigh_w 0.1 --job_id plane_agnesi_mountain_test_uniform_advdiv_op --use_reference_state false
```
(1) Post (1617) : `advdiv` finite difference operator application 
```
julia> Fields.level(p.ᶠu³, half).components.data.:1 |> extrema 
(-2.2737368f-13, 1.1368684f-13)
```

**_WIP_**

**Comment by szy21** [comment]
If `ᶠu³` is almost zero, why would `ᶜdivᵥ` and `ᶜadvdivᵥ` give different results?

**Comment by akshaysridhar** [comment]
In 
 ```
 @. ∂ᶜρcₜ∂ᶠw =
        -(ᶜadvdivᵥ_stencil(ᶠwinterp(ᶜJ, ᶜρ) * one(ᶠw) * ᶠinterp(ᶜρc / ᶜρ)))
 ```
is the value of the argument assumed to be `ᶜadvdivᵥ_stencil(ᶠwinterp(ᶜJ, ᶜρ) * one(ᶠw) * ᶠinterp(ᶜρc / ᶜρ))` at the `half` index? If so does this explain the behaviour change? Since `one(ᶠw)[1/2]` is not necessarily consistent with the diagnosed value of `ᶠw[1/2]`, which is applied in 
```
@. ᶜρχₜ = -(ᶜadvdivᵥ(ᶠwinterp(ᶜJ, ᶜρ) * ᶠu³ * ᶠinterp(ᶜχ)))
```
 to enforce `u \cdot n = 0`.

**Comment by szy21** [comment]
I think this has been addressed. Could we close this?
