### ISSUE TITLE
a bug in energy equation

### ISSUE THREAD

**Issue by jiahe23** [CliMA/ClimaAtmos.jl#164]
pressure work to the energy tendency is missing [here](https://github.com/CliMA/ClimaAtmos.jl/blob/main/src/Models/Nonhydrostatic3DModels/nonhydrostatic_3d_model.jl#L181-L184).

See https://github.com/CliMA/ClimaCore.jl/pull/411

**Comment by bischtob** [comment]
:slam

**Comment by bischtob** [comment]
Can you fix this in your PR #163 ?
