### ISSUE TITLE
Clean up examples folder and driver file

### ISSUE THREAD

**Issue by bischtob** [CliMA/ClimaAtmos.jl#1664]
Items:
- [ ] Remove the `hybrid` folder
- [ ] Move helper routines for drivers into a `utils.jl`
- [ ] Refactor `driver.jl` into a readable driver our validation experiments

**Comment by charleskawczynski** [comment]
I think this last bullet point really involves fixing #1199. Once that's fixed, the driver (up until solve) can probably be written in a few lines

**Comment by trontrytel** [comment]
> I think this last bullet point really involves fixing #1199. Once that's fixed, the driver (up until solve) can probably be written in a few lines.
> 
> Maybe this is related to the edmf and parameter handling efforts, though (cc @trontrytel, @nefrathenrici )

Thanks to @nefrathenrici we have an example in the CI where a simulation is using parameters from a toml file. Does it mean we want to switch from CI arguments to toml files now?

As far as overwriting parameters:
- All configurations set the precipitation relaxation timescale to model `dt`. That's something we would prolly like to keep.
- Aside from that, the old EDMF only overwrites one more parameter and EDMFX is too young to want to overwrite anything. It's mostly the baro wave setup that relies on parameter overwrites. Not sure how many of those are actually needed
