### ISSUE TITLE
Test SSP332

### ISSUE THREAD

**Issue by valeriabarra** [CliMA/ClimaAtmos.jl#1691]
It was just recommended to use SSP332 rather than SSP333. 

- Test this in the coarse-resolution regular CI pipeline, hopefully with only 1 newton iteration
- Test this in the high-resolution longrun CI pipeline

**Comment by valeriabarra** [comment]
- Regular CI pipeline resolution, moist Baroclinic Wave, stable at day 10, `qt` extrema calculated on mean values over all times, level 1 plots:

| Time-stepper  |   upwinding mode    | limiters    | `dt` | `max_newton_iters`      | `qt` extrema   |  `u` plot        |  `v` plot        |  `w` plot        | `ρqt` plot |
|:--------------------:|:-----------------------------:|:-------------:|:-----:|:---------------------------------:|:-------------------|:---------------:|:---------------:|:---------------:|:---------------:|
| ARS                   |   central                      |     off     | 450s | 1      | (-0.00043375918f0, 0.019891012f0)  |![u_day10_level1](https://github.com/CliMA/ClimaAtmos.jl/assets/39932030/c16a02cb-8375-492c-bd11-b58ea62f3741) |![v_day10_level1](https://github.com/CliMA/ClimaAtmos.jl/assets/39932030/eadb4993-166a-4736-83b2-198791ffd395) |![w_day10_level1](https://github.com/CliMA/ClimaAtmos.jl/assets/39932030/4c77fbff-e132-4162-bfd8-1faed6d69630)|![rho_q_tot_day10_level1](https://github.com/CliMA/ClimaAtmos.jl/assets/39932030/5453f21e-b437-4a1f-b50d-2011fc9e9ff4)|
| SSP333             |   central                      |     on     | 450s | 1      | (-9.2196177f-7, 0.01980693f0) |![u_day10_level1](https://github.com/CliMA/ClimaAtmos.jl/assets/39932030/86720c7a-d987-4d35-b5fa-82fefb772bde)|![v_day10_level1](https://github.com/CliMA/ClimaAtmos.jl/assets/39932030/fca553c5-2017-4e07-91a1-7af79faed0ed)|![w_day10_level1](https://github.com/CliMA/ClimaAtmos.jl/assets/39932030/9c5e4ddd-4a2f-48db-bd26-ed7a08abc666) |![rho_q_tot_day10_level1](https://github.com/CliMA/ClimaAtmos.jl/assets/39932030/1f5d218f-2b1b-4899-bbb1-4f3d7f704c4f)|
| SSP332             |   central                      |     on     | 425s | 1      |(-5.800464f-6, 0.017954363f0) |![u_day10_level1](https://github.com/CliMA/ClimaAtmos.jl/assets/39932030/348278fb-f700-4422-94fc-ea503e6893e7)|![v_day10_level1](https://github.com/CliMA/ClimaAtmos.jl/assets/39932030/e41ca508-74f6-4245-bae3-234c11ab8369)|![w_day10_level1](https://github.com/CliMA/ClimaAtmos.jl/assets/39932030/4762d069-151b-46ed-9590-e8009c0700cb)|![rho_q_tot_day10_level1](https://github.com/CliMA/ClimaAtmos.jl/assets/39932030/8447b05e-75e2-4c72-86e4-3d6f17a1d791) |
| SSP333             |   1st-order                      |     on     | 450s | 1      |(-8.480579f-6, 0.01789666f0)|![u_day10_level1](https://github.com/CliMA/ClimaAtmos.jl/assets/39932030/15235404-7925-4da7-bdb4-695f755c3855)|![v_day10_level1](https://github.com/CliMA/ClimaAtmos.jl/assets/39932030/413f39ff-5cd6-4143-9268-425faf1c0144)|![w_day10_level1](https://github.com/CliMA/ClimaAtmos.jl/assets/39932030/8483dd93-31e6-4c13-a265-a97e2f7f7dcb)|![rho_q_tot_day10_level1](https://github.com/CliMA/ClimaAtmos.jl/assets/39932030/283c73a8-216c-4a07-9659-d5d8ca07a87b)|
| SSP332             |   1st-order                      |     on     | 300s | 1      |(-6.883974f-6, 0.017994002f0) |![u_day10_level1](https://github.com/CliMA/ClimaAtmos.jl/assets/39932030/b08e9db8-7d00-47d2-a7dc-dfe7e0c3f9cc)|![v_day10_level1](https://github.com/CliMA/ClimaAtmos.jl/assets/39932030/51ffdd07-395c-4ca4-8b23-42185b40296d)|![w_day10_level1](https://github.com/CliMA/ClimaAtmos.jl/assets/39932030/7951b2c9-f288-4222-9bb4-ae05dd86ef47)|![rho_q_tot_day10_level1](https://github.com/CliMA/ClimaAtmos.jl/assets/39932030/8c4b8522-35f6-4c6f-9a14-be4dde3ea764)|
| SSP333             |   3rd-order                      |     on     | 450s | 1      |(-5.9881604f-6, 0.017960856f0) |![u_day10_level1](https://github.com/CliMA/ClimaAtmos.jl/assets/39932030/1e251c12-ac7d-472e-9a63-a15cc795127a)|![v_day10_level1](https://github.com/CliMA/ClimaAtmos.jl/assets/39932030/c078cec9-e078-4c36-940c-bac9783e6433)|![w_day10_level1](https://github.com/CliMA/ClimaAtmos.jl/assets/39932030/3a5c2bb3-97aa-4d19-b387-4701a617aea9)|![rho_q_tot_day10_level1](https://github.com/CliMA/ClimaAtmos.jl/assets/39932030/3cf226e2-0f09-4b98-b4a8-90f809c9e8b4)|
| SSP332             |   3rd-order                      |     on     | 425s | 1      |(-6.9621074f-6, 0.017973091f0)|![u_day10_level1](https://github.com/CliMA/ClimaAtmos.jl/assets/39932030/b5a9368e-10a4-41f3-9660-a18e65db5d59)|![v_day10_level1](https://github.com/CliMA/ClimaAtmos.jl/assets/39932030/9fc0580d-e622-480d-ad4b-69fbfcfb7bd7)|![w_day10_level1](https://github.com/CliMA/ClimaAtmos.jl/assets/39932030/2e60f48b-d0fc-479e-ac95-b58409c0a633)|![rho_q_tot_day10_level1](https://github.com/CliMA/ClimaAtmos.jl/assets/39932030/f1511456-2c4f-4c22-93d3-c81089e48765)|
| SSP333             |   zalesak                     |     on     | 600s | 4      |(-5.674892f-6, 0.017938389f0) |![u_day10_level1](https://github.com/CliMA/ClimaAtmos.jl/assets/39932030/6be072db-5077-422e-a490-3fe53396f5ea)|![v_day10_level1](https://github.com/CliMA/ClimaAtmos.jl/assets/39932030/8e7e4abf-5f28-4b9c-aa84-26f94ef0e11b)|![w_day10_level1](https://github.com/CliMA/ClimaAtmos.jl/assets/39932030/5faa74b7-2c65-4c3c-ad0a-4c8d20340c7b)|![rho_q_tot_day10_level1](https://github.com/CliMA/ClimaAtmos.jl/assets/39932030/a2f7895c-cbd3-4f3a-a7fb-db444dfa903c)|
| SSP332             |   zalesak                      |     on     | 600s | 4      |(-8.207306f-6, 0.017245814f0)|![u_day10_level1](https://github.com/CliMA/ClimaAtmos.jl/assets/39932030/f156b67d-a7a5-44a6-ac29-ac3324a03178)|![v_day10_level1](https://github.com/CliMA/ClimaAtmos.jl/assets/39932030/dce77fdc-e8d6-4478-8846-c46b8c655df7)|![w_day10_level1](https://github.com/CliMA/ClimaAtmos.jl/assets/39932030/e8d96962-f57a-4ff7-add8-731d075ab621)|![rho_q_tot_day10_level1](https://github.com/CliMA/ClimaAtmos.jl/assets/39932030/c2f8f7de-36a4-4da5-8813-ade8fe27f84f)|

- Regular CI pipeline resolution, moist Held-Suarez, stable at day 10, `qt` extrema calculated on mean values over all times, level 1 plots:

| Time-stepper  |   upwinding mode    | limiters    | `dt` | `max_newton_iters`      | `qt` extrema   |  `u` plot        |  `v` plot        |  `w` plot        | `ρqt` plot |
|:--------------------:|:-----------------------------:|:-------------:|:-----:|:---------------------------------:|:-------------------|:---------------:|:---------------:|:---------------:|:---------------:|
| ARS                   |   central                      |     off     | 450s | 1      |   |![u_day10_level1](https://github.com/CliMA/ClimaAtmos.jl/assets/39932030/e6a44c12-4e2e-4480-8972-0596f4866d8f)|![v_day10_level1](https://github.com/CliMA/ClimaAtmos.jl/assets/39932030/98a19049-b66c-490e-bbc4-7e649ff1057a)|![w_day10_level1](https://github.com/CliMA/ClimaAtmos.jl/assets/39932030/1404aae2-6c02-4ca7-9249-4f5735652b2e)|![rho_q_tot_day10_level1](https://github.com/CliMA/ClimaAtmos.jl/assets/39932030/f0a5f079-e8db-483d-8dd6-31d560f37659)|
| SSP333             |   central                      |     on     |   | 1      |  | | | | |
| SSP332             |   central                      |     on     | 450s | 1      |(-0.0004418393f0, 0.013593912f0)|![u_day10_level1](https://github.com/CliMA/ClimaAtmos.jl/assets/39932030/c167ca29-53d5-4a48-a88c-b68c7e5dabe1)|![v_day10_level1](https://github.com/CliMA/ClimaAtmos.jl/assets/39932030/8314aab3-510d-4d6a-8ed4-1576fd0ccc3b)|![w_day10_level1](https://github.com/CliMA/ClimaAtmos.jl/assets/39932030/56e66477-cf7c-4c1e-8309-400a817ac99c)|![rho_q_tot_day10_level1](https://github.com/CliMA/ClimaAtmos.jl/assets/39932030/642600fe-41d4-4a6f-af82-fbac0162cb92)|
| SSP333             |   1st-order                     |     on     |  | 1      |  | | | | |
| SSP332             |   1st-order                     |     on     | 75s | 1      |(-0.00025083055f0, 0.013649414f0)|![u_day10_level1](https://github.com/CliMA/ClimaAtmos.jl/assets/39932030/1f624109-fcd3-45e7-aa8e-2855ab0c16d3)|![v_day10_level1](https://github.com/CliMA/ClimaAtmos.jl/assets/39932030/e8a365aa-f952-49b0-b0be-60dccc4d0f10)|![w_day10_level1](https://github.com/CliMA/ClimaAtmos.jl/assets/39932030/68b9fe55-e2af-4b5f-a334-677f76ddfba4)|![rho_q_tot_day10_level1](https://github.com/CliMA/ClimaAtmos.jl/assets/39932030/66f78bf4-6199-4114-94c6-a885adcbbd1a)|
| SSP333             |   3rd-order                      |     on     |  | 1      |  | | | | |
| SSP332             |   3rd-order                      |     on     | 100s | 1      | (-0.000268682f0, 0.013651341f0)|![u_day10_level1](https://github.com/CliMA/ClimaAtmos.jl/assets/39932030/11f2f7b0-f278-453a-bce4-fa26c0c91af8)|![v_day10_level1](https://github.com/CliMA/ClimaAtmos.jl/assets/39932030/1d48e7d0-1a93-4704-af75-a9391dd2aeb8)|![w_day10_level1](https://github.com/CliMA/ClimaAtmos.jl/assets/39932030/d7c89f03-897e-49ad-81fa-2816501c2164)|![rho_q_tot_day10_level1](https://github.com/CliMA/ClimaAtmos.jl/assets/39932030/ec472add-907f-48bd-a590-f87de38d6c36)|
| SSP333             |   zalesak                     |     on     | 100s | 4      |(-0.00019842283f0, 0.013695388f0)|![u_day10_level1](https://github.com/CliMA/ClimaAtmos.jl/assets/39932030/0bfa1240-0a82-45bc-9357-712d435b68a9)|![v_day10_level1](https://github.com/CliMA/ClimaAtmos.jl/assets/39932030/aec6197f-9ecc-4f53-9ef8-369350adaae9)|![w_day10_level1](https://github.com/CliMA/ClimaAtmos.jl/assets/39932030/912f85d8-8a39-4603-8524-dade1135f57f)|![rho_q_tot_day10_level1](https://github.com/CliMA/ClimaAtmos.jl/assets/39932030/c6e31a39-9d5f-4a06-b386-631bc474837c)|
| SSP332             |   zalesak                     |     on     | 100s | 4      |(-0.00016930311f0, 0.013731889f0)|![u_day10_level1](https://github.com/CliMA/ClimaAtmos.jl/assets/39932030/6a516797-853c-46a4-9b62-4bc3957a2188)|![v_day10_level1](https://github.com/CliMA/ClimaAtmos.jl/assets/39932030/923af40a-0a53-412e-bfc2-e0b2b5b36f95)|![w_day10_level1](https://github.com/CliMA/ClimaAtmos.jl/assets/39932030/31f1bc72-fa4b-49a3-a37a-4730dc960143)|![rho_q_tot_day10_level1](https://github.com/CliMA/ClimaAtmos.jl/assets/39932030/21c8b7b8-049b-4c10-89fe-3f1398194f60)|

**Comment by bischtob** [comment]
cc. @tapios, @szy21

**Comment by szy21** [comment]
Thanks Valeria. Could you make a table for the longrun ci as well, just using the simulations you already run?

**Comment by valeriabarra** [comment]
> Thanks Valeria. Could you make a table for the longrun ci as well, just using the simulations you already run?

For some of the modes (i.e., Zalesak) the stable targeted resolution configuration was not found yet. I am running some jobs

**Comment by szy21** [comment]
> > Thanks Valeria. Could you make a table for the longrun ci as well, just using the simulations you already run?
> 
> For some of the modes (i.e., Zalesak) the stable targeted resolution configuration was not found yet. I am running some jobs

That's ok, maybe just post the table with what you have now, and add the new ones once you have them?

**Comment by valeriabarra** [comment]
> > > Thanks Valeria. Could you make a table for the longrun ci as well, just using the simulations you already run?
> > 
> > 
> > For some of the modes (i.e., Zalesak) the stable targeted resolution configuration was not found yet. I am running some jobs
> 
> That's ok, maybe just post the table with what you have now, and add the new ones once you have them?

The ones that I had found to be stable for 1st- and 3rd-order upwinding and that were already merged in the `main` longruns pipeline (see this [build](https://buildkite.com/clima/climaatmos-longruns/builds/951) from May 5th), now are not stable anymore after the recent changes in ClimaAtmos. So I will have to test/experiment again to find all those stable configurations and it will take time. I will post them when ready

**Comment by szy21** [comment]
Ok, thanks. The timestep of some SSP experiments was decreased in #1660, and those experiments should work now. (This PR was merged after 10pm last Friday, so was not included in the latest build.) I don't know what happened to the 3rd-order upwinding experiments.

**Comment by tapios** [comment]
It looks like the problem here is primarily moist HS, which is a very artificial and strange test case with a violent initial instability that can be a challenge for timestepping. 

I suggest you focus on 
* Moist baroclinic wave, including at higher resolution 
* Aquaplanet, including at higher resolution.

**Comment by valeriabarra** [comment]
Here are the results from our longrun targeted resolution (`h_elem 16`, `z_elem 45`) pipeline that I mentioned I was already running during the meeting last Friday and that are stable at **day 100**. 

 `qt` extrema are calculated on mean values over all times: 

- Moist Baroclinic Wave: 

| Time-stepper  |   upwinding mode    | limiters    | `dt` | `max_newton_iters` | `qt` extrema   |  velocity diagnostics | moisture diagnostics | other diagnostics | 
|:--------------------:|:-----------------------------:|:-------------:|:-----:|:---------------------------------:|:-------------------|:---------------:|:---------------:|:---------------:|
| ARS  |   central    | off    | 350s | 1      | (-6.3224106f-5, 0.01765201f0)|![mbw_velocity_day100](https://github.com/CliMA/ClimaAtmos.jl/assets/39932030/b2ca3002-aed7-4514-850e-8922f364d9ec)|![mbw_moisture_day100](https://github.com/CliMA/ClimaAtmos.jl/assets/39932030/c4ea9e80-8925-497b-851b-5453d07b9d2e)|![mbw_basic_day100](https://github.com/CliMA/ClimaAtmos.jl/assets/39932030/fbf621fd-7d70-4ea5-9acb-483b42609411)|
| SSP333 |   central    | on    | 200s | 3      | (-2.111756f-5, 0.01569733f0)|![mbw_velocity_day100](https://github.com/CliMA/ClimaAtmos.jl/assets/39932030/78e54fde-ffe5-40c6-9433-c1857d5310d3)|![mbw_moisture_day100](https://github.com/CliMA/ClimaAtmos.jl/assets/39932030/92e3fe1f-6b5a-450a-9f8d-76cabe9cb6ec)|![mbw_basic_day100](https://github.com/CliMA/ClimaAtmos.jl/assets/39932030/10e9473f-bd20-42e0-8e5a-aa8aa1443d8a)|
| SSP332 |   central    | on    |  |      | ||||
| SSP333 |   1st-order    | on    | 200s | 3      | (1.4569591f-6, 0.013885102f0)|![mbw_velocity_day100](https://github.com/CliMA/ClimaAtmos.jl/assets/39932030/cc17c63c-bdc5-468d-9920-aeb9ef94f12b)|![mbw_moisture_day100](https://github.com/CliMA/ClimaAtmos.jl/assets/39932030/17af21ff-e6fe-410e-baa4-fdbb46f91e6b)|![mbw_basic_day100](https://github.com/CliMA/ClimaAtmos.jl/assets/39932030/703fe73b-a745-4cfe-a6cc-f5d60de66912)|
| SSP332 |   1st-order    | on    | 150s | 3      | (1.731877f-6, 0.0125709055f0)|![mbw_velocity_day100](https://github.com/CliMA/ClimaAtmos.jl/assets/39932030/5cca3a9e-88f7-49e5-b27d-f177613d4be6)|![mbw_moisture_day100](https://github.com/CliMA/ClimaAtmos.jl/assets/39932030/af6966ed-2a8d-4e20-bdc7-c67927ea0dd4)|![mbw_basic_day100](https://github.com/CliMA/ClimaAtmos.jl/assets/39932030/36263564-6788-438b-9902-5f09183b4614)|
| SSP333 |   3rd-order    | on    | 150s | 3      |(-4.086812f-5, 0.016181435f0)|![mbw_velocity_day100](https://github.com/CliMA/ClimaAtmos.jl/assets/39932030/6d0d9f59-1f73-4d44-bc19-176baeed2fb3)|![mbw_moisture_day100](https://github.com/CliMA/ClimaAtmos.jl/assets/39932030/5a5b2ad1-bede-495d-b7e7-0265a194cda9)|![mbw_basic_day100](https://github.com/CliMA/ClimaAtmos.jl/assets/39932030/da82d9c6-5c2d-4a26-bedc-4bd395e67416)|
| SSP332 |   3rd-order    | on    | 150s | 3      | (-4.69705f-5, 0.016308514f0)|![mbw_velocity_day100](https://github.com/CliMA/ClimaAtmos.jl/assets/39932030/39bbecf1-1079-4e45-a758-ebff3b4c0c8b)|![mbw_moisture_day100](https://github.com/CliMA/ClimaAtmos.jl/assets/39932030/02d9eabf-937d-4c12-8d84-e509e2035a58)|![mbw_basic_day100](https://github.com/CliMA/ClimaAtmos.jl/assets/39932030/f98a4bba-496a-4daf-8ab6-30341f3fdd38)|
| SSP333 |   zalesak    | on    |  |       ||
| SSP332 |   zalesak    | on    | 100s | 3      | (-4.8687438f-5, 0.015954636f0)|![mbw_velocity_day100](https://github.com/CliMA/ClimaAtmos.jl/assets/39932030/1d303b67-5cce-4875-9bbd-74d17753e977)|![mbw_moisture_day100](https://github.com/CliMA/ClimaAtmos.jl/assets/39932030/f9c132ad-0de1-4d19-abb5-1ea1bfae65e4)|![mbw_basic_day100](https://github.com/CliMA/ClimaAtmos.jl/assets/39932030/f5b6cb8c-ae11-461e-a0a7-3775e84265a8)|


- Moist Aquaplanet:

| Time-stepper  |   upwinding mode    | limiters    | `dt` | `max_newton_iters` | `qt` extrema   | diagnostics | 
|:--------------------:|:-----------------------------:|:-------------:|:-----:|:---------------------------------:|:-------------------|:---------------:|
| ARS  |   central    | off    | 150s | 1      |(-1.1992041f-5, 0.01808344f0)|![diagnostics](https://github.com/CliMA/ClimaAtmos.jl/assets/39932030/2e3e13ac-8bee-43d1-a4f7-bfebbba9fbd2)|
| SSP333  |   central    | on    | 100s | 3      |(-1.0358959f-5, 0.01761985f0)|![diagnostics](https://github.com/CliMA/ClimaAtmos.jl/assets/39932030/fbe09796-872b-451c-9611-8e0fe64af285)|
| SSP332  |   central    | on    | 75s | 3      |(-8.1168555f-6, 0.01757332f0)|![diagnostics](https://github.com/CliMA/ClimaAtmos.jl/assets/39932030/f3487120-b251-41d3-904b-dddfe778c432)|
| SSP333  |   1st-order    | on    |  |       |||
| SSP332  |   1st-order    | on    |  |       |||
| SSP333  |   3rd-order    | on    | 100s | 3      |(-3.7739674f-6, 0.017673798f0)|![diagnostics](https://github.com/CliMA/ClimaAtmos.jl/assets/39932030/d3af786f-b381-47c6-8a3c-d61650228bf8)|
| SSP332  |   3rd-order    | on    | 75s |    3   |(-3.6901736f-6, 0.017614143f0)|![diagnostics](https://github.com/CliMA/ClimaAtmos.jl/assets/39932030/fa101898-8691-4e6e-8b05-f2c6468ba44c)|
| SSP333  |   zalesak   | on    |  |      |||
| SSP332  |   zalesak   | on    |  |      |||

-----------------------------
For the ones that were unstable (6 in total), I'm going to rerun them using the restart file as @tapios suggested. Tapio, can you please confirm that I understood correctly what you suggested: to use a day10 check-pointed file obtained from a different time-stepper and upwinding mode (ARS + central diff), manually zero-out the `qt` values in the HDF5 file, and use that as the restart file for the other time-stepper and upwinding mode simulations?  Thanks

**Comment by tapios** [comment]
Almost, with two modifications:

1. Use a restart file from a spun-up state. So for the aquaplanet, this would be ~100 days (or at least 50 days). I'm not quite sure what it is for the MBW, but probably more than 10 days. 

2. Manually zero out values negative `q_t` values (not all of them).

Given the above results, I'd also like to see ARS with (a) horizontal limiters and (b) limiters + upwinding, even if that is not rigorously justifiable for ARS.

**Comment by tapios** [comment]
Just to follow up on this here. The results in the table are confusing in that they are not always showing a clear benefit of limiters/upwinding with flux correction where they should (i.e., with SSP schemes at least). We need to increase turnaround time to understand what is going on here. So:

* Set up a configuration where you start from a restart file with a spun-up state but with all q_t set to be non-negative.
* Run the various configurations for a few simulated days. (Set precipitation timescale to be much longer than `dt`, or eliminate precipitation entirely, to make sure this is not causing negative `q_t`.)
* Check minimum and maximum q_t on SE *nodes* (not the interpolated values).
* Limiters plus 1st-order upwinding (or with 3rd-order plus flux correction) should preserve positivity with SSP schemes. Do we see that? If not, why not? Make plots showing where negative values arise and investigate why.

**Comment by valeriabarra** [comment]
Okay, I plotted results from both a spunup state and just the initial condition t=0. 
Here are the first 24-hours (with hourly outputs) of simulation of the coarse-resolution (for faster turnaround time) MBW test case with SSP333, limiters and 1st-order upwinding: 

I'm plotting the time-series of the minima of `qt` and the maxima of `qt` separately: 
![time_series_lows](https://github.com/CliMA/ClimaAtmos.jl/assets/39932030/467244f7-d8b8-4fdf-8b2f-7f8e7d028aba)

![time_series_highs](https://github.com/CliMA/ClimaAtmos.jl/assets/39932030/ab70de71-caba-491c-84ba-1dcf9274c213)

**Comment by valeriabarra** [comment]
Here is an animation of the `qt` negative values to see where they happen. It is at the poles. This is level = 5 (out of the 10 vertical levels in total). The higher-up the less negative values we have; with levels 8,9,10 that are completely without negative `qt` values)

Note: the plot appears to be very pixelated - that's only because of the very small range of values in the colorbar. 

https://github.com/CliMA/ClimaAtmos.jl/assets/39932030/df045353-6a2b-4253-a2ae-b4193713f7bb

**Comment by valeriabarra** [comment]
Here is an animation starting from a spunup state (at 30days and with all `qt` set to be non-negative) run for 10 days with daily output. 

 This is level = 6 (out of the 10 vertical levels in total). We see that it has some pretty large negative values.
 

https://github.com/CliMA/ClimaAtmos.jl/assets/39932030/e04c0100-43c6-49b2-869d-0d08b636efdc

**Comment by Zhengyu-Huang** [comment]
With @szy21 , we have tried explicit treatment of the tracer equation, we observe that
1) For the moist baroclinic wave, after 10 days, the extrema of negative qt is about -10^{-6} (no precipitation)
2) For the moist baroclinic wave, after 10 days, if we turn off the horizontal tendency, it becomes hundreds of single column simulations, the extrema of negative qt is about -10^{-10} (no precipitation)

**Comment by valeriabarra** [comment]
@szy21 , @Zhengyu-Huang , can we close this issue now?
