### ISSUE TITLE
Replace boilerplate macro with exports

### ISSUE THREAD

**Issue by simonbyrne** [CliMA/ClimaAtmos.jl#17]
The boilerplate macro could be replaced by simply using `export` statements inside ClimaAtmos: the [Reexport.jl](https://github.com/simonster/Reexport.jl) package might be useful for this.

This would also have the advantage of not requiring the project running the script to have all the other packages added: instead, the user would only need to add ClimaAtmos.

**Comment by sandreza** [comment]
Thank you for pointing this out! I'll play around with this and open a pull request when it's done
