### ISSUE TITLE
Low resolution gray radiation aquaplanet has wrong result

### ISSUE THREAD

**Issue by szy21** [CliMA/ClimaAtmos.jl#1716]
Found by @valeriabarra @LenkaNovak. See this [build](https://buildkite.com/clima/climaatmos-longruns/builds/994#01885968-6016-42cc-a163-a67b66feb24a) for example.

Here is the qt (g/kg) at level 6 at day 30
![image](https://github.com/CliMA/ClimaAtmos.jl/assets/11598433/9246496b-bad4-4211-8e2b-382b2f895d46)

**Comment by LenkaNovak** [comment]
Thank you @szy21 ! More plots from a similar coupled experiment are [here](https://github.com/CliMA/ClimaCoupler.jl/issues/303), added by @juliasloan25
