### ISSUE TITLE
Compute & print time per timestep

### ISSUE THREAD

**Issue by charleskawczynski** [CliMA/ClimaAtmos.jl#1752]
We can add a time elapsed call to compute this

**Comment by charleskawczynski** [comment]
https://github.com/CliMA/ClimaAtmos.jl/pull/1793 Added simulated years per day to the log. We can also add effective time per time step. One wrinkle here is that this computation will also take callbacks into account, unless we do a separate step

**Comment by Sbozzolo** [comment]
Closed by #2428
