### ISSUE TITLE
GKS failure in output

### ISSUE THREAD

**Issue by charleskawczynski** [CliMA/ClimaAtmos.jl#1753]
There are GKS failures somewhere in the post processing pipeline. We should fix them. 

One job that is particularly concerning is sphere_aquaplanet_rhoe_equilmoist_allsky_gw_raw, which seems to take only 14 m to solve, but that job takes 40 m.

**Comment by szy21** [comment]
This is not an issue anymore as we moved to the new post processing pipeline.
