### ISSUE TITLE
Explicit ClimaAtmos without bycolumn for GPU support

### ISSUE THREAD

**Issue by simonbyrne** [CliMA/ClimaAtmos.jl#1761]
While we're figuring out the ClimaCore changes, it might be worth seeing if we can get a fully explicit GPU case working here by adding an alternative codepath without the `bycolumn` pieces.

**Comment by charleskawczynski** [comment]
Being that we've had a hand full of regressions with #720, I'm wondering if we should just remove some of the bycolumn calls-- the small ones may not be buying us much

**Comment by simonbyrne** [comment]
Fixed by #1811
