### ISSUE TITLE
Scaling analysis script: identify point at which we saturate GPU

### ISSUE THREAD

**Issue by simonbyrne** [CliMA/ClimaAtmos.jl#1863]
With @bloops

**Comment by bloops** [comment]
I can take a stab at generating plots. Is that something we should do in the Julia script itself (and runnable via Buildkite)?
If yes, do you have an example in Clima codebase where you're generating plots so that I can follow the same style?

**Comment by charleskawczynski** [comment]
Sure, that'd be great. I'm not sure we have much of a style with plotting at the moment, but something like:

```
import Plots
# x, y
p = Plots.plot(x, y; title="", xlabel=, ...)
Plots.png(p, joinpath(output_dir, "scaling.png"))
```
should be fine. Where `output_dir` matches the `artifact_paths` entry in the buildkite yaml pipeline.
