### ISSUE TITLE
Dry Held-Suarez: compare CPU vs GPU results

### ISSUE THREAD

**Issue by simonbyrne** [CliMA/ClimaAtmos.jl#1864]
Add GPU test case for dry Held-Suarez, and compare results.

Add mechanism to check that we get the same results on both CPU and GPU.

**Comment by valeriabarra** [comment]
The PR that seems to be closing this issue (#1901 ) adds a baroclinic wave test, not HS. So I would probably open a separate issue or modify this one, for clarity.
