### ISSUE TITLE
Formatter failure with superscripts

### ISSUE THREAD

**Issue by szy21** [CliMA/ClimaAtmos.jl#1875]
Applying the formatter to the following code with results in an error `ERROR: LoadError: Error while PARSING formatted text`
```
function foo(ᶜa)
    return - ᶜa * ᶜa
end
```
It works with the following code
```
function foo(ᶜa)
    return -(ᶜa * ᶜa)
end
```

**Comment by charleskawczynski** [comment]
Moved over to https://github.com/domluna/JuliaFormatter.jl/issues/743
