### ISSUE TITLE
Initialize tendencies with zeros

### ISSUE THREAD

**Issue by jiahe23** [CliMA/ClimaAtmos.jl#188]
These lines are a bit confusing https://github.com/CliMA/ClimaAtmos.jl/blob/main/src/Models/Nonhydrostatic3DModels/equations_thermodynamics.jl#L114-L117

Let's initialize `dY` fields with zeros and use `-=` or `+=` to update all tendency terms (as opposed to the current way which initialize it with a certain tendency term, e.g., hyperdiffusion in this case).

**Comment by bischtob** [comment]
@jiahe23 can you think about the best design of how and where we should do this?
