### ISSUE TITLE
Multi-year dry Held-Suarez simulation

### ISSUE THREAD

**Issue by akshaysridhar** [CliMA/ClimaAtmos.jl#1990]
**Requirements** 

- 55 km domain top
- 200km horizontal resolution
- 63 levels
- Held-Suarez forcing

- [ ] Merge completed simulation configuration into long-run buildkite pipeline.

**Comment by szy21** [comment]
We have some new requirements for the vertical resolution. I will let you know the exact configuration once I know them.

**Comment by akshaysridhar** [comment]
> We have some new requirements for the vertical resolution. I will let you know the exact configuration once I know them.

Noted, thanks: I saw the 65 level requirement w.r.t. performance - this can be changed here once the exact configuration is clear.

**Comment by szy21** [comment]
200-1000 day average:
![image](https://github.com/CliMA/ClimaAtmos.jl/assets/11598433/3fd39d0b-8407-4866-85fa-cbb7464c2c42)
