### ISSUE TITLE
Define config files for aquaplanet with earth orography

### ISSUE THREAD

**Issue by akshaysridhar** [CliMA/ClimaAtmos.jl#1993]
**Requirements** 

- 55 km domain top
- 200km horizontal resolution
- 63 vertical levels
- Earth orography
- Equilibrium moisture
- Time varying insolation 
- All-sky radiation
- 0M Microphysics Scheme
- Monin-Obukhov SF Scheme 
- Vertical Diffusion tendency 
- Cloud diagnostics

(edited to updated surface flux scheme)

**Comment by szy21** [comment]
We don't need held-suarez forcing when there is radiation. Let's do Monin-Obukhov instead of prescribed exchange coefficients. I will get back to you about microphysics.

**Comment by szy21** [comment]
The config file is in longrun_config now.
