### ISSUE TITLE
Check consistency in thermo state domain decomposition

### ISSUE THREAD

**Issue by szy21** [CliMA/ClimaAtmos.jl#1994]
Currently, the thermodynamic state of the environment of diagnostic EDMF is not consistent.

Specifically, we are assuming h_tot_env = h_tot_gm when:

- Calculating entrainment and detrainment tendency of e_tot_updraft
- Calculating sgs mass flux of e_tot_gm

We are assuming ts_env = ts_gm (i.e., h_int_env = h_int_gm) when:
- Calculating physical closures

And, related to this, when the area fraction or u^3 of the updraft is small, we set u^3_updraft=0 and h_tot_updraft = h_tot_gm.

This seems to be inconsistent. I think we should probably:

- Assume h_int_env = h_int_gm, and calculate h_tot_env from h_int_env and u^3_env
- When the area fraction or u^3 of the updraft is small, set u^3_updraft=u^3_gm and h_tot_updraft = h_tot_gm (I need to check that this won't cause problems above the updraft top)

**Comment by szy21** [comment]
@tapios What do you think?

**Comment by tapios** [comment]
What is h_int? Specific internal energy, or enthalpy?

In any case, this seems fine for small updraft velocity (though not in general):

> When the area fraction or u^3 of the updraft is small, set u^3_updraft=u^3_gm and h_tot_updraft = h_tot_gm (I need to check that this won't cause problems above the updraft top)

The difference in updraft vs environment vertical velocity will be insignificant in its effect on thermodynamics (the difference is of order (u^3/c)^2, where c is the speed of sound). But no harm in making this consistent.

**Comment by szy21** [comment]
> What is h_int? Specific internal energy, or enthalpy?
h_int is specific enthalpy

**Comment by tapios** [comment]
> * Assume h_int_env = h_int_gm, and calculate h_tot_env from h_int_env and u^3_env

Ok, this is fine then:

> Assume h_int_env = h_int_gm, and calculate h_tot_env from h_int_env and u^3_env

(But it's unlikely to make a measurable difference on your results.)

**Comment by szy21** [comment]
Sounds good, I will make the change.

**Comment by szy21** [comment]
Closed by #2023
