### ISSUE TITLE
Use microphysics sources from previous timestep 

### ISSUE THREAD

**Issue by trontrytel** [CliMA/ClimaAtmos.jl#2019]
Right now in diagnostic EDMF we are computing and applying the source terms inside the integral. This is causing numerical issues. We can fix them temporarily by setting the precipitation relaxation timescale to 10dt, instead of the default dt.

Alternatively we could try computing the source terms after the big integral is done. This would mean we would be applying the previous timestep sources inside the integral. 

It's worth testing which of the two bad options performs better

**Comment by trontrytel** [comment]
Here it is how it looks for box TRMM. Based on those results I think we should keep what we have right now. Applying the previous time step source term is even more of a hack and it does not help us to set the precipitation relaxation timescale back to dt. cc: @szy21 @tapios 

- Applying the current source term inside the diagnostic EDMF integral with precipitation timescale = 10xdt (main branch)

![contours_main_10x_slower_relax](https://github.com/CliMA/ClimaAtmos.jl/assets/1196696/f3827a00-37ab-4384-ad16-7d1344f3fa7c)

- Applying the current source term inside the diagnostic EDMF integral with precipitation timescale = dt

![contours_main_dt_relax](https://github.com/CliMA/ClimaAtmos.jl/assets/1196696/f69c175c-5b13-4209-a93a-04fad0358c05)

- Applying the previous timestep source term inside the diagnostic EDMF integral with precipitation timescale = 10xdt

![contours_testing_10x_slower_relax](https://github.com/CliMA/ClimaAtmos.jl/assets/1196696/279c8aa9-815d-4de7-a710-d4d0fc66071f)

- Applying the previous timestep source term inside the diagnostic EDMF integral with precipitation timescale = dt
 
![contours_testing_dt_relax](https://github.com/CliMA/ClimaAtmos.jl/assets/1196696/1dda0e6d-f6c5-4b43-b55b-8e0a7ed2f1dc)

**Comment by szy21** [comment]
Thanks for looking at this. Let's keep the longer relaxation timescale then.

**Comment by trontrytel** [comment]
> Thanks for looking at this. Let's keep the longer relaxation timescale then.

Agreed. I'm glad that the previous timestep sources hack is not better
