### ISSUE TITLE
O1.5.2c Multi-year, high-topped, aquaplanet simulations without topography, clearsky radiation and 0-moment microphysics.

### ISSUE THREAD

**Issue by akshaysridhar** [CliMA/ClimaAtmos.jl#2058]
# The Climate Modeling Alliance
### Purpose
Tracking SDI for multi-year high-top aquaplanet simulation and zero-moment microphysics and Monin-Obukhov surface fluxes. 

### Cost/Benefits/Risks
Cost / Schedule Risk: HPC outage during week of September 11. Restart files should help mitigate some issues with resource sharing on the central cluster. 
Benefit: Stable configurations towards target AMIP simulations. 

### People and Personnel
- Lead: @akshaysridhar 
- Collaborators: @szy21 (insolation / radiation setup) 
- Reviewers: --> @szy21 @sriharshakandala @trontrytel 

### Components
- Target domain parameters: 55km lid, vertical spacing 30m (base), 3000m (top), sponge layer (35-50km), 200km horizontal resolution (16 horizontal elements, np = 3), 63 vertical levels.
- Config files for target simulation without topography, with 0M microphysics.  https://github.com/CliMA/ClimaAtmos.jl/issues/1992
- Verification of simulation stability with topography given new resolution parameters (towards 1.5.2e)
- Time-varying insolation
- Clear-sky radiation
- Monin-Obukhov similarity theory for surface fluxes
- Cloud diagnostics

### Results and Deliverables
- [x] #2060
- [x] #2061

Multi-year refers to 1000 day simulations. Merged config files in buildkite pipeline will correspond to simulation end-times which are feasible in a 24hr wallclock-time (given current buildkite constraints). 

### SDI Revision Log
(1) Restrict cases to exclude topography in this specific block of work. Microphysics (1M), all-sky radiation, and topography configurations will be tracked w.r.t the 1.5.2d, 1.5.2e OKRs. cc @szy21

### CC
@tapios @simonbyrne @cmbengue @szy21

**Comment by szy21** [comment]
Thanks Akshay. I was thinking that the final deliverable of this milestone would be **aquaplanet, clear-sky radiation, time-varying insolation, without topography.** We can add topography and land in the AMIP milestone, and we can add cloud diagnostics and all-sky radiation with 1M microphysics later (as it is not correct now). Of course, feel free to include aquaplanet with topography simulation in the buildkite, but I would focus on the results of the above setup.

**Comment by akshaysridhar** [comment]
Noted, thanks. I'll revise the SDI to include the cases without topography as a step towards the topo+1M simulations. Topography will then only correspond to the `1.5.2d` milestone in the OKR docs.

**Comment by szy21** [comment]
This SDI/milestone is done. The simulation is stable and the result looks good. It is added to the longrun buildkite: https://github.com/CliMA/ClimaAtmos.jl/blob/baa37f0fff5f497897c39d01bea51acec36df240/.buildkite/longruns/pipeline.yml#L144. I am going to close this. Thanks @akshaysridhar!

**Comment by akshaysridhar** [comment]
Thanks @szy21
