### ISSUE TITLE
Configuration files for multi-year simulations with 0-M microphysics + clear-sky radiation + time varying insolation with M-O surface fluxes.

### ISSUE THREAD

**Issue by akshaysridhar** [CliMA/ClimaAtmos.jl#2061]

**Comment by akshaysridhar** [comment]
Summary: Aquaplanet + Clearsky radiation (Time varying insolation) + 0M + MO
<img width="1231" alt="Screenshot 2023-10-12 at 8 36 58 AM" src="https://github.com/CliMA/ClimaAtmos.jl/assets/43710045/74533135-be7e-4179-95a9-81b0ac6e392b">
Average over 600 days.

**Comment by szy21** [comment]
The result looks good, thanks!
