### ISSUE TITLE
u_3 at the bottom cell face is not zero

### ISSUE THREAD

**Issue by szy21** [CliMA/ClimaAtmos.jl#2086]
When running the `sphere_baroclinic_wave_rhoe` simulation in ci, Y.f.u_3 is not zero at the bottom cell face:
```
Fields.level(Y.f.u₃, half)
ClimaCore.Geometry.Covariant3Vector{Float32}-valued Field:
  components: 
    data: 
      1: Float32[-1.10124, -0.122195, -0.277133, -0.0229017, 0.0599936, -0.00809689, -0.0431773, 0.170735, 0.250247, 0.0437873  …  -0.114353, 0.0320632, -0.556519, 0.214318, 0.0463827, 0.244027, -1.10124, -0.122195, -0.277133, -0.0229017]
```
It is zero if hyperdiff is set to "false".

Found together with @trontrytel. cc @simonbyrne.

**Comment by simonbyrne** [comment]
Do you know if this was the case before #2006? Because the logic should still be the same:
https://github.com/CliMA/ClimaAtmos.jl/pull/2006/files#diff-2eab639ff3ba32cd1f1eaab302ce6aa6845984a8f1d1aaad8c9c46896db13c28L177

In any case, it should get cleaned up by `set_precomputed_quantities!`. When are you accessing it?

**Comment by szy21** [comment]
> Do you know if this was the case before #2006? Because the logic should still be the same: https://github.com/CliMA/ClimaAtmos.jl/pull/2006/files#diff-2eab639ff3ba32cd1f1eaab302ce6aa6845984a8f1d1aaad8c9c46896db13c28L177

I don't remember exactly. I remember u_3 at the surface is zero in the diagnostics, but that is after `set_precomputed_quantities!`

> In any case, it should get cleaned up by `set_precomputed_quantities!`. When are you accessing it?

Right, I was accessing it at the end of the simulation, when `set_precomputed_quantities!` is not called yet I think. I thought all the tendencies of u_3 at the surface would be zero though?
