### ISSUE TITLE
Test different EDMF closure and limiter

### ISSUE THREAD

**Issue by trontrytel** [CliMA/ClimaAtmos.jl#2108]
Here are some ideas that may help make EDMF more stable

Entrainment:
- Make entrainment large when a is small
- Replace entrainment E by E = L E',  L = 4a(1-a)

Detrainment:
- Make detrainment large at the cloud top: b/w when b is negative (Tan et al. eq. 27)
- Add area fraction limiter (Tan et al. discussion below eq. 27)
- Add horizontal divergence (Weller and McIntyre eq. 23)
- Replace detrainment D by D = L D',  L = 4a(1-a)

Pressure drag:
- Make drag large when a is small (Weller and McIntyre eq. 19)

**Comment by szy21** [comment]
I will update ideas and  things I have tried here

**Comment by szy21** [comment]
I'm going to close this as it is pretty outdated. We have most of the terms implemented, and it's just a matter of changing parameters.
