### ISSUE TITLE
Revamp current SCM

### ISSUE THREAD

**Issue by jiahe23** [CliMA/ClimaAtmos.jl#212]
Revamp current single column model so that it is consistent with the infrastructure set up in nhm.

**Comment by bischtob** [comment]
@jiahe23, can we fold this into #210 ?

**Comment by jiahe23** [comment]
> @jiahe23, can we fold this into #210 ?

They are separate issues. 

I want to first make a general scm infrastructure that follows current nhm. This can be closed once we bring back the old ekman layer test.

Once this is ready, it allows for compressible or anelastic choices for base model, and #210 can be closed once the anelastic and a test on that being added.
