### ISSUE TITLE
The cache significantly increases compile time

### ISSUE THREAD

**Issue by Sbozzolo** [CliMA/ClimaAtmos.jl#2138]
From https://github.com/CliMA/ClimaCore.jl/issues/1467

Tuples of `Field`s affect compilation time and are a major cause of latency.

In `ClimaAtmos`, the cache is a massive tuple. A native restructuring of the cache from a tuple to a struct shows 60% latency reduction to get the integrator for a moist case without radiation. The latency is further reduced for more complex cases.

**Comment by simonbyrne** [comment]
See https://github.com/CliMA/ClimaAtmos.jl/issues/2217
