### ISSUE TITLE
GPU benchmark for moist case

### ISSUE THREAD

**Issue by simonbyrne** [CliMA/ClimaAtmos.jl#2156]
@szy21 is there a config we should use?

**Comment by szy21** [comment]
We can use this one: https://github.com/CliMA/ClimaAtmos.jl/blob/main/config/longrun_configs/longrun_hs_rhoe_equilmoist_nz63_0M_55km_rs35km.yml, but change the resolution to the targeted one.

**Comment by simonbyrne** [comment]
Currently failing here: https://buildkite.com/clima/climaatmos-target-gpu-simulations/builds/82#018ad87d-0c3a-49d1-8335-e88c6f4a525f/138-201

**Comment by simonbyrne** [comment]
Can we also add to the CI pipeline as a soft fail for now?
