### ISSUE TITLE
GPU compilation error in `rayleigh_sponge_cache`

### ISSUE THREAD

**Issue by sriharshakandala** [CliMA/ClimaAtmos.jl#2158]
GPU compilation for the `moist Held-Suarez` simulation generates a compilation error in `rayleigh_sponge_cache`. The full error message can be found here: https://buildkite.com/clima/climaatmos-target-gpu-simulations/builds/71#018acda7-0c93-48d9-881e-90c321d2b525
cc: @simonbyrne

**Comment by simonbyrne** [comment]
@sriharshakandala can you get it down to a reproducible example?

**Comment by charleskawczynski** [comment]
> .f is of type Type{Float32} which is not isbits.

I'm pretty sure we're just running into https://github.com/CliMA/ClimaCore.jl/issues/1372

**Comment by simonbyrne** [comment]
I would have though that this would have been fixed by https://github.com/JuliaGPU/CUDA.jl/pull/2000, but maybe it's not in the version of CUDA.jl we're using.

**Comment by simonbyrne** [comment]
We can use the `$(FT(0)))` trick for now
