### ISSUE TITLE
`ERROR: LoadError: InitError: CUDA error (code 999, CUDA_ERROR_UNKNOWN)` is bogging down CI

### ISSUE THREAD

**Issue by charleskawczynski** [CliMA/ClimaAtmos.jl#2162]
The frequency of the `ERROR: LoadError: InitError: CUDA error (code 999, CUDA_ERROR_UNKNOWN)` error is very high. Here is one example: https://buildkite.com/clima/climaatmos-ci/builds/13337#018ad8bc-5271-4a19-8cbc-19708a1c276d/142-145.

This is blocking https://github.com/CliMA/ClimaAtmos.jl/issues/2015 (and many more PRs, I'm sure).

**Comment by charleskawczynski** [comment]
Maybe relevant: https://discourse.julialang.org/t/need-help-with-cuda-jl-installation/52786/2

**Comment by trontrytel** [comment]
I confirm that it affects more PRs
