### ISSUE TITLE
Remove extraneous dss call

### ISSUE THREAD

**Issue by charleskawczynski** [CliMA/ClimaAtmos.jl#2197]
Currently, the time stepper performs an extra dss operation at the start of the step, which can be removed.

**Comment by charleskawczynski** [comment]
ClimaTimeSteppers PR started here: https://github.com/CliMA/ClimaTimeSteppers.jl/pull/228

**Comment by simonbyrne** [comment]
Can also get rid of a `post_explict!` call.

**Comment by charleskawczynski** [comment]
Closed by #2201.
