### ISSUE TITLE
Switch over to the new diagnostic module

### ISSUE THREAD

**Issue by Sbozzolo** [CliMA/ClimaAtmos.jl#2198]
The `ClimaAtmos` pipelines currently still rely on the old diagnostic system. Now that the new system is in place, we can remove the old one. This requires ensuring that we are outputting and plotting all the quantities we care about.
```[tasklist]
### Tasks
- [ ] https://github.com/CliMA/ClimaCore.jl/pull/1497
- [ ] https://github.com/CliMA/ClimaAtmos.jl/pull/2179
```

**Comment by szy21** [comment]
https://github.com/CliMA/ClimaAtmos.jl/pull/2200 is a draft PR that adds the remaining diagnostics. Still work in progress.

**Comment by szy21** [comment]
We have moved to the new diagnostics module.
