### ISSUE TITLE
Test suite returns errors about missing files

### ISSUE THREAD

**Issue by teopb** [CliMA/ClimaAtmos.jl#2207]
After installing I attempted to develop/ run the test suite using the instructions in the main readme.

I tried to run the suite from `ClimaAtmos.jl` with
`julia --project=test test/runtests.jl`

I received 2 errors
`Test unique aliases: Error During Test at /projects/tepr6090/software/ClimaAtmos.jl/test/parameter_tests.jl:28
  Got exception outside of a @test
  "parameter_tests.toml": No such file`

and

`Test all parameter tomls in toml/: Error During Test at /projects/tepr6090/software/ClimaAtmos.jl/test/parameter_tests.jl:37
  Got exception outside of a @test
  IOError: readdir("../toml"): no such file or directory (ENOENT)`

The files/directory appears to be there when I look myself.

**Comment by charleskawczynski** [comment]
@nefrathenrici, can you please fix this? I've generally followed the slow but bullet-proof pattern for file inclusion of:

```julia
import ClimaAtmos as CA
include(joinpath(pkgdir(CA), "path_to_file", "file.jl"))
```
This:
 - Does not matter what `pwd` is (i.e., does not matter where Jjulia is launched from
 - Does not rely on what directory a file is in (e.g., using `@__DIR__`/`@__FILE__`), so it can easily be copy-pasted into the REPL

The main downside is that: ClimaAtmos has to be precompiled before the file can be included, which is a bit painful.
