### ISSUE TITLE
DYAMOND configuration GPU run + metadata size error

### ISSUE THREAD

**Issue by sriharshakandala** [CliMA/ClimaAtmos.jl#2216]
The DYAMOND configuration GPU run is crashes witha `metadata size` error on the GPU. 
The full error message can be found here: https://buildkite.com/clima/climaatmos-target-gpu-simulations/builds/106#018b1570-62bc-400f-a454-04a9a2595aa3
The error seems to be triggered in `atmos_state` function in `src/initial_conditions`

**Comment by simonbyrne** [comment]
We may have to refactor how we initialize things?

**Comment by sriharshakandala** [comment]
Sure. I can take a look!

**Comment by simonbyrne** [comment]
failure here: 
https://buildkite.com/clima/climaatmos-target-gpu-simulations/builds/106#018b1570-62bc-400f-a454-04a9a2595aa3/138-231
in particular it is
https://github.com/CliMA/ClimaAtmos.jl/blob/4fb9922892f424cf8c0ab3dcdfd82bf8ab449ac2/src/initial_conditions/atmos_state.jl#L14-L16

**Comment by charleskawczynski** [comment]
> We may have to refactor how we initialize things?

Can we first try to do this particular operation on the CPU?

**Comment by sriharshakandala** [comment]
The simulation runs fine with `Float32` but crashes with `Float64`. The metadata size in `Float64` case seems to approximately double what it is with `Float32`.

**Comment by sriharshakandala** [comment]
I think we need to refactor the initialization code!

**Comment by sriharshakandala** [comment]
Upgrading to the `CUDA.jl` main branch could solve this issue temporarily! I opened a new issue for refactoring initialization code here: https://github.com/CliMA/ClimaAtmos.jl/issues/2258

**Comment by simonbyrne** [comment]
@sriharshakandala Is this resolved?

**Comment by sriharshakandala** [comment]
Yes. The final piece, involving P100s, is resolved with a test branch, here: https://github.com/orgs/CliMA/projects/55/views/1?pane=issue&itemId=37383219
