### ISSUE TITLE
Use FDScheme when calling SurfaceFluxes

### ISSUE THREAD

**Issue by LenkaNovak** [CliMA/ClimaAtmos.jl#2230]
As found by @gdecker1 and @akshaysridhar , we are not calling `FDScheme` (correct for our vertical discretization) when calculating surface fluxes in ClimaAtmos, which assumes the default scheme (`FVScheme`).

@kmdeck, this may be relevant to you guys as well (though in practice it shouldn't change your values much).

**Comment by szy21** [comment]
This has been updated in #2261
