### ISSUE TITLE
Test Float32 outcomes in long-runs with MO surface fluxes.

### ISSUE THREAD

**Issue by akshaysridhar** [CliMA/ClimaAtmos.jl#2234]
Current status: 
https://buildkite.com/clima/climaatmos-longruns/builds/1187#_

**Comment by szy21** [comment]
Looks good. Could you make a lat-lon plot of the surface fluxes, and plot the difference between the new and old surface fluxes? Just focusing on `Aquaplanet Clearsky Idealized Insolation` would be good.

**Comment by akshaysridhar** [comment]
https://buildkite.com/clima/climaatmos-longruns/builds/1191 : Float32 w/ updated SF.jl

**Comment by szy21** [comment]
The results look good, thanks! I would still be interested to know the quantitative difference between the two versions of surface fluxes, but with the current results I am happy to move on with tagging a new release of SurfaceFlux and updating ClimaAtmos.

**Comment by akshaysridhar** [comment]
$\Delta$ (New SF Scheme  - Old SF Scheme) for fields represented above. 
<img width="1293" alt="Screenshot 2023-10-18 at 4 32 39 PM" src="https://github.com/CliMA/ClimaAtmos.jl/assets/43710045/df17e6be-cef3-4a43-ab9a-cfd75c1f8968">

**Comment by szy21** [comment]
The difference looks ok, thanks!

**Comment by szy21** [comment]
Could you help plot this run: https://buildkite.com/clima/climaatmos-longruns/builds/1195#018b509b-e1c9-4c36-a423-64a90899120a?

**Comment by akshaysridhar** [comment]
> Could you help plot this run: https://buildkite.com/clima/climaatmos-longruns/builds/1195#018b509b-e1c9-4c36-a423-64a90899120a?

Summary: Day 100-300 average (10 day output frequency)
<img width="1322" alt="Build1195_Aquaplanet" src="https://github.com/CliMA/ClimaAtmos.jl/assets/43710045/7891930a-0e03-421b-96fd-a26b7d66bec9">

Surface Energy Fluxes: Day 100-300 average (10 day output frequency)
<img width="1117" alt="Averaged_sfc_energy_flux" src="https://github.com/CliMA/ClimaAtmos.jl/assets/43710045/bbd07477-71f7-4c77-a64c-703169dd09fc">

Surface Energy Fluxes: Day 300 Snapshot
<img width="906" alt="Instantaneous_Day300_sfc_energy_flux" src="https://github.com/CliMA/ClimaAtmos.jl/assets/43710045/fbaa767e-9d22-4271-8780-60ff98aa3d0f">

**Comment by szy21** [comment]
Looks good, thanks! I am going to close this issue.
