### ISSUE TITLE
New diagnostic `nc` writer: error when writing surface variables

### ISSUE THREAD

**Issue by akshaysridhar** [CliMA/ClimaAtmos.jl#2271]
In the branch `https://github.com/CliMA/ClimaAtmos.jl/tree/as/test-viz-newdiag`, I'm attempting to test the new diagnostic output specifications. I'm using [this file](https://github.com/CliMA/ClimaAtmos.jl/blob/as/test-viz-newdiag/config/model_configs/sphere_aquaplanet_rhoe_equilmoist_allsky_gw_res.yml) to test the output workflow. When specifying the `h5` writer, I get successful simulation outcomes (see truncated trace below) with generated files e.g. `cli_6.0h_average_21600.0.h5` for the requested variables/intervals.
```
┌ Info: Running
│   job_id = "sphere_aquaplanet_rhoe_equilmoist_allsky_gw_res"
│   output_dir = "output/sphere_aquaplanet_rhoe_equilmoist_allsky_gw_res"
└   tspan = (0.0f0, 43200.0f0)
[ Info: solve!: 188.394 s (282638063 allocations: 119.16 GiB)
[ Info: sypd: 0.6282364633899803
....
....
┌ Warning: Buildkite not detected. Skipping regression tests.
└ @ Main ~/Research/Codes/ClimaAtmos.jl/regression_tests/compute_mse.jl:58
[ Info: Please review output results before merging.
[ Info: Callback verification, n_expected_calls: AbstractFloat[0.6666666666666666, 2.0f0, 108.0f0]
[ Info: Callback verification, n_measured_calls: [[1], [3], [108]]
```

When switching the output writer to `nc` however, this simulation fails - seemingly due to specific output keys (I assume invalid keys would be caught even in the h5 writer), since I still see files like 
<img width="353" alt="Screenshot 2023-10-23 at 2 13 02 PM" src="https://github.com/CliMA/ClimaAtmos.jl/assets/43710045/f2319a73-7258-455b-81ed-9485c497556d">

@Sbozzolo Can you help check this out please? Thanks! The first diag variable at which a run with this [config file](https://github.com/CliMA/ClimaAtmos.jl/blob/as/test-viz-newdiag/config/model_configs/sphere_aquaplanet_rhoe_equilmoist_allsky_gw_res.yml) above fails is `ts`, or in its absence, `hfes`- both are surface vars on the sphere.

**Comment by Sbozzolo** [comment]
Is this with the main branch?

**Comment by akshaysridhar** [comment]
> Is this with the main branch?
Working branch is `https://github.com/CliMA/ClimaAtmos.jl/tree/as/test-viz-newdiag` but `main` has been merged into this as of commit ` caded4d1`

**Comment by akshaysridhar** [comment]
I suspect it's something to do with the surface variables

**Comment by Sbozzolo** [comment]
Okay, the `NetCDF` writer you are currently does not work with surfaces (and many other cases), but that has been fixed in [this](https://github.com/CliMA/ClimaAtmos.jl/pull/2179) branch.

I working out some issues with performance and GPUs and then we can merge it

**Comment by akshaysridhar** [comment]
Noted thanks: Pulling the branch associated with #2179 > will report results shortly.

**Comment by akshaysridhar** [comment]
Works in commit `49105`. @Sbozzolo Thanks! Resolved, closing issue.
