### ISSUE TITLE
Remove Float64 conversion in insolation

### ISSUE THREAD

**Issue by szy21** [CliMA/ClimaAtmos.jl#2300]
Currently, we convert the argument to Float64 when calculating the zenith angle [here](https://github.com/CliMA/ClimaAtmos.jl/blob/d5bc2cff6422dbeef595b70b4853654d79ab5ff1/src/callbacks/callbacks.jl#L118-L119). We shouldn't need this anymore.

**Comment by szy21** [comment]
@akshaysridhar Would you be able to run a time-varying insolation longrun to test this?

**Comment by akshaysridhar** [comment]
https://buildkite.com/clima/climaatmos-longruns/builds/1201#018b721b-b0b9-4a91-a9a2-b4972f972633 shows the raw results (hdf5) to date - I'll set up a restart from day 180.

**Comment by szy21** [comment]
No need to run it for longer. Could you make some plots of TOA radiative fluxes?

**Comment by akshaysridhar** [comment]
Day 180 summary (spatial mean where appropriate, single timestamp) 
<img width="1001" alt="Screenshot 2023-10-30 at 10 38 09 AM" src="https://github.com/CliMA/ClimaAtmos.jl/assets/43710045/ccfd4ed5-84b4-4bbe-8975-363c3d7116b7">

**Comment by szy21** [comment]
Looks good, thanks! Could you open a PR?
