### ISSUE TITLE
Make vertical diffusion dependent on topography

### ISSUE THREAD

**Issue by szy21** [CliMA/ClimaAtmos.jl#2340]
Currently, vertical diffusion assumes a fixed boundary layer height (850 hPa) and uses a fixed reference pressure (1000 hPa) in the exponential decay profile. This is not realistic with topography and will result in small diffusivity over mountains. cc @akshaysridhar

**Comment by akshaysridhar** [comment]
Testing bl-stability-dependent method here:  https://buildkite.com/clima/climaatmos-ci/builds/14775#_ I'll follow up on the segfault cases (unrelated column /plane cases (??)) before setting up the PR from branch `[as/frierson-diff](https://buildkite.com/clima/climaatmos-ci/builds?branch=as%2Ffrierson-diff)`.
