### ISSUE TITLE
Make prognostic EDMF run on GPU

### ISSUE THREAD

**Issue by szy21** [CliMA/ClimaAtmos.jl#2365]

**Comment by szy21** [comment]
Currently failing: https://buildkite.com/clima/climaatmos-ci/builds/14915#018bd089-0cc4-4358-91fc-b01a72906e7b

**Comment by szy21** [comment]
The most recent failure: https://buildkite.com/clima/climaatmos-ci/builds/17646#018e5944-daae-493a-bb13-e0744e0a254c. cc @charleskawczynski

**Comment by charleskawczynski** [comment]
Accidentally closed by #2366.

**Comment by szy21** [comment]
Fixed by #2819
