### ISSUE TITLE
CompatHelper is not updating Project.toml in test/

### ISSUE THREAD

**Issue by jiahe23** [CliMA/ClimaAtmos.jl#241]

**Comment by jiahe23** [comment]
Can we remove the Project.toml from test/ and have everything in the repo home directory? @bischtob @akshaysridhar @charleskawczynski

**Comment by jiahe23** [comment]
> Can't we just manually update the test env compat?

Is this a common solution? We could do that for now, but I would expect an automatic way that CompatHelper handles it.

**Comment by charleskawczynski** [comment]
CompatHelper is not guaranteed to be able to update your compat entries, the PRs it opens are more of a notification a package dependency compat entry can be updated, and suggests a way to update it that will work if there are no breaking API changes for your package (which is not always the case).
