### ISSUE TITLE
Occasional HDF5/NetCDF errors in dealing with diagnostics output files

### ISSUE THREAD

**Issue by Sbozzolo** [CliMA/ClimaAtmos.jl#2425]
When the diagnostics NetCDF files are not cleanly closed, new runs with the same output directory can lead to HDF5 errors like:
```
ERROR: LoadError: Could not compute diagnostic Surface Altitude: 
NCDatasets.NetCDFError(-101, "Opening path output/slabplanet_ft32/orog_inst.nc: NetCDF: HDF error")
```

**Comment by szy21** [comment]
Adding to this, I think when they are closed cleanly, the new run will append to the existing files, rather than overwriting them.

**Comment by Sbozzolo** [comment]
Good point.

However, we should think if overwriting is the correct behavior we want. 

Suppose you ran a very long simulation, and you accidentally start a second simulation in the same folder. That will erase all the output from the previous run. 

Appending is also the desired behavior when we restart from a checkpoint.

**Comment by Sbozzolo** [comment]
I think this should be taken care of.
