### ISSUE TITLE
Identify correct parameters for a stable aquaplanet with PrognosticSurfaceTemperature

### ISSUE THREAD

**Issue by LenkaNovak** [CliMA/ClimaAtmos.jl#2457]
In #2399 , we found that the current initial conditions and parameters for the target aquaplanet case (for AMIP) lead to an unstable run, failing to complete 3 time steps. 

The same initial conditions are run in the coupler where this is stable at least for 100d. The standalone case differs from the coupled case by:
- the specification of the surface fluxes and coupling with the slab ocean at each substage (rather than every step)
- here we're testing on atmos main with new features, e.g. bubble correction, which have not been tested in the coupler

This needs to be investigated further so that we can achieve a long run (300d in Buildkite, but test 5yr+ to reach equilibration) at the target resolution, with the slab ocean surface.

**Comment by szy21** [comment]
Which build is this?

Bubble correction is by default true (so if you don't specify it in the coupler it should be on?), but you can set it to false in the yaml file.

**Comment by LenkaNovak** [comment]
> Which build is this?
> 
> Bubble correction is by default true (so if you don't specify it in the coupler it should be on?), but you can set it to false in the yaml file.

This was tested locally when the BK builds were blocked by the dependency issue #2460. When did the bubble correction become available? We're using ClimaAtmos v0.17.1 in the coupler right now. In any case, it looks like we need to find a new config for this setup.

**Comment by szy21** [comment]
> > Which build is this?
> > Bubble correction is by default true (so if you don't specify it in the coupler it should be on?), but you can set it to false in the yaml file.
> 
> This was tested locally when the BK builds were blocked by the dependency issue #2460. When did the bubble correction become available? We're using ClimaAtmos v0.17.1 in the coupler right now. In any case, it looks like we need to find a new config for this setup.

I don't quite remember, but it should be early this year. I was just wondering if I can see anything obvious from the error message of the build. But don't worry if you don't have it. It is possible that we are close to the unstable regime.

**Comment by szy21** [comment]
I just took a look at the [commit](https://github.com/CliMA/ClimaAtmos.jl/commit/d002c31ed477f455ae8e04c459b113a8a6a3f683). It might be because hyperdiffusivity is not set correctly. After https://github.com/CliMA/ClimaAtmos.jl/pull/2449 we need to set hyperdiffusivity for vorticity and tracer separately. The simulation is running with the correct hyperdiffusivity here: https://buildkite.com/clima/climaatmos-longruns/builds/1321#018cce0e-e8f9-448e-bb7b-41d6aa75bca5
