### ISSUE TITLE
Add AMIP/aquaplanet experiments to `build_history`

### ISSUE THREAD

**Issue by LenkaNovak** [CliMA/ClimaAtmos.jl#2459]
This is needed for better performance tracking (e.g., as in #2399). We need to decide on the most relevant runs that we want to retain in the long term and specify the `key` label in `pipeline.yml` to trigger the loggers. 

The selected run should contain all physical components that are needed for the target AMIP run.

**Comment by szy21** [comment]
It seems this PR https://github.com/CliMA/ClimaAtmos.jl/pull/2456 makes every simulation without EDMF two times slower (it should be captured by the dry and moist dycore simulations though). I'm looking into it. Also the builds for main branch are not triggered anymore after switching to merge queue, so the build history is not as helpful. I need to look into that as well.

**Comment by szy21** [comment]
The slowdown should be temporarily fixed by #2466
