### ISSUE TITLE
Deep atmosphere

### ISSUE THREAD

**Issue by simonbyrne** [CliMA/ClimaAtmos.jl#2497]
@tapios suggested adding support for a deep atmosphere configuration. Here is what I think would need to get done:
1. Update the metric terms so that the horizontal metric terms will scale as 

   $$\frac{z+r}{r}$$

   where $r$ is the radius of the reference sphere, and $z$ is the height from this.

2. Change the Coriolis terms to vary about the planetary rotation axis, basically
    ```julia
    cross(Cartesian3Vector(2 * omega), u)
    ```
    (note this should be a `Cartesian3Vector`, not a `WVector`).
3. We would need to distinguish between vertical line integrals, and vertical "wedge" integrals (which is probably what we would typically want?)

4. Gravity: White (2005) suggests scaling gravitational acceleration vertically by
    $$\frac{(z+r)^2}{r^2}$$
    Note that we should _not_  vary gravity by lat or long, as that would no longer correspond to the gradient of a gravitational potential, which could introduce spurious vorticity

If we did want to account for centrifugal effects in apparent gravity (i.e. lower gravitational acceleration at the equator vs the poles), we could switch to an spheroidal earth. I actually don't think this would be too difficult: main difficulty would be figuring out the appropriate conversions (geodetic lat, long, z) <-> (x1,x2,x3) for computing the metric terms.

Links
- The opposite issue from ClimateMachine.jl: https://github.com/CliMA/ClimateMachine.jl/issues/1270
- White, A.A., Hoskins, B.J., Roulstone, I. and Staniforth, A. (2005), Consistent approximate models of the global atmosphere: shallow, deep, hydrostatic, quasi-hydrostatic and non-hydrostatic. Q.J.R. Meteorol. Soc., 131: 2081-2107. https://doi.org/10.1256/qj.04.49
- Staniforth, A., and N. Wood, 2003: The Deep-Atmosphere Euler Equations in a Generalized Vertical Coordinate. Mon. Wea. Rev., 131, 1931–1938, https://doi.org/10.1175//2564.1. 
- Andrew Staniforth, Nigel Wood, Aspects of the dynamical core of a nonhydrostatic, deep-atmosphere, unified weather and climate-prediction model, Journal of Computational Physics, Volume 227, Issue 7, 2008, https://doi.org/10.1016/j.jcp.2006.11.009.
- Nathan J. Mayne, Isabelle Baraffe, David M. Acreman, Chris Smith, Matthew K. Browning, David Skålid Amundsen, Nigel Wood, John Thuburn and David R. Jackson, The unified model, a fully-compressible, non-hydrostatic, deep atmosphere global circulation model, applied to hot Jupiters - ENDGame for a HD 209458b test case, A&A, 561 (2014) A1, DOI: https://doi.org/10.1051/0004-6361/201322174
- Sebastian Borchert, Guidi Zhou, Michael Baldauf, Hauke Schmidt, Günther Zängl, and Daniel Reinert, 2019, The upper-atmosphere extension of the ICON general circulation model (version: ua-icon-1.0) GMD, 12, 3541–3569, 2019, https://doi.org/10.5194/gmd-12-3541-2019
- Skamarock, W. C., H. Ong, and J. B. Klemp, 2021: A Fully Compressible Nonhydrostatic Deep-Atmosphere Equations Solver for MPAS. Mon. Wea. Rev., 149, 571–583, https://doi.org/10.1175/MWR-D-20-0286.1.

**Comment by tapios** [comment]
Thanks, @simonbyrne. This looks good. 

Re 3: We should just support one set of vertical integrals. Usually, that remains a line integral, so that volume integral = line integral x surface integral, and the outward expanding surface integral takes care of the "wedge."

Re 4: Let's just consistently define gravitational acceleration = gradient geopotential. Then choose geopotential  = g r for shallow Earth (with constant g), and a corresponding effective potential for a deep atmosphere when we need it. For now, Phi  = g r suffices, and we can augment that function one day when we need it (e.g., for giant planet simulations). 

Also, let's focus on spherical geopotential surfaces and a spherical geoid. 

The key points are 1 and 2.
