### ISSUE TITLE
Error in hdf5 writer with mpi

### ISSUE THREAD

**Issue by szy21** [CliMA/ClimaAtmos.jl#2505]
When output diagnostics using hdf5 writer with MPI, I got this [error](https://buildkite.com/clima/climaatmos-ci/builds/15782#018cf25e-5110-47e9-929b-8fa5b235eebf/160-238). It works fine without MPI. This is tested in this draft [PR](https://github.com/CliMA/ClimaAtmos.jl/pull/2504). @Sbozzolo Could you look into it?

**Comment by Sbozzolo** [comment]
Can reproduce, thanks.
