### ISSUE TITLE
Update IMEX splitting of vertical advection

### ISSUE THREAD

**Issue by dennisYatunin** [CliMA/ClimaAtmos.jl#2510]
Our current plan is to have the following IMEX splitting of vertical advection:
- Implicit
  - Central vertical advection of active scalars at grid-mean velocity
  - Vertical advection of precipitation at its terminal velocity
  - Central vertical advection of grid-mean values at subgrid-scale velocities (EDMF only)
  - Vertical advection of subgrid-scale values at subgrid-scale velocities (prognostic EDMF only)
- Explicit
  - Vertical advection of horizontal velocity and passive scalars at grid-mean velocity
  - Upwinding corrections to vertical advection of active scalars at grid-mean velocity
  - (Maybe) updwinding corrections to advection of grid-mean values at subgrid-scale velocities (EDMF only)

In order to make our code for the dycore (ignoring EDMF for now) match this plan, we need the following two changes:
- [x]  Split vertical advection at grid-mean velocity into an implicit central component and explicit upwinding corrections
  - Remove the `density_upwinding` flag, and replace it with `Val(:none)` (it does not make sense to upwind density, and what we have now effectively amounts to upwinding the value `1` everywhere)
  - Remove the `energy_upwinding` and `tracer_upwinding` flags from `implicit_tendency!` and `update_implicit_equation_jacobian!`, and replace them with `Val(:none)`
  - Add some new terms to `remaining_tendency!`
    - `vertical_transport!(<energy>, ..., energy_upwinding) - vertical_transport!(<energy>, ..., Val(:none))`
    - `vertical_transport!(<tracer>, ..., tracer_upwinding) - vertical_transport!(<tracer>, ..., Val(:none))`
- [ ] Make the vertical advection of passive tracers at grid-mean velocity explicit
  - Remove all calls to `vertical_transport!` that involve passive tracers (scalars other than `ρ`, `ρe_tot`, and `ρq_tot`) and the grid-mean velocity `ᶠu³` from `implicit_tendency!`, and remove the corresponding Jacobian blocks from `update_implicit_equation_jacobian!`
  - Replace the upwinding correction terms for passive tracers in `remaining_tendency!` with the full vertical advection terms:
    - `vertical_transport!(<tracer>, ..., tracer_upwinding)`

The first change is expected to improve stability for all cases that use upwinding or flux-corrected transport. The second change could lead to a minor decrease in stability, but we do not expect this to happen.

**Comment by OsKnoth** [comment]
Confusing: Vertical advection means we solve the advection equation \dot(c) = -\nabla (w c), w is something like the contra vertical velocity. We discretize the divergence with some higher order interpolation and limiting of c (approximate c from cell center to cell face, may be depending on the sign of w).  Let us now design an implicit time integration method like backward Euler). For solving the nonlinear system for the new time level c we use a simplified Newton method, which means we fix the Jacobian and compute it  from a "simpler" spatial discretization (simple upwind). This Jacobian is very simple and contains only w and metric terms (vertical grid size). Each Newton step requires a function evaluation which includes the exact, higher order right hand side of our discretized advection equation.

**Comment by dennisYatunin** [comment]
@OsKnoth I think what you describe exactly matches what we have now (ignoring the bit about moving passive tracer advection to the explicit tendency). We are currently using flux-corrected transport in the implicit tendency, and we are approximating the Jacobian blocks that correspond to flux-corrected transport with the corresponding blocks for first-order upwinding. We were thinking that only the central component of these blocks contributes to fast waves, and that we could instead move the non-central component out of the implicit solve for fast waves. Do you think this is not valid?

**Comment by tapios** [comment]
So we have a reliable and tested configuration with FCT and know which timestepper (ARS vs SSP) to choose? I think the prognostic EDMF items are also pending. Once we have all of it, we can close it, but I'd like to see the results first.

**Comment by dennisYatunin** [comment]
Also, we still need to do the second part of this issue (make the advection of passive tracers explicit).

**Comment by charleskawczynski** [comment]
We can bump the ref counter / merge https://github.com/CliMA/ClimaAtmos.jl/pull/2580. cc @dennisYatunin

**Comment by charleskawczynski** [comment]
Just so that this doesn't get left behind, I believe @dennisYatunin said that he would rebase and merge #2580, please correct me if I'm wrong.
