### ISSUE TITLE
No artifacts generated in buildkite job

### ISSUE THREAD

**Issue by akshaysridhar** [CliMA/ClimaAtmos.jl#2514]
Example : https://buildkite.com/clima/climaatmos-longruns/builds/1358. 
It's unclear if this is true across multiple job-ids.  

There are two issues here:
(1) No artifacts generated. 
(2) Plot instruction not found - fixed in #2512 (even with the fixed id it's not helpful since the `simdir` is empty).

The GPU run might also be interesting : https://buildkite.com/clima/climaatmos-gpulongruns/builds/22.
(Will populate with more details as the issue becomes clearer)

**Comment by szy21** [comment]
#2512 should fix both of these. The files are there: `/central/scratch/esm/slurm-buildkite/climaatmos-longruns/1358/climaatmos-longruns/longrun_aquaplanet_rhoe_equil_gray_55km_nz63_0M`. It can't be uploaded just because the artifact folder is wrong.
