### ISSUE TITLE
#2489 is bloating the log

### ISSUE THREAD

**Issue by charleskawczynski** [CliMA/ClimaAtmos.jl#2519]
The log in one of the runs is pretty bloated with NetCDF info statements, added in (I think #2489):

```
[ Info: Computing diagnostics:
--
  | [ Info: - orog_inst (NetCDFWriter)
  | [ Info: - ts_1d_average (NetCDFWriter)
  | [ Info: - ta_1d_average (NetCDFWriter)
  | [ Info: - thetaa_1d_average (NetCDFWriter)
  | [ Info: - ha_1d_average (NetCDFWriter)
  | [ Info: - pfull_1d_average (NetCDFWriter)
  | [ Info: - rhoa_1d_average (NetCDFWriter)
  | [ Info: - ua_1d_average (NetCDFWriter)
  | [ Info: - va_1d_average (NetCDFWriter)
  | [ Info: - wa_1d_average (NetCDFWriter)
  | [ Info: - hfes_1d_average (NetCDFWriter)
  | [ Info: - ts_1d_max (NetCDFWriter)
  | [ Info: - ts_1d_min (NetCDFWriter)
  | [ Info: - hur_1d_average (NetCDFWriter)
  | [ Info: - hus_1d_average (NetCDFWriter)
  | [ Info: - clw_1d_average (NetCDFWriter)
  | [ Info: - cli_1d_average (NetCDFWriter)
  | [ Info: - hussfc_1d_average (NetCDFWriter)
  | [ Info: - evspsbl_1d_average (NetCDFWriter)
  | [ Info: - pr_1d_average (NetCDFWriter)
  | [ Info: - rsd_1d_average (NetCDFWriter)
  | [ Info: - rsu_1d_average (NetCDFWriter)
  | [ Info: - rld_1d_average (NetCDFWriter)
  | [ Info: - rlu_1d_average (NetCDFWriter)
  | [ Info: - rsdcs_1d_average (NetCDFWriter)
  | [ Info: - rsucs_1d_average (NetCDFWriter)
  | [ Info: - rldcs_1d_average (NetCDFWriter)
  | [ Info: - rlucs_1d_average (NetCDFWriter)
  | [ Info: Computing diagnostics:
  | [ Info: - orog_inst (NetCDFWriter)
  | [ Info: - ts_1d_average (NetCDFWriter)
  | [ Info: - ta_1d_average (NetCDFWriter)
  | [ Info: - thetaa_1d_average (NetCDFWriter)
  | [ Info: - ha_1d_average (NetCDFWriter)
  | [ Info: - pfull_1d_average (NetCDFWriter)
  | [ Info: - rhoa_1d_average (NetCDFWriter)
  | [ Info: - ua_1d_average (NetCDFWriter)
  | [ Info: - va_1d_average (NetCDFWriter)
  | [ Info: - wa_1d_average (NetCDFWriter)
  | [ Info: - hfes_1d_average (NetCDFWriter)
  | [ Info: - ts_1d_max (NetCDFWriter)
  | [ Info: - ts_1d_min (NetCDFWriter)
  | [ Info: - hur_1d_average (NetCDFWriter)
  | [ Info: - hus_1d_average (NetCDFWriter)
  | [ Info: - clw_1d_average (NetCDFWriter)
  | [ Info: - cli_1d_average (NetCDFWriter)
  | [ Info: - hussfc_1d_average (NetCDFWriter)
  | [ Info: - evspsbl_1d_average (NetCDFWriter)
  | [ Info: - pr_1d_average (NetCDFWriter)
  | [ Info: - rsd_1d_average (NetCDFWriter)
  | [ Info: - rsu_1d_average (NetCDFWriter)
  | [ Info: - rld_1d_average (NetCDFWriter)
  | [ Info: - rlu_1d_average (NetCDFWriter)
  | [ Info: - rsdcs_1d_average (NetCDFWriter)
  | [ Info: - rsucs_1d_average (NetCDFWriter)
  | [ Info: - rldcs_1d_average (NetCDFWriter)
  | [ Info: - rlucs_1d_average (NetCDFWriter)
```

@Sbozzolo, can you silence these if they're added one variable at a time?

**Comment by Sbozzolo** [comment]
The fact that the output is produced twice is a mistake (that I am fixing in https://github.com/CliMA/ClimaAtmos.jl/pull/2516). I would like to have the list of diagnostics that are registered: it helps a lot when debugging any problem related to diagnostics not produced correctly (the first question is always, was the diagnostic correctly added?). Moreover, given that the diagnostics are obtained from a combination of default ones and parsing YAML, I thought it would be useful for the user too to know what is being calculated.

I thought that adding ~ 30 lines to the log wouldn't be considered bloat, and I chose that as opposed to having everything on one line, which is ugly and harder to visually parse. 

I am open to suggestions to reduce the length, but I find this list very useful.

**Comment by charleskawczynski** [comment]
Ah, ok, maybe that's not quite so bad. Is this logging format going to scale, though? I imagine that the log could get really full as we add more diagnostics

**Comment by simonbyrne** [comment]
If you don't want to typically print it, use `@debug`: this can then be switched on and off via `JULIA_DEBUG`

**Comment by Sbozzolo** [comment]
> If you don't want to typically print it, use `@debug`: this can then be switched on and off via `JULIA_DEBUG`

I do want to typically print it in our automated runs. This allows me to check if the diagnostic was correctly registered when someone reports something wrong with a diagnostic in one of their runs. Having to rerun the thing would defy part of the purpose. 

> Ah, ok, maybe that's not quite so bad. Is this logging format going to scale, though? I imagine that the log could get really full as we add more diagnostics

Yes, I thought about that, and I initially postponed the problem. However, looking at the most complex EDMF cases, it is clear that it is best to tackle this now. I will open a PR soon to reduce the number of lines by grouping the diagnostics.
