### ISSUE TITLE
Baroclinic wave initial conditions

### ISSUE THREAD

**Issue by LenkaNovak** [CliMA/ClimaAtmos.jl#256]
File: `test/test_cases/run_3d_baroclinic_wave.jl`

Problem: 
- winds have excessive values (order of 1e7) leading to negative internal energy and temperate upon initialization. 

Minimal example:

```
using ClimaCore.Fields
using ClimaCorePlots

@unpack ρ, uh, w, ρe_tot = init_3d_baroclinic_wave(FT, params)
Y = simulation.integrator.u

space = axes(Y.base.uh)
local_geometry = Fields.local_geometry_field(space)

uh_init = uh.(local_geometry)
e_init = ρe_tot.(local_geometry)

plot(uh_init.components.data.:1,level=1)
plot(e_init,level=1)
```

**Comment by LenkaNovak** [comment]
Wind are values reasonable when transformed properly to UVW, i.e. :

```
uh_init = Geometry.UVWVector.( uh.(local_geometry) )
plot(uh_init.components.data.:1,level=1)
```

but still getting negative total energy and temperatures.

**Comment by jiahe23** [comment]
@LenkaNovak  If I understand correctly, this is no longer a problem. Can we close it?
