### ISSUE TITLE
Remove `Float32` to `Float64` conversions in `RRTMGP Interface`

### ISSUE THREAD

**Issue by sriharshakandala** [CliMA/ClimaAtmos.jl#2635]
Remove `Float32` to `Float64` conversions and back in `RRTMGP Interface`
This lets us utilize faster `RRTMGP` single precision calculations for `Float32` runs. 
Preliminary `RRTMGP.jl` timing tests indicate about 27% reduction in time vs the `Float64` runs.
There could be additional savings from eliminating conversions

**Comment by sriharshakandala** [comment]
cc: @nefrathenrici @charleskawczynski

**Comment by charleskawczynski** [comment]
Unfortunately, a bunch of simulations are not stable at Float32: https://buildkite.com/clima/climaatmos-ci/builds/16548.

**Comment by sriharshakandala** [comment]
> https://buildkite.com/clima/climaatmos-ci/builds/16548

The problem seems to be with saturation adjustment! Is it possible to tune the tolerances for single precision?  It may not make sense to use higher precision just for the radiation component.

cc: @akshaysridhar , @szy21

**Comment by szy21** [comment]
The real problem is that the simulations are not stable, not saturation adjustment (the input to SA is wrong). If you are sure the single precision change is correct, you can try reducing dt for the unstable jobs. `gpu_aquaplanet_dyamond` seems to break immediately, so it would be good to double check if the change is done correctly.

**Comment by szy21** [comment]
Ok, try reducing dt a bit then. I would be surprised if some small change in radiation results in instability though, so let's double check if you need to reduce dt a lot to make it stable.

**Comment by charleskawczynski** [comment]
> `gpu_aquaplanet_dyamond` seems to break immediately, so it would be good to double check if the change is done correctly.

I noticed that too. It's a bit curious. But, as you noted, thermodynamics is already running / working in Float32, so I'm wondering if we're somehow exercising RRTMGP in ways that are not exercised in RRTMGP.jl's test suite.

**Comment by szy21** [comment]
Actually, `single_column_radiative_equilibrium_allsky_idealized_clouds` is unstable too. The plots are empty, so it probably finished with all NaNs. This is a bit concerning. It seems to me the clear-sky radiation is fine, so maybe there is some issue with the all-sky radiation.

**Comment by LenkaNovak** [comment]
We recently noticed in the coupler that after the CA v0.20 our coarse simulations are less stable as well, especially those with allsky radiation (we thought it was a function in TD that changed, but then tested that wasn't it).

**Comment by szy21** [comment]
> We recently noticed in the coupler that after the CA v0.20 our coarse simulations are less stable as well, especially those with allsky radiation (we thought it was a function in TD that changed, but then tested that wasn't it).

That is probably because we change from 0 or 1 cloud fraction to partial cloud fraction.

**Comment by LenkaNovak** [comment]
> > We recently noticed in the coupler that after the CA v0.20 our coarse simulations are less stable as well, especially those with allsky radiation (we thought it was a function in TD that changed, but then tested that wasn't it).
> 
> That is probably because we change from 0 or 1 cloud fraction to partial cloud fraction.

Why would this lead to less stable sims though? 🤔

**Comment by szy21** [comment]
> > > We recently noticed in the coupler that after the CA v0.20 our coarse simulations are less stable as well, especially those with allsky radiation (we thought it was a function in TD that changed, but then tested that wasn't it).
> > 
> > 
> > That is probably because we change from 0 or 1 cloud fraction to partial cloud fraction.
> 
> Why would this lead to less stable sims though? 🤔

Not really, just this will result in significant change in the results:) You can test it by setting `cloud_model: "grid_scale"`

**Comment by szy21** [comment]
Actually this reminds me that I should change the `gpu_aquaplanet_dyamond` to `cloud_model: "grid_scale"`. I will do that after we sort out the instability issue.

**Comment by LenkaNovak** [comment]
> > > > We recently noticed in the coupler that after the CA v0.20 our coarse simulations are less stable as well, especially those with allsky radiation (we thought it was a function in TD that changed, but then tested that wasn't it).
> > > 
> > > 
> > > That is probably because we change from 0 or 1 cloud fraction to partial cloud fraction.
> > 
> > 
> > Why would this lead to less stable sims though? 🤔
> 
> Not really, just this will result in significant change in the results:) You can test it by setting `cloud_model: "grid_scale"`

`could_model: "grid_scale"` doesn't fix our [coupler issue](https://buildkite.com/clima/climacoupler-ci/builds/2579#018d862d-f02e-4a6d-9329-666e0ca5c07b) unfortunately. For now, we're resorting gray radiation (since this only breaks for the coarse setups in our tests), but it would be good to understand this more. Did anything else (that's not reverted by `could_model: "grid_scale"`) change in radiation recently?

**Comment by szy21** [comment]
> `could_model: "grid_scale"` doesn't fix our [coupler issue](https://buildkite.com/clima/climacoupler-ci/builds/2579#018d862d-f02e-4a6d-9329-666e0ca5c07b) unfortunately. For now, we're resorting gray radiation (since this only breaks for the coarse setups in our tests), but it would be good to understand this more. Did anything else (that's not reverted by `could_model: "grid_scale"`) change in radiation recently?

Nothing else should have physical changes, but the recent refactor of rrtmgp results in numerical changes (all atmos ci and longrun passed though).

(Also this issue/PR should not affect you, as we are still using Float64 for radiation in the latest atmos release, in case that's confusing)

**Comment by szy21** [comment]
> > `could_model: "grid_scale"` doesn't fix our [coupler issue](https://buildkite.com/clima/climacoupler-ci/builds/2579#018d862d-f02e-4a6d-9329-666e0ca5c07b) unfortunately. For now, we're resorting gray radiation (since this only breaks for the coarse setups in our tests), but it would be good to understand this more. Did anything else (that's not reverted by `could_model: "grid_scale"`) change in radiation recently?
> 
> Nothing else should have physical changes, but the recent refactor of rrtmgp results in numerical changes (all atmos ci and longrun passed though).
> 
> (Also this issue/PR should not affect you, as we are still using Float64 for radiation in the latest atmos release, in case that's confusing)

We haven't tested coarse resolution amip run for more than 1 day though, as that's not our focus, so it could be the atmos one is not stable as well.

**Comment by szy21** [comment]
It seems there are some edge case in sw fluxes that are wrong with Float32. When I run `single_column_radiative_equilibrium_allsky_idealized_clouds` locally the simulation breaks, even with smaller timesteps. When using `dt: 1hours` before the simulation breaks I got
```
julia> println(p.radiation.radiation_model.face_sw_flux_dn)
Float32[2.7108308f-5; 2.7150347f-5; 2.7194521f-5; 2.7240849f-5; 2.7289268f-5; 2.733982f-5; 2.7392463f-5; 2.7447206f-5; 2.7504057f-5; 2.7637554f-5; 2.77772f-5; 2.792324f-5; 2.798731f-5; 2.8057842f-5; 2.8154462f-5; 2.837723f-5; 2.9263036f-5; 3.356648f-5; 5.5360433f-5; 0.00016651116; 0.0007300283; 0.0035406176; 0.017336491; 0.083236575; 0.39228332; 1.7929803; 7.8860397; 33.06356; 132.20605; 502.51562; 1807.0975; 6251.8945; 20902.334; 67322.93; 208511.67; 619586.5; 1.7654548f6; 4.8118575f6; 1.2521805f7; 3.0897436f7; 7.197809f7; 1.5806795f8; 3.2711245f8; 6.377673f8; 1.1709271f9; 2.0267587f9; 3.3109914f9; 5.117658f9; 7.5839145f9; 1.0778556f10; 1.4669485f10; 1.9129876f10; 2.4023435f10; 2.7530187f10; 3.085804f10; 3.390368f10; 3.6586762f10; 3.888266f10; 4.078141f10; 4.2311033f10; 4.351357f10; 4.4426895f10; 4.5095916f10; 4.556693f10; 4.588413f10; 4.6085464f10; 4.620472f10; 4.626888f10; 4.6299476f10; 4.6311473f10; 4.631403f10;;]

julia> p.radiation.radiation_model.face_sw_flux_dn
71×1 view(::Matrix{Float32}, 1:71, :) with eltype Float32:
 2.7108308f-5
 2.7150347f-5
 2.7194521f-5
 2.7240849f-5
 2.7289268f-5
 2.733982f-5
 2.7392463f-5
 ⋮
 4.6085464f10
 4.620472f10
 4.626888f10
 4.6299476f10
 4.6311473f10
 4.631403f10

julia> p.radiation.radiation_model.face_sw_flux_up
71×1 view(::Matrix{Float32}, 1:71, :) with eltype Float32:
      1.0301155f-5
      1.0301945f-5
      1.030292f-5
      1.0304107f-5
      1.0305519f-5
      1.03071725f-5
      1.0309083f-5
      ⋮
 388453.97
 401662.0
 412144.22
 419960.9
 425306.47
      2.2088827f18
``` 
So something is clearly wrong. Maybe it has something to do with some threshold in RRTMGP? @sriharshakandala any idea?

**Comment by szy21** [comment]
Maybe @tapios knows if any threshold in RRTMGP could lead to errors in SW fluxes?

**Comment by szy21** [comment]
Ok, I don't think it has anything to do with clear-sky or all-sky. When I run single column clear-sky locally with time-varying insolation with Float32 it breaks too. It seems to me it has something to do with errors in SW fluxes when zenith angle is large. Float32 leads to very wrong SW fluxes. (When zenith angle is larger than 90 degree, cos_zenith_angle is `7.54979f-8` for Float32 and `2.83276944882399e-16` for Floa64, from the limit above, if that helps.)

**Comment by tapios** [comment]
Don't we have some catch that when `abs(SZA) > pi/2`, `cos(SZA) = 0`? If not, let's add it.

**Comment by tapios** [comment]
We should add a conditional [here](https://github.com/CliMA/RRTMGP.jl/blob/1b37f6673d2490dd523a435cc374da3485157713/src/rte/shortwave2stream.jl#L337) to make sure all fluxes are zero when `zenith_angle > pi/2`. 

I am concerned that with our current `+eps` construct, we run into problems for fluxes such as [here](https://github.com/CliMA/RRTMGP.jl/blob/1b37f6673d2490dd523a435cc374da3485157713/src/rte/shortwave2stream.jl#L338), where we have an exponential `exp(-τ_sum / μ₀)` that leads to wrong evaluations at `float32`.

This may not be the only problem, but it could be one problem.

**Comment by szy21** [comment]
@tapios Thank you! I did a quick hack in ClimaAtmos to set all SW fluxes to zero when zenith angle is large and that seems to solve the problem: see https://github.com/CliMA/ClimaAtmos.jl/pull/2666/commits/9679498c0dc221555c2216a662a733e8320cdbf1 (The hard-coded numbers are to match our current -eps threshold). I haven't figured out which lines in RRTMGP cause the issue (`exp(-τ_sum / μ₀)` seems fine), but @sriharshakandala let's add this to RRTMGP?

**Comment by szy21** [comment]
Also this doesn't show up in RRTMGP test cases. I think we have test cases with large zenith angle, but maybe the problem is caused by some combination of optical depth and zenith angle. Is there a way to test it in RRTMGP so we won't have similar issues in the future? Maybe we can add a radiative equilibrium case as that will cover a lot more scenarios than the standalone RRTMGP test?

**Comment by sriharshakandala** [comment]
> Also this doesn't show up in RRTMGP test cases. I think we have test cases with large zenith angle, but maybe the problem is caused by some combination of optical depth and zenith angle. Is there a way to test it in RRTMGP so we won't have similar issues in the future? Maybe we can add these edge cases we found in climaatmos to rrtmgp test cases?

In `RRTMGP`, it is handled upstream  in the tests, e.g. here: https://github.com/CliMA/RRTMGP.jl/blob/main/test/read_rfmip_clear_sky.jl#L38

**Comment by szy21** [comment]
It might be [this](https://github.com/CliMA/RRTMGP.jl/blob/1b37f6673d2490dd523a435cc374da3485157713/src/rte/shortwave2stream.jl#L354) line. I wonder besides setting SW fluxes to zero, should we add a minimum value for the denominator `(FT(1) - Rdif * albedo_ilev)`?

**Comment by szy21** [comment]
I did some more tests on this. With Float32 there are issues even with `cos_zenith = 1.2e-4`, which corresponds to cos(pi/2 - 100*eps(FT)). There seem to be no issues with `cos_zenith = 3.5e-4`, which corresponds to cos(pi/2 - sqrt(eps(FT))). So we may need to set SW fluxes to zero when zenith angle is larger than `pi/2 - sqrt(eps(FT))`. Right now `pi/2 - eps(FT)` works because we use a single column and call radiation every hour so we don't get a zenith angle that is smaller but very close to pi/2. But we may get it on the sphere when calling radiation more frequently?  I think it would be good to figure out what the issue is. Or are we ok with `pi/2 - sqrt(eps(FT))`? @tapios @sriharshakandala What do you think?

**Comment by szy21** [comment]
> I'm fine with having `pi/2 - sqrt(eps(FT))` as the limit, but it would be nice to trace down where the problem occurs. Can you do it in the REPL, e.g., assuming zero SW opacity? Or is it dependent on SW optical depth?

It is dependent on SW optical depth, as for the same zenith angle sometimes it breaks and sometimes it doesn't. I will see if I can try modifying the SW optical properties.

**Comment by szy21** [comment]
We found that it's because [this](https://github.com/CliMA/RRTMGP.jl/blob/1b37f6673d2490dd523a435cc374da3485157713/src/rte/shortwave2stream.jl#L360) line can be negative with Float32. Limiting it to zero works fine in standalone RRTMGP cases. We will test ClimaAtmos with this fix in RRTMGP.

**Comment by sriharshakandala** [comment]
> We found that it's because [this](https://github.com/CliMA/RRTMGP.jl/blob/1b37f6673d2490dd523a435cc374da3485157713/src/rte/shortwave2stream.jl#L360) line can be negative with both Float32 and Float64, but it's small enough and didn't cause issues with Float64. Limiting it to zero works fine in standalone RRTMGP cases. We will test ClimaAtmos with this fix in RRTMGP.

Thanks @szy21 . I just added this change in PR https://github.com/CliMA/RRTMGP.jl/pull/448
