### ISSUE TITLE
Add mass, water and energy conservation tests

### ISSUE THREAD

**Issue by trontrytel** [CliMA/ClimaAtmos.jl#2658]

**Comment by szy21** [comment]
See also #2568. Let's keep only one issue?

**Comment by trontrytel** [comment]
> See also #2568. Let's keep only one issue?

Could we split #2568 into smaller tasks?

**Comment by szy21** [comment]
Sure, feel free to split it in whatever way. Just want to make sure we don't duplicate the work. #2556 is also related and we can combine it too.

**Comment by szy21** [comment]
merged with #2568
