### ISSUE TITLE
Export final yaml file to output folder

### ISSUE THREAD

**Issue by charleskawczynski** [CliMA/ClimaAtmos.jl#2659]
Similar to exporting the parameters toml file to the output folder, it might be nice if we export the final (used) yaml file to the output folder.

What do you think @Sbozzolo, @nefrathenrici, @juliasloan25 ?

**Comment by nefrathenrici** [comment]
I think this would be helpful. The main consideration I have is cluttering up the output, but we are already outputting far fewer diagnostic files than before.

**Comment by Sbozzolo** [comment]
I was thinking about this last week. We should have some metadata files. Those files should contain, among the other things, everything that is needed to reproduce the run (so, the used yaml too). 

So, yes, maybe we can start by adding the yaml file.

**Comment by charleskawczynski** [comment]
@nefrathenrici, would you mind taking this on?

**Comment by nefrathenrici** [comment]
@charleskawczynski Sure!

**Comment by Sbozzolo** [comment]
Have you verified that the generated yaml files can be used to reproduce the run?
