### ISSUE TITLE
Regression function-based surface albedo parameterization (broadband)

### ISSUE THREAD

**Issue by LenkaNovak** [CliMA/ClimaAtmos.jl#2677]
Following Jin et al., 2011, as required in issue https://github.com/CliMA/ClimaCoupler.jl/issues/577

# Components
- [x] add functions
- [x] implement unit test
- [x] compare with Jin et al 2011 
- [x] integrate in driver
- [x] test for other types of radiation
- [x] docs
- [x] clean up

# Notes
- long runs are non-deterministic (expected due to the random seed), but in some cases they can lead to failing conservation errors (e.g. compare [this build](https://buildkite.com/clima/climaatmos-longruns/builds/1431#018dafe7-66a0-4bef-8901-1c0a357f9d9b) v  [this build](https://buildkite.com/clima/climaatmos-longruns/builds/1432#018db066-a41e-40bc-83e0-27adea0abe3d)

# QA
## Long runs
- [x] high res slab ocean aquaplanet with `RegressionFunctionAlbedo` passes [build](https://buildkite.com/clima/climaatmos-longruns/builds/1432#018db066-a418-45ff-847b-3502df639135)

### Direct
<img width="537" alt="Screen Shot 2024-02-14 at 4 52 50 PM" src="https://github.com/CliMA/ClimaAtmos.jl/assets/38083334/9ce450d8-cb4f-4931-a152-ea479421c2e3">

w=0 (note for latitude of 90deg this doesn't quite converge to 1 due to the accuracy of the coefficients provided in the paper, but this is currently sufficient for our purposes):
![Screen Shot 2024-02-14 at 4 54 34 PM](https://github.com/CliMA/ClimaAtmos.jl/assets/38083334/27daf30b-0067-4253-864d-78a8de183a74)

### Diffuse

<img width="426" alt="Screen Shot 2024-02-14 at 4 52 43 PM" src="https://github.com/CliMA/ClimaAtmos.jl/assets/38083334/3e842394-9e13-42d7-930e-0c1597d48f05">

![Screen Shot 2024-02-14 at 4 54 45 PM](https://github.com/CliMA/ClimaAtmos.jl/assets/38083334/53c3c2c9-74b3-4422-8fc2-d8b7656bb0ec)

### slabplanet after 20d
direct:
<img width="596" alt="Screen Shot 2024-02-15 at 7 33 37 AM" src="https://github.com/CliMA/ClimaAtmos.jl/assets/38083334/cdacf42b-b01e-4fc1-92aa-cebf7f5edc60">

diffuse:
![Image](https://github.com/CliMA/ClimaAtmos.jl/assets/38083334/a70c9052-7f8f-47dc-870a-2bd554cd13c2)

**Comment by szy21** [comment]
30-100 day average albedo in the longrun. The values are a bit too high compared with observations, but the spatial pattern looks pretty good! We can just calibrate the parameters later.
![image](https://github.com/CliMA/ClimaAtmos.jl/assets/11598433/94f0525f-49dd-4fc2-bd63-721be6ee815d)

**Comment by LenkaNovak** [comment]
> 30-100 day average albedo in the longrun. The values are a bit too high compared with observations, but the spatial pattern looks pretty good! We can just calibrate the parameters later. ![image](https://private-user-images.githubusercontent.com/11598433/306523323-cf54a115-6ec0-421e-be95-b659b8e76e70.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1NDQ2NTcsIm5iZiI6MTcwODU0NDM1NywicGF0aCI6Ii8xMTU5ODQzMy8zMDY1MjMzMjMtY2Y1NGExMTUtNmVjMC00MjFlLWJlOTUtYjY1OWI4ZTc2ZTcwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIxVDE5MzkxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkMDU2ZjMxYjhkZjdhZDk0MWI4NzYyZWQ2OTk3NzQ5NzUwNWJkMGZhMWY2ZjM1ZWI4MmE2MjRjNmFkYTM4M2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.P7SdkZAGRzUiZW53oEPwuazCGUsc0WHYuh3zUSaM9IU)

Nice, thanks for checking! Is this the diffuse component btw?

**Comment by szy21** [comment]
This is the combined albedo (defined as sw flux up / sw flux down). We don't save direct and diffusive fluxes separately in RRTMGP anymore, but can separate them if needed for debugging.

**Comment by LenkaNovak** [comment]
That's good to know, thank you!
