### ISSUE TITLE
Regression function-based albedo as a function of wavelength

### ISSUE THREAD

**Issue by LenkaNovak** [CliMA/ClimaAtmos.jl#2687]
We want to extend the broadband albedo of #2677 to be spectral (relative refractive index as a function of wavelength)

**Comment by szy21** [comment]
70-day averaged albedo for n=1.34:
![image](https://github.com/CliMA/ClimaAtmos.jl/assets/11598433/5b400e96-35f0-44ea-a66c-049ca4ce6074)

n=1.20:
![image](https://github.com/CliMA/ClimaAtmos.jl/assets/11598433/7da4294d-0392-4de3-b950-17b0eed0fb6d)
