### ISSUE TITLE
Update divergence damping in topography longrun

### ISSUE THREAD

**Issue by szy21** [CliMA/ClimaAtmos.jl#2720]
@akshaysridhar What is the latest stable configuration for divergence damping for the topography runs? If it is stable, could we update the longrun configuration?

**Comment by akshaysridhar** [comment]
The updated configurations are being tested against v20.1 in the GPU pipelines [here](https://buildkite.com/clima/climaatmos-gpulongruns/builds/49). Passing versions will be added to the longrun-gpu pipelines.
