### ISSUE TITLE
Fix aquaplanet 0M longrun

### ISSUE THREAD

**Issue by szy21** [CliMA/ClimaAtmos.jl#2752]
`longrun_aquaplanet_rhoe_equil_55km_nz63_clearsky_0M` is breaking in the latest [build](https://buildkite.com/clima/climaatmos-gpulongruns/builds/65#018dfdc0-86e4-444a-90e3-90e32049029e).

**Comment by szy21** [comment]
@akshaysridhar @trontrytel

**Comment by trontrytel** [comment]
`ρ=2.424961` thats dense

**Comment by szy21** [comment]
`e_int=-5425040` it's very cold 🤷

**Comment by szy21** [comment]
I'm not sure if the recent radiation fix in ClimaAtmos fixes everything. I'll try this run with Float64 (which will alleviate radiation problems, if there are any).

**Comment by szy21** [comment]
Float64 runs for longer (80days), but still breaks: https://buildkite.com/clima/climaatmos-gpulongruns/builds/67#018e0af1-02fb-4b95-ac9b-ab22fa034176

**Comment by szy21** [comment]
It runs for 300 days if I reduce dt from 150secs to 120secs: https://buildkite.com/clima/climaatmos-gpulongruns/builds/68#018e0baa-02cb-4435-9607-ad1cd272fe45. It's probably not worth the time to investigate it before we finalize the numerics for moist simulations. I'll just reduce dt for this run.

**Comment by akshaysridhar** [comment]
We have this [older build](https://buildkite.com/clima/climaatmos-longruns/builds/1304#018c9543-6827-4859-994e-e362db767c25) for reference.
