### ISSUE TITLE
Freeing NCDatasets increases allocations for GPU test

### ISSUE THREAD

**Issue by nefrathenrici** [CliMA/ClimaAtmos.jl#2785]
Unpinning NCDatasets from 0.14.1 increases allocations by ~25% for this job: `julia --color=yes --project=perf perf/flame.jl config/perf_configs/flame_gpu_implicit_barowave_moist.yml`

See failing test [here](https://buildkite.com/clima/climaatmos-ci/builds/17408#018e3879-4255-4da1-9e9b-cd713f8ee12a).

I am not sure if this worth unpinning NCDatasets, since this will impact GPU performance.

**Comment by Sbozzolo** [comment]
Can you try again with the new version of Adapt? We need to unpin NCDatasets at some point. 0.14.2 comes with the binary that is MPI-compatible.

**Comment by nefrathenrici** [comment]
Seems to work with 0.14.3! https://buildkite.com/clima/climaatmos-ci/builds/17724
