### ISSUE TITLE
Make prognostic edmf implicit solver work on GPU

### ISSUE THREAD

**Issue by szy21** [CliMA/ClimaAtmos.jl#2826]
Error here: https://buildkite.com/clima/climaatmos-ci/builds/17751#018e648e-ef08-4506-924b-f8b716349ef9/196-282

**Comment by charleskawczynski** [comment]
Can we add this job to CI with soft fail? This would be really helpful

**Comment by szy21** [comment]
Yes, I can do that later today.

**Comment by szy21** [comment]
@charleskawczynski do you want to keep your change in https://github.com/CliMA/ClimaAtmos.jl/pull/2825, or just add the job?

**Comment by charleskawczynski** [comment]
We can remove my change, I think it wasn’t working for some reason. Thank you!

**Comment by charleskawczynski** [comment]
Closed by #2926
