### ISSUE TITLE
can't use `~` when specifying toml path in yml file

### ISSUE THREAD

**Issue by haakon-e** [CliMA/ClimaAtmos.jl#2896]
If you take, say, `ClimaAtmos.jl/config/model_configs/prognostic_edmfx_bomex_column.yml`
and modify the toml entry (`toml: [toml/prognostic_edmfx_bomex.toml]`) to something like
`toml: [~/Documents/CliMA/ClimaAtmos.jl/toml/prognostic_edmfx_bomex.toml]`
(where `ClimaAtmos.jl` actually lives in `~/Documents/CliMA`)

it seems like I get this error:

```julia
julia> config = CA.AtmosConfig(config_dict)
ERROR: "~/Documents/CliMA/ClimaAtmos.jl/toml/prognostic_edmfx_bomex.toml": No such file
Stacktrace:
     ⋮ internal @ Base, TOML, ClimaParams, Unknown
 [5] merge_toml_files(filepaths::Vector{Any})
   @ ClimaParams ~/.julia/packages/ClimaParams/ZE2tQ/src/file_parsing.jl:264
 [6] ClimaAtmos.AtmosConfig(config::Dict{Any, Any}; comms_ctx::Nothing)
   @ ClimaAtmos ~/Documents/CliMA/ClimaAtmos.jl/src/solver/types.jl:501
 [7] ClimaAtmos.AtmosConfig(config::Dict{Any, Any})
   @ ClimaAtmos ~/Documents/CliMA/ClimaAtmos.jl/src/solver/types.jl:498
Use `err` to retrieve the full stack trace.
```

related to #2167

**Comment by haakon-e** [comment]
The same seems to be true when trying to load the yaml file itself, e.g.:

```julia
julia> config_dict = YAML.load_file("~/Documents/CliMA/ClimaAtmos.jl/config/model_configs/prognostic_edmfx_bomex_column.yml");
ERROR: SystemError: opening file "~/Documents/CliMA/ClimaAtmos.jl/config/model_configs/prognostic_edmfx_bomex_column.yml": No such file or directory
Stacktrace:
      ⋮ internal @ Base, Unknown
  [9] load_file(::String)
    @ YAML ~/.julia/packages/YAML/U6OOW/src/YAML.jl:94
Use `err` to retrieve the full stack trace.
```

but I guess that's a different issue.

**Comment by haakon-e** [comment]
Opened https://github.com/JuliaData/YAML.jl/issues/137 for the YAML issue.

ah I see this is actually technically `TOML`'s fault (from ClimaParams): `toml_data = TOML.parsefile(filepath)`

**Comment by Sbozzolo** [comment]
I will close this given that it is an upstream issue. Feel free to reopen for any reason.
