### ISSUE TITLE
Quantify fluctuations in benchmarks on clima

### ISSUE THREAD

**Issue by Sbozzolo** [CliMA/ClimaAtmos.jl#2914]
It has been reported that the measure for SYPD for jobs on Clima fluctuates. How large are the fluctuations? What are the possible causes?

**Comment by nefrathenrici** [comment]
I believe this was originally opened to track the super-linear scaling we saw on the GPU server, this behavior has stopped.

For initial tests between jobs in the same build, I ran the same scaling jobs twice and compared their percent difference. I ran this build 4x in total.
Max percentage diff in SYPD between jobs with the same resources:

[Build 1](https://buildkite.com/clima/climaatmos-target-gpu-simulations/builds/322#0190b8c2-c90a-4635-bc60-0bc4028fc044):  0.13%
[Build 2](https://buildkite.com/clima/climaatmos-target-gpu-simulations/builds/320#0190b7fd-0cfa-4612-b0f7-1dc0ff3bdab3): 0.25%
[Build 3](https://buildkite.com/clima/climaatmos-target-gpu-simulations/builds/319#0190b7c7-ef6f-43c4-8c59-2d20e1838a95): 2.8%. This is the largest SYPD fluctuation between all jobs as well. 
[Build 4](https://buildkite.com/clima/climaatmos-target-gpu-simulations/builds/318#0190b7aa-abad-47de-be76-b8b91784a5f2): 0.43%

With a maximum SYPD change of 2.8%, I think we can be confident in the consistency of the scaling pipeline until we want to run more comprehensive benchmarks.
