### ISSUE TITLE
Move WallTimeEstimte to ClimaUtilities

### ISSUE THREAD

**Issue by Sbozzolo** [CliMA/ClimaAtmos.jl#2935]
The `WallTimeEstimate` progress log is very nice and useful. I think it would be good to standardize it across the Clima packages. For example, I already would like to have it in ClimaLand as we are moving to more complex global runs.

In this, I think the progress bar can be extended to (maybe optionally) print:
- current memory used
- current memory used on the GPU (if applicable)

It would also be nice if the printout didn't cointain the full date but only the time for the estimated time of completion when it is the same day as when the simulation is run (it is harder to visually parse).

@charleskawczynski thoughts?

**Comment by charleskawczynski** [comment]
I’m open to moving it out to ClimaUtilities, and adding memory used

I do like having the full date, however, because we don’t know when the log is printed (I realized this after the first iteration). And it’s not printed frequently for long runs.

**Comment by charleskawczynski** [comment]
Maybe we can improve some names, too. Like WallTimeSinceLastCallback

**Comment by Sbozzolo** [comment]
> I do like having the full date, however, because we don’t know when the log is printed (I realized this after the first iteration). And it’s not printed frequently for long runs.

It makes sense. My commented stemmed mostly for interactive use: it always takes me multiple seconds to find the estimated finish time and parse it. Right now, it looks like:
```
└   estimated_finish_date = 2024-04-19T22:03:28.667
```
And the relevant information for interactive use most of the time is just `22:03`

**Comment by charleskawczynski** [comment]
Ah, I see, I’m happy to parse it into something more human readable (and ditch the seconds)
