### ISSUE TITLE
Off-by-one in WallTimeEstimate

### ISSUE THREAD

**Issue by Sbozzolo** [CliMA/ClimaAtmos.jl#2992]
This is a tiny detail, but it looks like that the `WallTimeEstimate` is off by one step:
```julia
julia> import ClimaAtmos as CA
julia> import SciMLBase
julia> simulation = CA.get_simulation(CA.AtmosConfig())
julia> SciMLBase.step!(simulation.integrator)
# nothing is printed

julia> SciMLBase.step!(simulation.integrator);
[ Info: Progress: Completed first step
```

**Comment by charleskawczynski** [comment]
IIRC, timings aren't reported (or even computed) for the very first step due to compilation (in order to disallow compilation time from contaminating timings).

**Comment by Sbozzolo** [comment]
From a user-experience point of view, the message is a little confusing: it says that we completed the first step even when we completed the second.

**Comment by charleskawczynski** [comment]
Agreed. Frankly, it's hard to design a progress-reporting function in the form of a callback, that doesn't have footguns and can potentially result in misreported numbers. I think a better solution would be to (re-)implement this in the timestepper, as we'll have proper access to what we need in scope. Also, then other repos can use it. I'll open an issue there.
