### ISSUE TITLE
Some diagnostics with topography fail on GPU

### ISSUE THREAD

**Issue by szy21** [CliMA/ClimaAtmos.jl#3005]
See the error [here](https://buildkite.com/clima/climaatmos-gpulongruns/builds/149#018f6606-c1ad-4282-aa3b-ce2c765bdd55/151-410) for example. @Sbozzolo @akshaysridhar Could you take a look?

**Comment by Sbozzolo** [comment]
Fixed in https://github.com/CliMA/ClimaDiagnostics.jl/pull/24
