### ISSUE TITLE
Benchmark GPU jobs occasionally time out

### ISSUE THREAD

**Issue by Sbozzolo** [CliMA/ClimaAtmos.jl#3034]
As in:

https://buildkite.com/clima/climaatmos-ci/builds/18919
https://buildkite.com/clima/climaatmos-ci/builds/18898
https://buildkite.com/clima/climaatmos-ci/builds/18921

**Comment by trontrytel** [comment]
I got hit by that one here: https://github.com/CliMA/ClimaAtmos.jl/pull/3033, https://buildkite.com/clima/climaatmos-ci/builds/18950

Can we remove this job from the GPU CI?

**Comment by charleskawczynski** [comment]
Should be closed by #3039. Let's reopen if it happens again.

**Comment by Sbozzolo** [comment]
Found another instance here:
https://buildkite.com/clima/climaatmos-ci/builds/18988#018fa913-8dd9-4c6e-bb0f-e96930f829a1

**Comment by Sbozzolo** [comment]
I haven't seen this in two weeks, so I think the problem is either solved or very low occurance rate. In either cases, we can close this.
