### ISSUE TITLE
Re-introduce `OutputPathGenerator`

### ISSUE THREAD

**Issue by Sbozzolo** [CliMA/ClimaAtmos.jl#3048]
As reported by @charleskawczynski and @trontrytel in https://github.com/CliMA/ClimaDiagnostics.jl/issues/56
and by @akshaysridhar in https://github.com/CliMA/ClimaDiagnostics.jl/issues/55

> I don't have a reproducer for this, so I'm not sure what causes this issue, but here is an error I ran into with @trontrytel

> ERROR: LoadError: incompatible dimensions for orog
Stacktrace:
  [1] error(s::String)
    @ Base .\error.jl:35
  [2] write_field!(writer::ClimaDiagnostics.Writers.NetCDFWriter{…}, field::ClimaCore.Fields.Field{…}, diagnostic::ClimaDiagnostics.ScheduledDiagnostics.ScheduledDiagnostic{…}, u::ClimaCore.Fields.FieldVector{…}, p::ClimaAtmos.AtmosCache{…}, t::Float32)
    @ ClimaDiagnostics.Writers C:\Users\kawcz\.julia\packages\ClimaDiagnostics\gzst4\src\netcdf_writer.jl:330
  [3] ClimaDiagnostics.DiagnosticsHandler(scheduled_diagnostics::Vector{…}, Y::ClimaCore.Fields.FieldVector{…}, p::ClimaAtmos.AtmosCache{…}, t::Float32; dt::Float32)
    @ ClimaDiagnostics C:\Users\kawcz\.julia\packages\ClimaDiagnostics\gzst4\src\clima_diagnostics.jl:95
  [4] DiagnosticsHandler
    @ C:\Users\kawcz\.julia\packages\ClimaDiagnostics\gzst4\src\clima_diagnostics.jl:56 [inlined]
  [5] IntegratorWithDiagnostics(integrator::ClimaTimeSteppers.DistributedODEIntegrator{…}, scheduled_diagnostics::Vector{…})
    @ ClimaDiagnostics C:\Users\kawcz\.julia\packages\ClimaDiagnostics\gzst4\src\clima_diagnostics.jl:280
  [6] macro expansion
    @ C:\dev\CliMA\ClimaAtmos.jl\src\solver\type_getters.jl:709 [inlined]
  [7] macro expansion
    @ .\timing.jl:503 [inlined]
  [8] macro expansion
    @ C:\dev\CliMA\ClimaAtmos.jl\src\utils\utilities.jl:331 [inlined]
  [9] get_simulation(config::ClimaAtmos.AtmosConfig{…})
    @ ClimaAtmos C:\dev\CliMA\ClimaAtmos.jl\src\solver\type_getters.jl:708
 [10] top-level scope
    @ C:\dev\CliMA\ClimaAtmos.jl\examples\hybrid\driver.jl:15
 [11] include(fname::String)
    @ Base.MainInclude .\client.jl:489
 [12] top-level scope
    @ REPL[3]:1
in expression starting at C:\dev\CliMA\ClimaAtmos.jl\examples\hybrid\driver.jl:15
Some type information was truncated. Use `show(err)` to see complete types.

The root issue:
> NetCDF files come with defined dimensions that you are not allowed to change. If you re-run a simulation with the same output_dir and change anything about it, you will end up with incompatible NetCDF files. This happens very frequently when developing in the REPL, so the solution was that every time a new Simulation is created, a new folder is also created. Previous folders are retained to ensure that one can still inspect the output there. This is implemented in `OutputPathGenerator`.

**Comment by charleskawczynski** [comment]
>  so the solution was that every time a new Simulation is created

This doesn't sound like an ideal good solution, since it involves recreating the integrator. Can't we make this just work? Perhaps we can add some tests to ClimaAtmos to ensure that everyone's typical workflow is supported.

**Comment by Sbozzolo** [comment]
The problem occurs only when you change the integrator, if the integrator stays the same, it means that the output will be the same.

**Comment by Sbozzolo** [comment]
Typical workflow is this:
```julia-repl
julia> import ClimaAtmos as CA
julia> simulation = CA.get_simulation(CA.AtmosConfig("my_yml_file.yml"))
julia> CA.solve_atmos!(CA)
# On no, I want to change something in the code or
julia> simulation = CA.get_simulation(CA.AtmosConfig("my_yml_file.yml"))  # This fails if you don't have OutputPathGenerator
```
