### ISSUE TITLE
zero_tendency for sgs variables doesn't work on GPU

### ISSUE THREAD

**Issue by szy21** [CliMA/ClimaAtmos.jl#3053]
[This](https://github.com/CliMA/ClimaAtmos.jl/blob/eba9f0c29cfbbee9f22f1446e536261e68861333/src/prognostic_equations/zero_tendency.jl#L30) doesn't work on GPU. See the error [here](https://buildkite.com/clima/climaatmos-gpulongruns/builds/159#018fba84-106c-465b-ac00-2dbe06248be3/151-249).

**Comment by Sbozzolo** [comment]
I think you should be able to use `fill(xxxx, 0)`

**Comment by szy21** [comment]
> I think you should be able to use `fill!(xxxx, 0)`

Thanks! I'll give it a try later.

**Comment by charleskawczynski** [comment]
This should be closed by the latest ClimaCore release please reopen if that’s not the case 🙂

**Comment by szy21** [comment]
Yes, it works now, thanks!
