### ISSUE TITLE
Moist held suarez breaks after switching to SSP and CAM_SE hyperdiffusion

### ISSUE THREAD

**Issue by szy21** [CliMA/ClimaAtmos.jl#3108]
See here: https://buildkite.com/clima/climaatmos-gpulongruns/builds/242#01902f1a-4668-41c6-b245-dfc68b13005b. @Sbozzolo Could you check if something is wrong with the setup, or if we should reduce dt?

**Comment by Sbozzolo** [comment]
I think one of the runs I had explicitely checked and it was running fine, but I might be getting confused. I am off today and I'll check this tomorrow morning. 

If you want to re-run this tonight, can you try with dt of 120 s?

**Comment by szy21** [comment]
dt=120s is running: https://buildkite.com/clima/climaatmos-gpulongruns/builds/246#0190326e-9db4-4fe6-97ed-afdfa865d7e2
