### ISSUE TITLE
Many aquaplanet simulations are broken

### ISSUE THREAD

**Issue by szy21** [CliMA/ClimaAtmos.jl#3110]
See this build: https://buildkite.com/clima/climaatmos-gpulongruns/builds/242

Recent major changes are 

- using SSP + CAM_SE (#3019)
- removing filter in radiation (#3099)
- updating to RRTMGP v0.15.0 (#3098)

Things to try

- [x] Test atmos v0.26.0 (the differences between this version and main are radiation filter and rrtmgp version): https://buildkite.com/clima/climaatmos-gpulongruns/builds/244
- [ ] Use ARS and/or ClimaHyperdiffusion
- [x] Use RRTMGP main branch which contains the clamping of tau: https://buildkite.com/clima/climaatmos-gpulongruns/builds/243
- [ ] Add back the radiation filter

**Comment by szy21** [comment]
Here is a summary.

- The topography runs (`longrun_aquaplanet_rhoe_equil_55km_nz63_clearsky_0M_earth` and `longrun_aquaplanet_rhoe_equil_55km_nz63_clearsky_0M_earth_sleve`) are broken because of the timestepper change. They were broken before too, but run for longer. Maybe we should revisit it after the topography work.
- The aquaplanet 1M (`longrun_aquaplanet_clearsky_1M`) breaks faster with the rrtmgp version update (v0.15.0).
- The latest rrtmgp version (with clamping of tau) fixes the aquaplanet 0M runs without topography (`longrun_aquaplanet_rhoe_equil_55km_nz63_clearsky_tvinsol_0M_slabocean` and `amip_target_diagedmf`).
- However, the change in timestepper breaks the conservation test in `longrun_aquaplanet_rhoe_equil_55km_nz63_clearsky_tvinsol_0M_slabocean`. There is a ~20% change in total water. We should look into it. I will open a separate issue.

**Comment by Sbozzolo** [comment]
Deep atmos passing here: https://buildkite.com/clima/climaatmos-gpulongruns/builds/248#0190363d-b25a-4199-92fc-b3150c045db9

**Comment by szy21** [comment]
I think we can close this now. The rrtmgp update has been merged, and I opened an issue for the aquaplanet conservation. Topography work will be tracked somewhere else.
