### ISSUE TITLE
O1.5.4a Prescribe aerosol concentrations

### ISSUE THREAD

**Issue by trontrytel** [CliMA/ClimaAtmos.jl#3197]
# The Climate Modeling Alliance
### Purpose

Prescribe the aerosol concentrations based on RCP 4.5 from CMIP 5. The files are here: https://tntcat.iiasa.ac.at/RcpDb/dsd?Action=htmlpage&page=download

### Benefits

- We need aerosol optical properties for radiation. (We also need to code a way to compute optical properties from aerosol concentrations, see [SDI](https://github.com/CliMA/CloudMicrophysics.jl/issues/213))
- We need aerosol precursors for cloud droplet activation and ice nucleation in 2-moment microphysics scheme. (The 2-moment scheme is under development. See [SDI](https://github.com/CliMA/CloudMicrophysics.jl/issues/218) and [SDI](https://github.com/CliMA/CloudMicrophysics.jl/issues/215))

### People

- Lead: @szy21 
- Collaborators: @Sbozzolo @sriharshakandala @trontrytel 
- Reviewers: 

### Results

Run AMIP simulations with aerosol concentrations read from files.

```[tasklist]
- [x] Add aerosol data to artifacts
- [x] [Aerosol prescribing enabled in Atmos](https://github.com/CliMA/ClimaAtmos.jl/pull/2815)
- [x] [add aerosol optics in rrtmgp](https://github.com/CliMA/RRTMGP.jl/issues/460)
- [ ] https://github.com/CliMA/ClimaAtmos.jl/issues/3140
- [ ] https://github.com/CliMA/ClimaUtilities.jl/issues/74
- [ ] https://github.com/CliMA/ClimaAtmos.jl/issues/3274
- [x] use aerosols in the AMIP simulation
- [ ] https://github.com/CliMA/RRTMGP.jl/issues/539
```

### CC
@tapios @simonbyrne @cmbengue

**Comment by Sbozzolo** [comment]
Is there anything else needed to close this issue?

**Comment by szy21** [comment]
> Is there anything else needed to close this issue?

Sea salt is not added, but let's close this. I will add sea salt after updating rrtmgp.
