### ISSUE TITLE
Incorrect looking condition in calibration model interface

### ISSUE THREAD

**Issue by charleskawczynski** [CliMA/ClimaAtmos.jl#3209]
`sol_res.sol .= NaN` in
 - https://github.com/CliMA/ClimaAtmos.jl/blob/bf25448efd0d06c7f33d62886e8cb5a4296311f8/calibration/model_interface.jl#L64
 - and https://github.com/CliMA/ClimaAtmos.jl/blob/bf25448efd0d06c7f33d62886e8cb5a4296311f8/calibration/experiments/sphere_held_suarez_rhoe_equilmoist/model_interface.jl#L49

looks incorrect (those appear to be assignments and not a condition)

**Comment by nefrathenrici** [comment]
Thanks for catching this! I will open a PR today.
