### ISSUE TITLE
julia (`pretty_table`) output to docs is not searchable

### ISSUE THREAD

**Issue by haakon-e** [CliMA/ClimaAtmos.jl#3301]
Consider the [Default Configuration](https://clima.github.io/ClimaAtmos.jl/dev/config/) doc section, which enumerates arguments to the config file.

The text in this table in not discoverable from the "Search docs" page in the upper-left side of the webpage:
<img width="287" alt="image" src="https://github.com/user-attachments/assets/4e989f3b-b790-4d0a-ba2d-b8b53689fd89">

------
I came across this looking for information about the Rayleigh sponge, which has a config entry:

<img width="721" alt="image" src="https://github.com/user-attachments/assets/ac654d91-8fec-4014-9a90-4ad77e4c2226">

but there are no results in search:

<img width="953" alt="image" src="https://github.com/user-attachments/assets/632bb4ce-9cb2-4ddf-9e0f-94dff7ed6f54">

**Comment by Sbozzolo** [comment]
This can be solved by generating everything ahead of time
