### ISSUE TITLE
End-to-end calibration test occasionally times out

### ISSUE THREAD

**Issue by charleskawczynski** [CliMA/ClimaAtmos.jl#3335]
Sometimes our end-to-end calibration test is timing out, preventing PRs from being merged.

Some examples:
 - https://buildkite.com/clima/climaatmos-ci/builds/20742
 - https://buildkite.com/clima/climaatmos-ci/builds/20760

@costachris, any idea why this might be timing out? The SYPD is pretty huge for that job.

**Comment by szy21** [comment]
I think it times out when the cluster is busy, because it is waiting for submitting new jobs for each iteration.

**Comment by Sbozzolo** [comment]
> I think it times out when the cluster is busy, because it is waiting for submitting new jobs for each iteration.

Yes, that's the problem.

We can decrease the number of ensable members and iterations.

**Comment by nefrathenrici** [comment]
Closed by #3386, since the job has been set to soft-fail and the slurm timeout limit has been lowered.

**Comment by nefrathenrici** [comment]
I also opened an issue in ClimaCalibrate to remove the dependency on the slurm database
https://github.com/CliMA/ClimaCalibrate.jl/issues/115
