### ISSUE TITLE
insolation_tuple is not correctly set for boxes/columns

### ISSUE THREAD

**Issue by Sbozzolo** [CliMA/ClimaAtmos.jl#3355]
https://github.com/CliMA/ClimaAtmos.jl/blob/aedb9984dd95a53a199f2c223d8b3f664f7d33bc/src/callbacks/callbacks.jl#L325

this update is not in-place, so `p.radiation.insolation_tuple` does not get update.

**Comment by charleskawczynski** [comment]
Closed by #3359
