### ISSUE TITLE
Seed the random number generator with the time-step number before calling the radiation solver to guarantee reproducibility.

### ISSUE THREAD

**Issue by sriharshakandala** [CliMA/ClimaAtmos.jl#3384]

**Comment by Sbozzolo** [comment]
Note that if you seed the random number every time you call radiation, you lose all the randomness properties of your RNG. RNGs require a statistical sample of values to satisfy basic entrophy properties, so we should fix the seed as infrequently as we can. If we do this once every checkpoint, we will reset the seed every ~700 numbers, which is not very much, so will probably also want an option to disable this behavior.

**Comment by sriharshakandala** [comment]
- We are using a different seed at every `rrtmgp` call, based on the dycore time step number. Update flux is typically called every one hour with a dycore step of about 100 sec.
- The number of `rand` calls, after seeding, for each 'update_flux` call is typically of the order `3000 * 4 * 4` * (`fraction of cols with clouds`) * (`average number of cloudy layers per cloudy column`) * 2 (i.e. `96,000` * `frac of cols with clouds` * `avg # of cloudy layers per column`).
- Linking seeding frequency with checkpoint frequency is not natural and, in general, does not guarantee reproducibility!

**Comment by Sbozzolo** [comment]
> Linking seeding frequency with checkpoint frequency is not natural and, in general, does not guarantee reproducibility!

Why not? We only need to seed at the checkpoint to ensure reproducibility and we need to be able set the same seed upon restart. 

> The number of rand calls, after seeding, for each update_flux call is typically of the order 3000 * 4 * 4 * (fraction of cols with clouds) * (average number of cloudy layers per cloudy column) * 2 (i.e. 96,000 * frac of cols with clouds * avg # of cloudy layers per column).

Good!

Even so, we should interfere the least we can to ensure that the properties of the RNG are correctly realized.

**Comment by sriharshakandala** [comment]
> > Linking seeding frequency with checkpoint frequency is not natural and, in general, does not guarantee reproducibility!
> 
> Why not? We only need to seed at the checkpoint to ensure reproducibility and we need to be able to set the same seed upon restart.
> 
> > The number of rand calls, after seeding, for each update_flux call is typically of the order 3000 * 4 * 4 * (fraction of cols with clouds) * (average number of cloudy layers per cloudy column) * 2 (i.e. 96,000 * frac of cols with clouds * avg # of cloudy layers per column).
> 
> Good!
> 
> Even so, we should interfere the least we can to ensure that the properties of the RNG are correctly realized.

The user can keep changing the checkpoint frequency during the course of a simulation! Simulations run for the same integration time using different checkpointing number for different fractions of total integration time could see different results!

**Comment by sriharshakandala** [comment]
I do agree that we should have an option to turn off seeding completely if the user chooses to do so!

**Comment by sriharshakandala** [comment]
- This manual seeding feature is primarily for verifying bit-wise reproducibility for testing purposes. 
- We should just turn off manual seeding for production runs. I do not believe the goal for our production runs is bitwise reproducibility. We just need reasonable agreement in some statistical sense. 
- I do not believe we should be generating random numbers when they are not needed.
- Checkpoint frequency is not currently linked to `rrtmgp` call frequency!

**Comment by Sbozzolo** [comment]
> This manual seeding feature is primarily for verifying bit-wise reproducibility for testing purposes.
> We should just turn off manual seeding for production runs. I do not believe the goal for our production runs is bitwise reproducibility. We just need reasonable agreement in some statistical sense.

I agree. The main use case of this is allowing people to restart a simulation that broke and explore what went wrong.

>  Checkpoint frequency is not currently linked to rrtmgp call frequency!

We started requiring for the checkpoint frequency to be integer multiple of the rrtgmp frequency:

https://github.com/CliMA/ClimaAtmos.jl/blob/3caa65012f9c8b5f20bea0fb7d22c5c608d61d9f/src/callbacks/get_callbacks.jl#L284-L285

Consider that for our nightly AMIP simulations, we only have ~ 4000 zones, so setting the RNG at every radiation call would lead to a very small run of points, which means that the points will be biased (even by resetting the seed to a new value). Being biased means that we could have more points closer to 0 than to 1. 

If the quality of random numbers don't matter much, we can go ahead with resetting the seed every hour, but let's make sure that this gotcha is documented somewhere.

**Comment by Sbozzolo** [comment]
> If the quality of random numbers don't matter much, we can go ahead with resetting the seed every hour, but let's make sure that this gotcha is documented somewhere.

I ran some tests and convinced myself that the bias is small, even when we generate only 100 numbers per seed. So, this should be fine.

**Comment by sriharshakandala** [comment]
I updated the above estimate by a factor of (>= 224) since we do this for each of the 224 points (shortwave), or 256 g-points (longwave)
