### ISSUE TITLE
Error starting from restart without `atoms_model_hash`

### ISSUE THREAD

**Issue by haakon-e** [CliMA/ClimaAtmos.jl#3387]
Trying to `get_simulation(config)` with a restart file from a run a few weeks ago gives the the error:

```julia
ERROR: HDF5.API.H5Error: Error opening attribute atmos_model_hash for object /
libhdf5 Stacktrace:
 [1] H5O__attr_open_by_name: Attribute/Object not found
     can't locate attribute: 'atmos_model_hash'
  ⋮
```

which I think is due to this line: 
https://github.com/CliMA/ClimaAtmos.jl/blob/62dbe8cf1c11e16e1f0635865d598c6dccf6d8f3/src/solver/type_getters.jl#L309-L310

I presume new simulations won't have this problem, but perhaps there could be a "strict" flag to allow folks to restart older simulations from newer versions of ClimaAtmos?

**Comment by haakon-e** [comment]
cc: @Sbozzolo

**Comment by Sbozzolo** [comment]
Thanks, we can easily address this.
