### ISSUE TITLE
(geo)Potential bug

### ISSUE THREAD

**Issue by charleskawczynski** [CliMA/ClimaAtmos.jl#3456]
I was refactoring some code and came across `@. ᶜ∇Φ³ += CT3(gradₕ(ᶜΦ))` [here](https://github.com/CliMA/ClimaAtmos.jl/blob/002b4f341699db2c90235285b2bf25211d5c7586/src/cache/diagnostic_edmf_precomputed_quantities.jl#L334). Maybe there's some topography nuance here that I'm missing, but shouldn't this be `@. ᶜ∇Φ³ += CT3(gradᵥ(ᶜΦ))`?

Sorry for the pun in the title, I couldn't help myself 🙃

cc @szy21, @trontrytel @costachris

**Comment by szy21** [comment]
This has something to do with topography. We want the contravariant 3 component of the gradient of geopotential gradient, which includes the contribution of both horizontal and vertical gradients of Φ (the horizontal gradient is zero without topography). It shouldn't be `@. ᶜ∇Φ³ += CT3(gradᵥ(ᶜΦ))` as that's double counting the vertical gradient.

**Comment by charleskawczynski** [comment]
Ok, thanks for the clarification!
