### ISSUE TITLE
Track moist Held-Suarez developments

### ISSUE THREAD

**Issue by jiahe23** [CliMA/ClimaAtmos.jl#363]
This issue is to track the developments of moist held-suarez. Here are the code pieces needed from dry hs to moist:
- [x] moist var `qt` and equations
- [x] microphysics scheme (0Moment for now)
- [x] a simple vertical diffusion (following the [paper](https://gmd.copernicus.org/articles/9/1263/2016/gmd-9-1263-2016.pdf)
- [x] surface flux varying spatially (dependency: a new ClimaCore.jl release after [this](https://github.com/CliMA/ClimaCore.jl/pull/325) merged)
- [ ] limiter for positivity

===============================
Tests:

**Comment by trontrytel** [comment]
Right now the moist HS crashes at day 18. Our goal is to have it running 1200. That means we are 1.5% done right now. We will keep updating this metric ;)

Things we tried that are stable till 1200 days:
- [ ] dry HS
- [ ] moist HS with no surface fluxes

Things we are testing now:
- [ ] moist HS with moisture as passive tracer (set latent heat to 0)  -> crashes at day 24
- [ ] moist HS without 0-moment precipitation -> crashes at day ?
- [ ] moist HS with 0-moment precipitation -> crashes at day 18

@bischtob @charleskawczynski @LenkaNovak

**Comment by trontrytel** [comment]
The instability starts suspiciously "at the corner". Any hints what we could look at next @simonbyrne @szy21?

**Comment by bischtob** [comment]
@jiahe23 are there any updates here?

**Comment by jiahe23** [comment]
> @jiahe23 are there any updates here?

Updating climacore version in atmos; will set up proper sst once this done.

Waiting for limiters.
