### ISSUE TITLE
Implement adaptive time stepper via callbacks

### ISSUE THREAD

**Issue by bischtob** [CliMA/ClimaAtmos.jl#37]
**context**
We can leverage the callbacks infrastructure to have adaptive time stepping.

**ideas**
Reuse the calculation methods used for `OutputWriters` to calculate a new time step based on the flow. Then update the `DEIntegrator` state.

**next steps**
Finish the callbacks framework first, then prototype an example using CFL calculator.

**Comment by akshaysridhar** [comment]
First iteration of `Callbacks` is now in. This is within reach in the short term.

**Comment by akshaysridhar** [comment]
From Issue 41 
```
cfl monitor idea

struct CFL end
function (::CFL)(Y,Ya,integrator)
    u, v, w = Y.u.u1, Y.u.u2, Y.u.u3
    u_max, v_max, w_max = maximum.((u, v, w))
    dh, dz = minhorzdistance(axes(u)), minvertdistance(axes(w))
    dt = currenttimestep(integrator)
    cfl_x = u * dt / dh
    cfl_y = v * dt / dh
    cfl_z = w * dt / dz

    cfl_horz = maximum(cfl_x, cfl_y)
    cfl_vert = maxmium(cfl_z)    

    return (horizontal = cfl_horz, vertical = cfl_vertical)
end
```
