### ISSUE TITLE
Add / improve auto-plotting infrastructure

### ISSUE THREAD

**Issue by charleskawczynski** [CliMA/ClimaAtmos.jl#373]
There are a few ways we can improve our results plotting infrastructure:

 - Data can be better post-processed (e.g., apply remapping) before generating plots
 - We could compute time averages (comparing images is easier than comparing animations)
 - Perform comparisons against the main branch-- I find this more helpful / fast to compare with images than with animations

This issue was peeled off from #301.

**Comment by szy21** [comment]
Superseded by #1328
