### ISSUE TITLE
Centralize output folder

### ISSUE THREAD

**Issue by charleskawczynski** [CliMA/ClimaAtmos.jl#407]
What do people thing about creating a centralized output folder? For example:

```
docs/
output/
     /alloc_sphere_baroclinic_wave_rhoe
     /baroclinic_wave_rhoe
     /sphere_baroclinic_wave_rhoe
     /sphere_held_suarez_rhoe_equilmoist
     /sphere_held_suarez_rhotheta
     /flame_held_suarez_rhoe_equilmoist
     /sphere_single_column_radiative_equilibrium
     /held_suarez_rhotheta
src/
...
```

I think it would help navigation when running cases locally.

cc @jiahe23, @dennisYatunin, @LenkaNovak, @bischtob

**Comment by LenkaNovak** [comment]
Sounds good to me! (loving the label btw :) ) What exactly were you thinking for the output though (e.g. plots / notebooks / conservation tests)?

**Comment by charleskawczynski** [comment]
I was just thinking that we could prepend all output directories with `output/`, so that we'd have `output/existing_output_dirname/`. As I run cases locally, the `ClimaAtmos.jl/` directory gets a bit cluttered with output folder names, and then I periodically `rm -rf` them
