### ISSUE TITLE
Earth topography in ClimaAtmos experiments

### ISSUE THREAD

**Issue by akshaysridhar** [CliMA/ClimaAtmos.jl#408]
Status: ~80%
 
[Current Work] : Evaluate stability with long time integration for combinations of fluxes and forcing terms. Upwinding schemes are preferred over standard central schemes based on current setups (results are below, detailed NetCDF and JLD2 available on cluster storage) 

1. Metric term modifications with topography are in ClimaCore.

- [x]  https://github.com/CliMA/ClimaCore.jl/tree/main/src/Hypsography
- [x]  https://github.com/CliMA/ClimaCore.jl/pull/667
- [ ]  https://github.com/CliMA/ClimaCore.jl/pull/706

2. Interfaces to prescribe topography from stored datasets is included in ClimaCore.
    - [x]  Demo : https://github.com/CliMA/ClimaCore.jl/blob/main/test/Spaces/terrain_warp.jl
3. Towards demonstration of earth topography on hybrid extruded grid (interpolated form ETOPO1 dataset) at 450km, 100km resolutions.
    - References: 
      - https://journals.ametsoc.org/view/journals/clim/26/3/jcli-d-11-00448.1.xml [Evans et al. (2018)]
        (Height field E(k), k<71 resolution required. c.f. CAM-SE for sensitivity to smoothing.)
      - https://gmd.copernicus.org/articles/8/3975/2015/ [Lauritzen et al. (2015)] 
        (MODIS Data mask options, LANDFRAC / terrain-dependent masking, consequences of smoothing)    

###  Pull Request Sequence
- [x]  Build mask options following PR#325 merger (see Coupler [PR](https://github.com/CliMA/ClimaCoupler.jl/pull/50)), 
- [ ] (90%) Complete verification - long time integration tests of tendency terms with topography, address stability issues. [ie. verify projection operations in tendency specifications, and boundary conditions with topography features included] 
- [x] Update ClimaCoreTempestRemap `netcdf` methods to handle TerrainWarpedIntervalTopology. Verify NetCDF outputs. ClimaCore https://github.com/CliMA/ClimaCore.jl/pull/764
- [x] Update vector projections in prognostic equations to correctly apply contravariant projections. #540 
- [x] Update cache variables to carry surface pressure. (See https://github.com/CliMA/ClimaAtmos.jl/pull/543, extend this to pressure)
- [ ] Update SurfaceFluxes interactions with non-zero elevation (define contravariant 3 vector components)
- [ ] (Stretch) : VTK support. 

Development: Most of the changes required for this will be first implemented in ClimaCore.jl ; Modifications to `common_spaces` and the `staggered_nonhydrostatic_model` in ClimaAtmos will follow once (4) is completed.

**Comment by akshaysridhar** [comment]
Demonstration problems:  
Spectral FD (Plane) 
![image](https://user-images.githubusercontent.com/43710045/167163936-1be15201-d6f9-4a14-9c2c-ef5f009e6edf.png) 

Spectral FD ("Unwrapped" Sphere)
<img width="604" alt="Demo_Earth_Topography" src="https://user-images.githubusercontent.com/43710045/167168536-472a348e-dd74-4a29-aeb3-554618c30b24.png"> [Simulation unstable for now :( ]

**Comment by akshaysridhar** [comment]
**Temperature, Vorticity at Day 6 in DCMIP test case (200)**
![bw-temperature-day6](https://user-images.githubusercontent.com/43710045/171880600-0439f327-6e7e-454a-a731-f265e6ed2cd2.png)
![bw-vorticity-day6](https://user-images.githubusercontent.com/43710045/171880610-106e9df6-9692-41b4-9c1f-0c80e7553131.png)

**Comment by szy21** [comment]
Superseded by #1282
