### ISSUE TITLE
Push discretization-dependent code to lower level

### ISSUE THREAD

**Issue by tapios** [CliMA/ClimaAtmos.jl#42]
It would be good for ClimaAtmos to be discretization agnostic as much as possible. This means, ideally, not distinguishing between face and center quantities at this level, and not having discretization-specific operations such as DSS here. They should live at a lower level, so that ClimaAtmos can equally well be used, e.g., with a FV core.

**Comment by glwagner** [comment]
It could make sense to use `Oceananigans.ShallowWaterModel` (or copy/paste that code into here) as an FV atmospheric model place holder for prototyping.
