### ISSUE TITLE
Improve PR review experience

### ISSUE THREAD

**Issue by charleskawczynski** [CliMA/ClimaAtmos.jl#423]
I think there are several concrete things that we can do to improve the PR review experience, specifically for PRs that are behavior-changing:
 - Reduce the number of figures / artifacts. We should probably hone in on specific results to review, and right now looking through all the results / videos is pretty time consuming (I'm admittedly responsible for adding some figs / animations that are less than ideal for review)
 - Focusing on post-processed figures over animations. Animations are difficult to compare, even if they're side-by-side, because (of course) they move and because they can take a long time. Doing something like proper orthogonal decomposition (POD), or some sort of temporal compression would give a really nice snapshot of the overall picture. @jiahe23's added plots are great, they're post-processed for comparing for literature, and we need more of this.
 - Side-by-side with reference. One of the reason TC's pipeline has become so smooth is that the pipeline automatically plots results as a comparison against references, so there's not really any additional places to look for reviewing PRs-- and it automatically updates as the code changes.

I think there's low hanging fruit for some of these items, and others may require more thought / effort. I'm not suggesting that we get rid of all the animations, but perhaps they can 1) limit them a bit more (I may trim out some that I've added, but don't really look at much anymore) and 2) perhaps somehow split them from other results that are easier to review.

**Comment by szy21** [comment]
Superseded by #1328. I think we covered all the points in that issue, but please add to the issue if you have more comments.
