### ISSUE TITLE
Track idealized aquaplanet with radiation development

### ISSUE THREAD

**Issue by szy21** [CliMA/ClimaAtmos.jl#485]
It might be useful to have an issue to track important updates on the idealized aquaplanet development so that everyone is on the same page. I will keep updating this issue.

The goal is to build the model that is ready for EDMF integration.

Current status (all with z_max = 30km, stretched grid with 500m at the bottom and 5000m at the top):

**1. z_elem = 10, gray radiation, runs for 800 days**
2. z_elem = 10, clear sky radiation, crashes at day 6
3. z_elem = 20, clear sky radiation, crashes before day 10
4. z_elem = 10, clear sky radiation, rayleigh sponge starting at 20km, crashes at day 12
**5. z_elem = 10, clear sky radiation, rayleigh sponge starting at 15km, runs for 800 days**
**6. z_elem = 15, clear sky radiation, rayleigh sponge starting at 20km, runs for 800 days**
7.  z_elem = 10, clear sky radiation, viscous sponge starting at 15km with diffusivity 1e6, crashes at day 6
8. z_elem = 10, clear sky radiation, isothermal initial condition, crashes at day 80
**9. z_elem = 10, clear sky radiation, viscous sponge starting at 15km with diffusivity 1e7, runs for 800 days**
10. z_elem = 15, clear sky radiation, viscous sponge starting at 15km with diffusivity 1e6, crashes at day 460

**Some of the simulations start with a different initial conditions so don't read too much into the numbers of days**

Next steps (suggestions?):
- [ ] check the difference between with and without radiation (need more diagnostics)

Still needs:
- [ ] Change constant coefficient to monin obukhov in surface fluxes (waiting for the coupler team, we are not doing it before amip?)
- [ ] Change domain top to 45km (maybe optional, and maybe better to test this in moist held suarez first, which is not working currently)
- [ ] Use limiters (waiting for the numerics team)

**Comment by szy21** [comment]
When the simulation is stable, the results look somewhat reasonable to me.

Here is zonal mean zonal wind in 1. z_elem = 10, gray radiation:
![image](https://user-images.githubusercontent.com/11598433/169927436-10cf8318-6532-4f6e-9198-49006f3c3f7e.png)

Here is zonal mean zonal wind in 5. z_elem = 10, clear sky radiation, rayleigh sponge starting at 15km: Note that the difference at the top is likely from the sponge.
![image](https://user-images.githubusercontent.com/11598433/169927293-cc7a6373-2206-473e-9ee7-9e6c1e596dd2.png)

**Comment by szy21** [comment]
When the simulation crashes, it's not very clear to me what the reason is. Here is an example of the top level (top) v and (bottom) w before it crashes. Looks like some gravity wave? That may explain why sponge helps, and maybe we just need enough levels for the sponge? Why would gray radiation be stable without the sponge though?

![image](https://user-images.githubusercontent.com/11598433/169927749-d2a40f09-de26-448b-af26-89bfb39b51d0.png)

![image](https://user-images.githubusercontent.com/11598433/169927678-8fe69754-ee3c-4e0b-b25e-9066f339ba35.png)

**Comment by szy21** [comment]
I would appreciate @tapios thoughts on this.

**Comment by tapios** [comment]
@szy21 Let's talk through this on Wednesday. I need more detail to parse what's going on.

**Comment by szy21** [comment]
Here is the temperature and meridional velocity at about 5km at day 6, for no radiation, gray radiation, and clear sky radiation (everything else is the same). I don't know why the difference is large after only 6 days. I probably did something wrong, but I will need more diagnostics to analyze it. I will focus on this before moving on to more tests.

no radiation:
![image](https://user-images.githubusercontent.com/11598433/170178848-9312aba9-0b0f-4956-ac74-916d90c38c26.png)
![image](https://user-images.githubusercontent.com/11598433/170179039-25a0365d-1c60-46ab-8460-034613dd67cc.png)
gray radiation:
![image](https://user-images.githubusercontent.com/11598433/170178874-2d4e788b-222c-4c54-a00e-76d50514f397.png)
![image](https://user-images.githubusercontent.com/11598433/170179014-2544f3b1-a482-4e8f-b797-6befdf0e1826.png)
clear sky radiation:
![image](https://user-images.githubusercontent.com/11598433/170178909-4bdf83a5-935c-400d-9132-cc3968918f0d.png)
![image](https://user-images.githubusercontent.com/11598433/170178975-d82e978e-18b4-462a-811c-14e63c183dc2.png)

**Comment by szy21** [comment]
We'll move on for now and use the configuration `z_elem = 10, clear sky radiation, viscous sponge starting at 15km with diffusivity 1e7`. I will close this issue.
