### ISSUE TITLE
Long run is broken

### ISSUE THREAD

**Issue by charleskawczynski** [CliMA/ClimaAtmos.jl#525]
Just to track, our long runs are broken and need to be fixed. I can try to track down which commits may be the culprits, but opening now for the record.

**Comment by szy21** [comment]
Which ones are you thinking about? Is it the error in postprocessing?

**Comment by charleskawczynski** [comment]
Yeah, it's an error in the post processing

**Comment by charleskawczynski** [comment]
[here](https://buildkite.com/clima/climaatmos-longruns/builds/211#0181c805-8cfc-4c5a-991c-23675a8009ac/133-288) is a job failure example. cc @simonbyrne

**Comment by charleskawczynski** [comment]
Fixed by #645
