### ISSUE TITLE
Instability after switching to space filling curve (low priority)

### ISSUE THREAD

**Issue by LenkaNovak** [CliMA/ClimaAtmos.jl#586]
PR [#574](https://github.com/CliMA/ClimaAtmos.jl/pull/574/files) causes long CI runs to break (saturation adjustment: negative density, e.g. [here](https://buildkite.com/clima/climaatmos-longruns/builds/218#0181d254-19aa-4661-ae26-4cfa92c85a3f), with some results summarized [here](https://docs.google.com/spreadsheets/d/1vksKjzrKEErU17yjXEUhn88Ignm9BOywT5O_9Fm48iQ/edit#gid=991011956)). This warrants further investigation whether this is related to another bug (and this PR just tips the nearly unstable setup to be unstable), or whether there is a more serious problem with the space filling curve (though it passed its unit tests in ClimaCore). 

Preliminary results show this is more problematic for 3rd order upwinding when using Float32. Float64 seems ok. This difference was also noted when performing a simple Field `sum` over Fields before/after the space filling curve PR for Float32 (not for Float64), though the difference was very small. @szy21 may have more details. 

This will become higher priority if we use 3rd order upwinding in the standard config (TBD).

**Comment by szy21** [comment]
Is this still a problem?

**Comment by LenkaNovak** [comment]
Not that I know of. All issues with the SFC have been addressed, as far as I know. Just tagging @simonbyrne here, is case there's something I'm not aware of.
