### ISSUE TITLE
Update buildkite runs to the newly decided config

### ISSUE THREAD

**Issue by LenkaNovak** [CliMA/ClimaAtmos.jl#587]
(in progress)
We need to update our Buildkite pipeline so that all cases are stable and can catch problems with incoming changes.

## Long runs
- it is still valuable to run coarse resolution checks for several years, to obtain a quick view of long-term stability and tracer conservation
- suggested config:
  - helem, nq, velem, z_max, dz_bottom, dz_top = (4, 5, 10, 30e3, 500, 5000)
  - dt = ~ 400s 
  - dry & moist
  - other numerics TBD

## High resolution runs
- this will be the prequel to the first AMIP simulation, and will be the basis for the next round of stability vs performance testing.
- suggested config:
  - helem, nq, velem, z_max, dz_bottom, dz_top = (12, 5, 45, 30e3, 30, 5000)
  - dt = ~ 200s 
  - dry & moist
  - no limiters (?), 3rd order upwinding (?)
  - t_end = ?

**Comment by szy21** [comment]
I think we can close this:)
