### ISSUE TITLE
The `bycolumn` PR broke the long runs

### ISSUE THREAD

**Issue by charleskawczynski** [CliMA/ClimaAtmos.jl#610]
The long runs broke on #585. See builds

 - [231](https://buildkite.com/clima/climaatmos-longruns/builds/231): long runs work (for PR #589)
 - [232](https://buildkite.com/clima/climaatmos-longruns/builds/232): long runs break (for PR #585)

This also kind of makes sense since #585 adjusted the mse tables which, now that I'm thinking of it, doesn't make sense to me.  @simonbyrne do you know why these changes would result in behavioral differences?

Also, if this is another instance of machine precision differences, we really need to make the long runs more robust by not running so close to the unstable limit. @szy21, @jiahe23, can we use slightly smaller timesteps for these runs so that they're not so unstable? Configurations like this are really difficult to maintain / update, our model (and configuration) shouldn't be sensitive to machine precision. #585 was, was aimed at making the model faster, so we should be able to afford a slightly smaller timestep.

Before changing the timestep, however, let's make sure that there wasn't a bug in the bycolumn implementation. (cc @simonbyrne )

**Comment by szy21** [comment]
These failed long runs only run for a few minutes, which means they fail almost immediately after initialization. But how could the PR pass the standard buildkite? For example, PR 585 can run 10 days for jobid [`sphere_held_suarez_rhoe`](https://buildkite.com/clima/climaatmos-ci/builds/1925#0181df44-5cb0-4b36-a3e2-6d6a5ffa64b7), but the [`longrun_hs_rhoe`](https://buildkite.com/clima/climaatmos-ci/builds/1925#0181df44-5cb0-4b36-a3e2-6d6a5ffa64b7) failed before day 10.

**Comment by charleskawczynski** [comment]
Yes, that and the use of `dt_save_to_sol` and `dt_save_to_disk`. So either:

 - Single vs multi-threading is resulting in behavioral changes, which is corroborated by the behavioral changes in CI for #585 
 - The `dt_save_to_sol` is affecting the state of the system (we've made this mistake before in TC)

Due to the mse table changes, I'm inclined to say it's the former. @simonbyrne, this seems kind of important to look into since, I can see how multithreading in horizontal could result in machine precision differences, but column multithreading should be identical.

**Comment by simonbyrne** [comment]
I can't look until tomorrow, but i would start by comparing the results from a single evaluation
