### ISSUE TITLE
Implement general and flexible model interface

### ISSUE THREAD

**Issue by bischtob** [CliMA/ClimaAtmos.jl#64]
This enables tracers models, subcomponents, flux accumulation. If done correctly allows naturally for operation on subset of state.

Pseudocode ideas
```
SubModel1 = ... 
#SoilModel = NoSoil(T_prescribed = T(x,y,z,t), \theta_i = f)])
SoilModel = FancySoil(args...; kwargs...)
CoupledModel = ...
main_model = MainModel(SubModel1, SoilModel, CoupledModel, ..., args...; kwargs...)

SubIC1 = sub_ic1 # functions f(x, y, z, params; kwargs...) => f(x, y, z, params; T_sfc = FieldReader)
SoilIC = soil_ic
CoupledIC = coupled_ic
ic = (SubIC1, SoilIC, ..., args...; kwargs...) # creates prognostic and aux components: Y = (Y_prog = (sub1 = Y1, soil = Y_soil, coupled = Y_coupled)

function make_rhs(main_model)
    rhs_sub1! = make_rhs(main_model.sub1) # rhs_sub1! updates dY.sub1 in place
    rhs_soil! = make_rhs(main_model.soil) # ""
    rhs_coupled! = make_rhs(main_model.coupled) # ""
    function rhs!(dY, Y, p, t)
        rhs_sub1!(dY.sub1, Y, p, t)
        rhs_soil!(dY.soil, Y, p, t)
        rhs_coupled!(dY.coupled Y, p, t)
    end

    return rhs!
end

# Y = (Y1, SoilY, ...)
state = make_state(ic) # assembles a state, populates stuff needs to know that for SoilIC - dont add anything

ic = ModelIC(canopy = canopy_ic, soil = soil_ic, river = river_ic,...)
sim = Simulation(model, ic, stepper, dt, ...)
```

**Comment by glwagner** [comment]
> One thing that would be good to keep in mind here: we need structures that label terms as implicit, slower rate (by integer multiple n) etc., that is, a `rhs` (I'd prefer to call it tendency to disambiguate) that can be further sub partitioned according to time rates.

Oceananigans handles this by attaching a `time_discretization` property to every closure. We only support   `VerticallyImplicitTimeDiscretization` now; vertical flux divergences are elided for closures marked by this type using multiple dispatch and their contributions are added during an implicit solve in a separate step.

**Comment by bischtob** [comment]
I have cooked something up today that addresses a few points. I will post the design and an example here early next week.

**Comment by bischtob** [comment]
Superseded by #137 and #139
