### ISSUE TITLE
memory allocations in tridiagonal LU factorization

### ISSUE THREAD

**Issue by simonbyrne** [CliMA/ClimaAtmos.jl#648]
The  call to [`lu!` in the linear solve](https://github.com/CliMA/ClimaAtmos.jl/blob/e7e23ba3861e80a4f0f2a798469183e57b867160/examples/hybrid/schur_complement_W.jl#L225) causes significant memory allocations. My guess is that it is caused by the allocation of the pivot array:
https://github.com/JuliaLang/julia/blob/v1.7.3/stdlib/LinearAlgebra/src/lu.jl#L500

Options:
- write our own direct tridiagonal solver. @OsKnoth might have some code?
- use [BandedMatrices.jl](https://github.com/JuliaMatrices/BandedMatrices.jl), which wraps the general LAPACK banded solvers

**Comment by simonbyrne** [comment]
The best option is probably to implement the [Thomas algorithm](https://en.wikipedia.org/wiki/Tridiagonal_matrix_algorithm)

**Comment by charleskawczynski** [comment]
Is there an issue open in Julia about the allocations? (not that we'll be able to leverage it yet)

**Comment by simonbyrne** [comment]
no idea: feel free to open one
