### ISSUE TITLE
Compressible bomex is unstable

### ISSUE THREAD

**Issue by charleskawczynski** [CliMA/ClimaAtmos.jl#697]
See [this build](https://buildkite.com/clima/climaatmos-ci/builds/2521#018237d5-758f-4954-b4c8-e338aba28fee/132-171).

We should probably add a test/assert: `@assert sol.t == t_end` after `solve!(integrator)` so that we know that every job is running to completion.

**Comment by trontrytel** [comment]
This one could be closed?

**Comment by charleskawczynski** [comment]
Yes!
