### ISSUE TITLE
Set up regression & validation testing framework

### ISSUE THREAD

**Issue by bischtob** [CliMA/ClimaAtmos.jl#70]
**context**
Very soon, we will be running benchmarks and keeping them working while the underlying numerics and model interface is changing is a pain that need to be automated away.

**idea**
Replicate framework from Oceananigans.jl and TurbulenceConvection.jl to set up test groups with PR artifacts. This will keep things tested with high coverage and quick development turnaround.

**next steps**
1. Set up test groups for full simulations examples. Provide one group for regression (only one time step) and one group for validation (output plots, metrics)
2. After 1. is accomplished set up buildkite artifacts.

**Comment by bischtob** [comment]
@charleskawczynski, what do we need for you framework to work. Can you post rough steps?

**Comment by charleskawczynski** [comment]
For TurbulenceConvection.jl, there are several pieces:

 - Each experiment [includes](https://github.com/CliMA/TurbulenceConvection.jl/blob/main/integration_tests/Bomex.jl#L11) a file that defines [a `Dict` containing mean squared errors (MSEs) for _all_ experiments](https://github.com/CliMA/TurbulenceConvection.jl/blob/main/integration_tests/utils/mse_tables.jl)

 - The experiment then [grabs the corresponding `Dict` for the particular experiment](https://github.com/CliMA/TurbulenceConvection.jl/blob/main/integration_tests/Bomex.jl#L14) and passes that into a mega-machinery, called [`compute_mse_wrapper`](https://github.com/CliMA/TurbulenceConvection.jl/blob/main/integration_tests/Bomex.jl#L23), defined [here](https://github.com/CliMA/TurbulenceConvection.jl/blob/main/integration_tests/utils/compute_mse.jl#L97), that computes MSEs for all desired variables (specified in `mse_tables.jl`).

### What `compute_mse_wrapper` does

 - Accepts only `.nc` files, to keep things agnostic, however, the existing keys/values will depend on what experiments are run.

 - Plots (and saves .png) all of the results, and comparison against other references (SCAMPy, TC.jl's main branch, Pycles LES), for a single experiment.

 - Computes a `Dict` of _computed_ MSE values (for the PR) against one of the references, with [some precedence](https://github.com/CliMA/TurbulenceConvection.jl/blob/main/integration_tests/utils/compute_mse.jl#L398-L406).

- These values are [dumped to a JSON file](https://github.com/CliMA/TurbulenceConvection.jl/blob/main/integration_tests/Bomex.jl#L32-L34), and [tested](https://github.com/CliMA/TurbulenceConvection.jl/blob/main/integration_tests/Bomex.jl#L36-L38) against the "best" MSE values (i.e., the MSE values in `main`).

### How `compute_mse_wrapper` works

 - [checks](https://github.com/CliMA/TurbulenceConvection.jl/blob/main/integration_tests/utils/compute_mse.jl#L108-L116) if a buildkite commit env variable is defined (to see if we're running locally/remotely), and if it is, then we grab the .nc file to be included in the comparison against the computed results.

  - Once the comparison is finished, we [wait, and continue on failure](https://github.com/CliMA/TurbulenceConvection.jl/blob/main/.buildkite/pipeline.yml#L168-L169) to [print](https://github.com/CliMA/TurbulenceConvection.jl/blob/main/.buildkite/pipeline.yml#L171-L178) the PR's MSE table, defined [here](https://github.com/CliMA/TurbulenceConvection.jl/blob/main/utils/print_new_mse.jl). This allows us to easily update all of the MSE tables in a single copy-paste.

  - Then, we [wait, and do _not_ continue on failure](https://github.com/CliMA/TurbulenceConvection.jl/blob/main/.buildkite/pipeline.yml#L180) before [moving the computed output results from the local directory into a folder on the cluster](https://github.com/CliMA/TurbulenceConvection.jl/blob/main/.buildkite/pipeline.yml#L180-L189), defined [here](https://github.com/CliMA/TurbulenceConvection.jl/blob/main/utils/move_output.jl)

Note that the [`cluster_data_prefix`](https://github.com/CliMA/TurbulenceConvection.jl/blob/main/utils/move_output.jl#L5) when moving the results must match the [`cluster_data_prefix`](https://github.com/CliMA/TurbulenceConvection.jl/blob/main/integration_tests/utils/compute_mse.jl#L109) when reading the results.

@jakebolewski has suggested a few ways to simplify/improve this workflow, but it's working for us for now and I've not gotten around to doing this, yet.

**Comment by jakebolewski** [comment]
one additional suggestion would be to just have a prefix path URI for all assets that you would want to download / compare against and do that for everything.  that way we can stage all the data on the cluster and not have to re-download assets for every comparison.

ex: `$PREFIX/comparison1/data.nc` -> `gcs://atomos/comparions/comparion1/data.nc` or `file://central/groups/esm/comparisons/comparison1/data.nc` 

structuring it this way will simplify everything down the line
