### ISSUE TITLE
Widen scope of threaded column loops

### ISSUE THREAD

**Issue by charleskawczynski** [CliMA/ClimaAtmos.jl#720]
:warning: This issue is a work in progress :warning:

One important ingredient of improving performance is leveraging single processor parallelism via multithreading. ClimaCore supports three ways of multithreading code:

 - multithreading single broadcast expressions
 - multithreading a group of _column_ broadcast expressions with `bycolumn`
 - multithreading a group of _slab_ broadcast expressions with `byslab`

**Comment by trontrytel** [comment]
Thank you @charleskawczynski I'm taking this one and https://github.com/CliMA/TurbulenceConvection.jl/issues/908 as some first tasks for Nat to start contributing to TC 🚀

**Comment by charleskawczynski** [comment]
Ok, sounds good, also, keep in mind that we have the namelist hierarchy in TC and CA now!

**Comment by charleskawczynski** [comment]
@dennisYatunin, can we make a column-wise version of `set_precomputed_quantities!`? This is theoretically better for performance (more work per thread)

**Comment by tapios** [comment]
> Another performance regression in [84ba175](https://github.com/CliMA/ClimaAtmos.jl/commit/84ba17551432f01224c4a67bcdca0e490a673b5b) cc @dennisYatunin.
> 
> Just search for `bycolumn` in here to see where we've added additional launches.
> 
> cc @tapios. This will be a strong scaling GPU issue, not just a CPU multithreading issue. Basically, we need to minimize the number of `bycolumn` calls, and that's not something we can really enforce at the ClimaCore level, the implementation in ClimaAtmos must be mindful of this level of parallelism.
> 
> I'm not sure how to prevent this from happening. @dennisYatunin, can you please fix this or at least not introduce new `bycolumn` calls? Can @szy21 and or @trontrytel screen for this?

Thanks, @charleskawczynski. Could you please add a section "Best Practice for Developing Performant Code" to the code development best practice doc at https://github.com/CliMA/policies/wiki/Code-Development-Best-Practices-and-Policies, and add the issues you raise here, and others you are aware of, there? Please tag @simonbyrne and me as reviewers.

**Comment by trontrytel** [comment]
I'll be on the lookout for additional `bycolumn`s from now on. 

Would it be possible to come up with an estimate on how many are needed given our equations and how we split implicit/explicit tendencies?

**Comment by charleskawczynski** [comment]
> Would it be possible to come up with an estimate on how many are needed given our equations and how we split implicit/explicit tendencies?

My hope is no more than 2 (one for precomputed quantities and one for summing tendencies)

**Comment by charleskawczynski** [comment]
I'm going to close this issue because this is really only impacting CPU performance now that `bycolumn` is functionally different on the CPU and GPU, and while widening the scope of the bycolumn loops on the CPU may improve performance, it may not be the most impactful direction since we're targeting the GPU more.
