### ISSUE TITLE
OOM error in the high resolution moist held suarez longruns.

### ISSUE THREAD

**Issue by jiahe23** [CliMA/ClimaAtmos.jl#723]
Recent longruns of high resolution [1st amip target resolution] run into the [oom issue](https://buildkite.com/clima/climaatmos-longruns/builds/281#01825aca-bf98-48a9-8408-74bc124a4b2c).

@charleskawczynski @simonbyrne

**Comment by charleskawczynski** [comment]
This may be the result of the recent performance-related changes. We did add a _lot_ of `@inline`s, and they may not all be needed. It could be that adding those that aren't necessary bloated the resulting code gen. Until we confirm / fix that, it may be a good idea to just temporarily increase the memory request for those jobs running into this issue.

**Comment by szy21** [comment]
I don't think we have this issue anymore?
