### ISSUE TITLE
Topography experiments in longrun buildkite fail after changing to hdf5

### ISSUE THREAD

**Issue by szy21** [CliMA/ClimaAtmos.jl#761]
See [here](https://buildkite.com/clima/climaatmos-longruns/builds/325#0182c987-2239-4d6c-bff0-f01fe54fd25c) for example. cc @akshaysridhar. @simonbyrne mentioned hdf5 doesn't work with topography for now. One option is to just disable output in the topography experiments?

**Comment by akshaysridhar** [comment]
I think we can close this issue @szy21
