### ISSUE TITLE
Implement the non-orographic gravity wave parameterization

### ISSUE THREAD

**Issue by jiahe23** [CliMA/ClimaAtmos.jl#783]
## Purpose
Implement the [Alexander and Dunkerton (1999)](https://journals.ametsoc.org/view/journals/atsc/56/24/1520-0469_1999_056_4167_aspomf_2.0.co_2.xml) gravity wave (GW) parameterization, using the convective gravity wave source implemented in [GFDL](https://github.com/NOAA-GFDL/atmos_phys/blob/80d0a701d9772e23f44e6163cfd22ec0d762d0d9/atmos_param/cg_drag/cg_drag.F90).

Other resources
- [Fleming 1990](https://www.sciencedirect.com/science/article/pii/027311779090386E?ref=cra_js_challenge&fr=RR-1)
- [Mansfield Sheshadri (in press)](https://www.essoar.org/doi/abs/10.1002/essoar.10511598.1)

## Cost/Benefits/Risks
Benefits:
The parameterization of GW breaking and its forcing on momentum makes a more realistic representation of upper atmospheric circulations (stratosphere and mesosphere).

## People and Personnel
(@ the personnel required/requested to implement the software solution)
- Lead: @jiahe23 
- Collaborators: @LenkaNovak @szy21 and software engineers tbd
- Reviewers: tbd

## Components + Algorithm
- [design doc](https://www.overleaf.com/7583245518sfmjvghpkgpq)

## Results and deliverables
- [x] design - WIP (above)
- [x] translated algorithm 
- [x] driver test in a single-column model compared to Fig. 6 of [Alexander and Dunkerton (1999)](https://doi.org/10.1175/1520-0469(1999)056%3C4167:ASPOMF%3E2.0.CO;2)
    - [x] ERA-5 data [here](https://drive.google.com/file/d/1pOOv02QwW0GafY8-6Z68hjYadbZBz2F8/view?usp=sharing)  [9/15/2022]
- [x] test compared to Fig8 of [Alexander and Dunkerton (1999)] [9/15/2022]
- [ ] #897
- [ ] direct GCM integration. [9/30/2022]
- [ ] Future work plan (TBD: GCM integration via coupling to TC, parameter calibration, alternative orographic GW parameterization...)

**Comment by tapios** [comment]
Looks good to me!

**Comment by bischtob** [comment]
Can we add a little more detail here re task breakdown and dates, perhaps in terms of PRs? I am guessing we are targeting a simple driver first?

**Comment by jiahe23** [comment]
#852 partially resolved this issue; it provided a single column implementation.

GCM integration is still wip.
