### ISSUE TITLE
Non-deterministic results in all-sky long run

### ISSUE THREAD

**Issue by charleskawczynski** [CliMA/ClimaAtmos.jl#837]
These two builds:

 - https://buildkite.com/clima/climaatmos-longruns/builds/402#01832def-6aa0-452e-b220-a637e972191e
 - https://buildkite.com/clima/climaatmos-longruns/builds/403#01833083-97ea-42e6-86ad-7af6f607b480

occurred one day apart and the only PRs between were #834 and #835. So, it looks like our results for this job are non-deterministic, and we should fix this. Potential culprits are:
 - Use of `rand` without (or before) `Random.seed`
 - (threading) race condition in RRTMGP, ClimaCore, or some nested combination

**Comment by szy21** [comment]
That's probably because we use `rand` in fractional cloud cover in RRTMGP. @sriharshakandala Could you take a look?

**Comment by sriharshakandala** [comment]
> * https://buildkite.com/clima/climaatmos-longruns/builds/403#01833083-97ea-42e6-86ad-7af6f607b480

We can seed the `rand`. Can we find a good test case for the case with cloud fraction to compare with? @szy21

**Comment by sriharshakandala** [comment]
> That's probably because we use `rand` in fractional cloud cover in RRTMGP. @sriharshakandala Could you take a look?

We can seed the `rand`. Can we find a good test case for the case with cloud fraction to compare with? @szy21

**Comment by szy21** [comment]
No, we need to write test cases ourselves, and it takes some work. I can come back to it when I have more time. But fixing the random seed sounds like a good idea.

**Comment by szy21** [comment]
@charleskawczynski I just noticed we are actually setting the cloud fraction in ClimaAtmos in a way that the random number in RRMTGP should almost do nothing. I will push a small fix to RRTMGP to make sure, but what is the second possibility (on threading) you mentioned?

**Comment by charleskawczynski** [comment]
I need to take a closer look at how we call RRTMGP to see if we may have a threading issue. One thing to confirm is that we’re not calling `Threads.@threads` inside `Threads.@threads`

**Comment by szy21** [comment]
I'm going to try again after update rrtmpg. How should I know if the problem still exists or not? Should I just compare two runs to see if they are exactly the same?

**Comment by charleskawczynski** [comment]
> I'm going to try again after updating rrtmpg. How should I know if the problem still exists or not? Should I just compare two runs to see if they are exactly the same?

Yeah, I think that should be sufficient. The easiest way to do that, IMO, would be to

 - Add a job that exercises the code
 - Add an entry into the regression tests
 - Update the ref counter

And just wait to see if it breaks

**Comment by szy21** [comment]
Thanks! Will do that next time we upgrade dependencies.

**Comment by szy21** [comment]
I think I will close it and we can continue the discussion here: https://github.com/CliMA/RRTMGP.jl/issues/316
