### ISSUE TITLE
Logging with multiple processes duplicates info

### ISSUE THREAD

**Issue by simonbyrne** [CliMA/ClimaAtmos.jl#838]
e.g. https://buildkite.com/clima/climaatmos-scaling/builds/252#018335a9-1ee5-4adf-9eb9-d74f789b3aff

Probably needs some rearranging of the driver file

**Comment by charleskawczynski** [comment]
It looks like this has returned 😞

**Comment by charleskawczynski** [comment]
It looks like it may even be worse than before

**Comment by charleskawczynski** [comment]
https://buildkite.com/clima/climaatmos-ci/builds/3938#01839eca-e966-4e12-a558-8da915c8e9bc
