### ISSUE TITLE
Precipitation diagnostics are missing in the output

### ISSUE THREAD

**Issue by szy21** [CliMA/ClimaAtmos.jl#854]
`precipitation_removal, column_integrated_rain, column_integrated_snow` are missing in the diagnostics in moist simulations. I think [here](https://github.com/CliMA/ClimaAtmos.jl/blob/fb5be4dbfd99103def412231e06c8bce123216a3/examples/hybrid/callbacks.jl#L159) and [here](https://github.com/CliMA/ClimaAtmos.jl/blob/fb5be4dbfd99103def412231e06c8bce123216a3/examples/hybrid/callbacks.jl#L208) `propertynames(Y.c)` should be `propertynames(p)`.

cc @jiahe23 @trontrytel

**Comment by trontrytel** [comment]
@szy21  Could you check if this fixes the issue? https://github.com/CliMA/ClimaAtmos.jl/pull/855

**Comment by szy21** [comment]
Thanks!
