### ISSUE TITLE
Remove EDMF's dependence on `getindex(::Field, i)` support

### ISSUE THREAD

**Issue by charleskawczynski** [CliMA/ClimaAtmos.jl#887]
Perhaps rather than overloading getindex on `Int`s, we can define an `Up` type and overload getindex on it. This would at least preserve expected of ClimaCore behavior in the dycore.

**Comment by charleskawczynski** [comment]
The hard part of this issue is resolving https://github.com/CliMA/ClimaCore.jl/issues/77, but there's other low hanging fruit (e.g., removing use of `TC.Grid`)

**Comment by charleskawczynski** [comment]
The remaining piece here is removing getindex for surface indexing (e.g., `kc_surface`), now that we’ve removed all k-loops. There might also be the shrink mask that needs adjusted, but this could be written as a clima core operator

**Comment by trontrytel** [comment]
Is this also relevant for EDMFX? @nefrathenrici @dennisYatunin?

**Comment by charleskawczynski** [comment]
We can easily check by removing the overloaded methods and seeing if it still works

**Comment by charleskawczynski** [comment]
Code to strip out would be [here](https://github.com/CliMA/ClimaAtmos.jl/blob/main/src/TurbulenceConvection/Fields.jl#L37-L65)

**Comment by szy21** [comment]
The old code has been removed.
