### ISSUE TITLE
Create a separate test group for spatial convergence testing of selected test cases

### ISSUE THREAD

**Issue by bischtob** [CliMA/ClimaAtmos.jl#89]
**context**
We would like to make sure that our benchmark cases (or a selected subgroup) runs correctly upon grid refinement.

**ideas**
Take the grid refinement study from @bischtob, done in `ClimaCore.jl`, and adapt it to work with a test group in ClimaAtmos.

**next steps**
Use this script https://github.com/CliMA/ClimaCore.jl/blob/tb/box_2d_refinement/test/convergence_integration.jl, and adapt it.

**Comment by szy21** [comment]
Sounds good. I was thinking about closing #95 and tracking things in this issue. What do you think?

**Comment by bischtob** [comment]
Now done in ClimaCore.
