### ISSUE TITLE
Vertical diffusion does not work in dry simulations

### ISSUE THREAD

**Issue by szy21** [CliMA/ClimaAtmos.jl#961]
When use `--vert_diff true` for a dry simulation, this [line](https://github.com/CliMA/ClimaAtmos.jl/blob/3bb8021eee7e472f4df1976c3e0a30bc93f227c9/examples/hybrid/sphere/baroclinic_wave_utilities.jl#L280) gives an error.

**Comment by charleskawczynski** [comment]
Closed by #916
